#!/usr/bin/env python
"""GCDGS build 检查（不训练）：验证前向数值、全局上下文分支、通道分配、参数量、end2end/reg_max。

检查项：
1. GCDGS 单块前向：Kd 条 local 多尺度 + 1 条 global 上下文分支，通道按权重非对称分配、
   各分支参数独立、梯度都能回传（含全局分支的注意力池化 + transform）。
2. 全局分支 sanity：对空间常数输入，ctx == 该常数，广播加回后每个位置一致（真全局）。
3. gsdown neck 的 4 个 VoVGSCSP 全换成 GCDGS 后，整模型 build 通过：
   end2end=True / reg_max=1 / nl=3 / 输出 [1,300,6]。
4. fused params 与对照（gsdown 1.936M / base 2.376M / msdgs 1.777M）对比，确认没增肥。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py
    python install_gsconv_modules.py
    python install_gcdgs_module.py
    python build_check_gcdgs.py
"""
from __future__ import annotations

import os
from pathlib import Path

import torch
import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"


def build_doc(dilations, global_frac, r=4) -> dict:
    """把 gsdown head 里所有 VoVGSCSP 换成 GCDGS。backbone 一字不动。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            # VoVGSCSP args=[c2] -> GCDGS args=[c2, shortcut, g, e, dilations, global_frac, r]
            block[2] = "GCDGS"
            block[3] = [c2, True, 1, 0.5, list(dilations), float(global_frac), int(r)]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_swapped}"
    print(f"swapped {n_swapped} VoVGSCSP -> GCDGS (dilations={dilations}, global_frac={global_frac}, r={r})")
    return doc


def check_module():
    from ultralytics.nn.modules import GCDGS

    # c2=256, e=0.5 => c_=128；dilations=(1,3) => 2 local + 1 global，global_frac=1 => 三等分
    m = GCDGS(c1=128, c2=256, n=2, e=0.5, dilations=(1, 3), global_frac=1.0, r=4).eval()
    print("SPLITS", m.splits, "sum", sum(m.splits), "(c_ should be 128, Kd+1=3 parts)")
    assert sum(m.splits) == 128, m.splits
    assert len(m.splits) == 3, m.splits  # 2 local + 1 global

    x = torch.randn(2, 128, 32, 32)
    with torch.no_grad():
        y = m(x)
    assert y.shape == (2, 256, 32, 32), f"bad out shape {y.shape}"
    print(f"MODULE_FWD_OK in{tuple(x.shape)} -> out{tuple(y.shape)}")

    # local 分支 dilation 正确
    st = m.stages[0]
    dils = [st[k].dw.dilation for k in range(m.Kd)]
    print("LOCAL_DILATIONS", dils)
    assert dils == [(1, 1), (3, 3)], dils

    # 参数独立：所有 local dw + global att/transform 权重指针互不重叠
    ptrs = {st[k].dw.weight.data_ptr() for k in range(m.Kd)}
    ptrs.add(st[m.Kd].att.weight.data_ptr())
    assert len(ptrs) == m.Kd + 1, "branches share weights!"
    print("BRANCH_INDEPENDENCE_OK", m.Kd, "local +1 global disjoint weights")

    # 全局分支 sanity：空间常数输入 -> 每个空间位置输出一致（证明是真全局上下文）
    gc = st[m.Kd]
    cc = m.splits[m.Kd]
    const = torch.randn(1, cc, 1, 1).expand(1, cc, 8, 8).contiguous()
    with torch.no_grad():
        go = gc(const)
    spatial_var = go.var(dim=(2, 3)).max().item()
    print(f"GLOBAL_BRANCH_CONST_VAR {spatial_var:.3e} (should ~0: uniform in -> uniform out)")
    assert spatial_var < 1e-6, f"global branch not spatially uniform on const input: {spatial_var}"

    # 梯度隔离：所有分支（含全局）都拿到梯度
    x2 = torch.randn(1, 128, 16, 16, requires_grad=True)
    m(x2).sum().backward()
    for k in range(m.Kd):
        assert st[k].dw.weight.grad is not None, f"local branch {k} grad missing"
    assert st[m.Kd].att.weight.grad is not None, "global att grad missing"
    assert st[m.Kd].transform[0].weight.grad is not None, "global transform grad missing"
    print("GRAD_FLOW_OK all local + global branches receive gradient")


def check_model(dilations, global_frac, tag, r=4):
    doc = build_doc(dilations, global_frac, r)
    gen = ROOT / "generated_models_gcdgs_e250"
    gen.mkdir(parents=True, exist_ok=True)
    cfg = gen / f"y26n_gsdown_gcdgs_{tag}_e250.yaml"
    cfg.write_text("# generated by build_check_gcdgs.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"CFG {cfg}")

    model = YOLO(str(cfg))
    m = model.model
    print("end2end", getattr(m, "end2end", None))
    det = m.model[-1]
    print("reg_max", getattr(det, "reg_max", None), "nl", getattr(det, "nl", None))

    mf = model.model.fuse() if hasattr(model.model, "fuse") else model.model
    params = int(sum(p.numel() for p in mf.parameters()))
    print(f"FUSED_PARAMS {params} = {params/1e6:.3f}M (vs gsdown 1.936M, base 2.376M, msdgs 1.777M)")

    x = torch.randn(1, 3, 640, 640)
    model.model.eval()
    with torch.no_grad():
        y = model.model(x)

    def _shapes(o):
        if isinstance(o, dict):
            return {k: _shapes(v) for k, v in o.items()}
        if isinstance(o, (list, tuple)):
            return [_shapes(v) for v in o]
        return tuple(o.shape) if hasattr(o, "shape") else type(o).__name__

    print("FWD_OUT", _shapes(y))
    print(f"BUILD_OK {tag}")


if __name__ == "__main__":
    check_module()
    # 三候选：验证"弱类要全局上下文"假设
    check_model((1, 3), 1.0, "13g_eq")     # 2 local(d1,d3) + global，三等分
    check_model((1, 3, 5), 1.0, "135g")    # 3 local(d1,d3,d5) + global
    check_model((1, 3), 2.0, "13g_heavy")  # global 分支拿更多通道（若更好 => 假设坐实）
