#!/usr/bin/env python
"""DualBranchGS build 检查（不训练）：验证前向数值、结构、参数量、end2end/reg_max。

先验清楚再上 250e，避免浪费训练。检查项：
1. DualBranchGS 单块前向：输入输出通道/空间正确，两分支参数独立（不共享）。
2. gsdown neck 的 4 个 VoVGSCSP 全换成 DualBranchGS 后，整模型 build 通过：
   end2end=True / reg_max=1 / nl=3 / 前向输出 [1,300,6]。
3. fused params 与对照（gsdown 1.936M / base 2.376M）对比，确认没增肥。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py
    python install_gsconv_modules.py
    python install_dualbranch_module.py
    python build_check_dualbranch.py
"""
from __future__ import annotations

import os
from pathlib import Path

import torch
import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"


def build_doc(d: int = 3) -> dict:
    """把 gsdown head 里所有 VoVGSCSP 换成 DualBranchGS(追加 dilation=d)。backbone 一字不动。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        # block = [from, n, module, args]
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            # VoVGSCSP args=[c2] -> DualBranchGS args=[c2, shortcut, g, e, d]
            block[2] = "DualBranchGS"
            block[3] = [c2, True, 1, 0.5, int(d)]
            n_swapped += 1
    print(f"swapped {n_swapped} VoVGSCSP -> DualBranchGS (dilation={d})")
    assert n_swapped == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_swapped}"
    return doc


def check_module():
    """单块前向 + 两分支参数独立性。"""
    from ultralytics.nn.modules import DualBranchGS

    m = DualBranchGS(c1=128, c2=256, n=2, e=0.5, d=3).eval()
    x = torch.randn(2, 128, 32, 32)
    with torch.no_grad():
        y = m(x)
    assert y.shape == (2, 256, 32, 32), f"bad out shape {y.shape}"
    print(f"MODULE_FWD_OK in{tuple(x.shape)} -> out{tuple(y.shape)}")

    # 两分支参数确实独立（local[0] 与 global[0] 是不同 Parameter 对象）
    lp = m.locals[0].dw.weight
    gp = m.globals[0].dw.weight
    assert lp.data_ptr() != gp.data_ptr(), "local/global branches share weights!"
    # dilation 不同
    assert m.locals[0].dw.dilation == (1, 1), m.locals[0].dw.dilation
    assert m.globals[0].dw.dilation == (3, 3), m.globals[0].dw.dilation
    print("BRANCH_INDEPENDENCE_OK local.dil=(1,1) global.dil=(3,3) weights disjoint")

    # 梯度隔离：只对输出前半（local 主导的通道走向）回传，检查两分支都能拿到梯度
    x2 = torch.randn(1, 128, 16, 16, requires_grad=True)
    out = m(x2).sum()
    out.backward()
    assert lp.grad is not None and gp.grad is not None, "branch grad missing"
    print("GRAD_FLOW_OK both branches receive gradient")


def check_model(d: int = 3):
    doc = build_doc(d)
    gen = ROOT / "generated_models_dualbranch_e250"
    gen.mkdir(parents=True, exist_ok=True)
    cfg = gen / f"y26n_gsdown_dualbranch_d{d}_e250.yaml"
    cfg.write_text("# generated by build_check_dualbranch.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"CFG {cfg}")

    model = YOLO(str(cfg))
    m = model.model
    print("end2end", getattr(m, "end2end", None))
    # reg_max 在 Detect 头
    det = m.model[-1]
    print("reg_max", getattr(det, "reg_max", None), "nl", getattr(det, "nl", None))

    # fused params
    mf = model.model.fuse() if hasattr(model.model, "fuse") else model.model
    params = int(sum(p.numel() for p in mf.parameters()))
    print(f"FUSED_PARAMS {params} = {params/1e6:.3f}M "
          f"(vs gsdown 1.936M, base 2.376M)")

    # forward
    x = torch.randn(1, 3, 640, 640)
    model.model.eval()
    with torch.no_grad():
        y = model.model(x)
    if isinstance(y, (list, tuple)):
        shapes = [tuple(t.shape) for t in y if hasattr(t, "shape")]
    else:
        shapes = tuple(y.shape)
    print("FWD_OUT", shapes)
    print("BUILD_OK")
    return cfg


if __name__ == "__main__":
    check_module()
    check_model(d=3)
