#!/usr/bin/env python
"""MSDGS build 检查（不训练）：验证前向数值、非对称通道分配、参数量、end2end/reg_max。

检查项：
1. MSDGS 单块前向：多分支 dilation 各异、通道按 fracs 非对称分配（splits 正确）、
   各分支参数独立、梯度都能回传。
2. gsdown neck 的 4 个 VoVGSCSP 全换成 MSDGS 后，整模型 build 通过：
   end2end=True / reg_max=1 / nl=3 / 输出 [1,300,6]。
3. fused params 与对照（gsdown 1.936M / base 2.376M）对比，确认没增肥。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py
    python install_gsconv_modules.py
    python install_msdgs_module.py
    python build_check_msdgs.py
"""
from __future__ import annotations

import os
from pathlib import Path

import torch
import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"


def build_doc(dilations, fracs) -> dict:
    """把 gsdown head 里所有 VoVGSCSP 换成 MSDGS。backbone 一字不动。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            # VoVGSCSP args=[c2] -> MSDGS args=[c2, shortcut, g, e, dilations, fracs]
            block[2] = "MSDGS"
            block[3] = [c2, True, 1, 0.5, list(dilations), list(fracs)]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_swapped}"
    print(f"swapped {n_swapped} VoVGSCSP -> MSDGS (dilations={dilations}, fracs={fracs})")
    return doc


def check_module():
    from ultralytics.nn.modules import MSDGS

    # c2=256, e=0.5 => c_=128；fracs=(2,1,1) 非对称：局部分支拿一半通道
    m = MSDGS(c1=128, c2=256, n=2, e=0.5, dilations=(1, 3, 5), fracs=(2, 1, 1)).eval()
    print("SPLITS", m.splits, "sum", sum(m.splits), "(c_ should be 128)")
    assert sum(m.splits) == 128, m.splits
    # 非对称：第一份(局部)应约为后两份之和
    assert m.splits[0] > m.splits[1] and m.splits[0] > m.splits[2], f"not asymmetric: {m.splits}"

    x = torch.randn(2, 128, 32, 32)
    with torch.no_grad():
        y = m(x)
    assert y.shape == (2, 256, 32, 32), f"bad out shape {y.shape}"
    print(f"MODULE_FWD_OK in{tuple(x.shape)} -> out{tuple(y.shape)}")

    # 各分支 dilation 正确且参数独立
    st = m.stages[0]
    dils = [st[k].dw.dilation for k in range(len(st))]
    print("DILATIONS", dils)
    assert dils == [(1, 1), (3, 3), (5, 5)], dils
    ptrs = {st[k].dw.weight.data_ptr() for k in range(len(st))}
    assert len(ptrs) == len(st), "branches share weights!"
    print("BRANCH_INDEPENDENCE_OK 3 branches disjoint weights")

    # 梯度隔离：所有分支都拿到梯度
    x2 = torch.randn(1, 128, 16, 16, requires_grad=True)
    m(x2).sum().backward()
    for k in range(len(st)):
        assert st[k].dw.weight.grad is not None, f"branch {k} grad missing"
    print("GRAD_FLOW_OK all branches receive gradient")


def check_model(dilations, fracs, tag):
    doc = build_doc(dilations, fracs)
    gen = ROOT / "generated_models_msdgs_e250"
    gen.mkdir(parents=True, exist_ok=True)
    cfg = gen / f"y26n_gsdown_msdgs_{tag}_e250.yaml"
    cfg.write_text("# generated by build_check_msdgs.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"CFG {cfg}")

    model = YOLO(str(cfg))
    m = model.model
    print("end2end", getattr(m, "end2end", None))
    det = m.model[-1]
    print("reg_max", getattr(det, "reg_max", None), "nl", getattr(det, "nl", None))

    mf = model.model.fuse() if hasattr(model.model, "fuse") else model.model
    params = int(sum(p.numel() for p in mf.parameters()))
    print(f"FUSED_PARAMS {params} = {params/1e6:.3f}M (vs gsdown 1.936M, base 2.376M)")

    x = torch.randn(1, 3, 640, 640)
    model.model.eval()
    with torch.no_grad():
        y = model.model(x)

    def _shapes(o):
        if isinstance(o, dict):
            return {k: _shapes(v) for k, v in o.items()}
        if isinstance(o, (list, tuple)):
            return [_shapes(v) for v in o]
        return tuple(o.shape) if hasattr(o, "shape") else type(o).__name__

    print("FWD_OUT", _shapes(y))
    print(f"BUILD_OK {tag}")


if __name__ == "__main__":
    check_module()
    # 三个候选各 build 一次
    check_model((1, 3, 5), (1, 1, 1), "135eq")
    check_model((1, 3, 5), (2, 1, 1), "135local")
    check_model((1, 3), (2, 1), "13local")
