#!/usr/bin/env python
"""Strict build gate for the MSDGS P4-texture -> P5-class-logit candidate."""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import subprocess
import sys

import torch
import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_clstex_e250"
CHECK_DIR = ROOT / "runs_msdgs_clstex_e250" / "build_check"
CANDIDATE = "msdgs_p5cls_p4tex"
SPEC = [0.1, 3]


def generate_yaml() -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    last = doc["head"][-1]
    assert last[0] == [16, 19, 22] and last[2] == "Detect", last
    last[2] = "MSDGSClsTexDetect"
    last[3] = ["nc", *SPEC]
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GEN_DIR / f"{CANDIDATE}.yaml"
    path.write_text("# generated by build_check_msdgs_clstex.py\n" + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    return path


def output_shape(output):
    if torch.is_tensor(output):
        return tuple(output.shape)
    if isinstance(output, (list, tuple)) and output and torch.is_tensor(output[0]):
        return tuple(output[0].shape)
    return None


def tensor_max_abs(a, b) -> float:
    values = []
    if torch.is_tensor(a) and torch.is_tensor(b):
        values.append(float((a - b).abs().max()))
    elif isinstance(a, dict) and isinstance(b, dict):
        assert a.keys() == b.keys(), (a.keys(), b.keys())
        values.extend(tensor_max_abs(a[k], b[k]) for k in a)
    elif isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        assert len(a) == len(b)
        values.extend(tensor_max_abs(x, y) for x, y in zip(a, b))
    else:
        assert type(a) is type(b), (type(a), type(b))
    return max(values, default=0.0)


def max_parameter_grad(parameters) -> float:
    return max((float(p.grad.abs().max()) if p.grad is not None else 0.0) for p in parameters)


def fresh_features():
    return [
        torch.randn(1, 64, 20, 20, requires_grad=True),
        torch.randn(1, 128, 10, 10, requires_grad=True),
        torch.randn(1, 256, 5, 5, requires_grad=True),
    ]


def shared_state_exact(standard, custom, prefixes) -> tuple[int, float]:
    a, b = standard.state_dict(), custom.state_dict()
    keys = [k for k in a if any(k.startswith(prefix) for prefix in prefixes)]
    assert keys
    assert all(k in b and a[k].shape == b[k].shape for k in keys)
    return len(keys), max(float((a[k] - b[k]).abs().max()) for k in keys)


def behavior_check() -> dict:
    from ultralytics.nn.modules.head import Detect
    from ultralytics.nn.modules.yolo26_msdgs_clstex import MSDGSClsTexDetect

    Detect.legacy = False
    MSDGSClsTexDetect.legacy = False
    torch.manual_seed(49)
    standard = Detect(nc=6, reg_max=1, end2end=True, ch=(64, 128, 256))
    custom = MSDGSClsTexDetect(nc=6, logit_scale=SPEC[0], pool_kernel=SPEC[1], reg_max=1, end2end=True, ch=(64, 128, 256))
    missing, unexpected = custom.load_state_dict(standard.state_dict(), strict=False)
    assert not unexpected, unexpected
    expected_prefixes = ("p5_cls_texture.", "one2one_p5_cls_texture.")
    assert missing and all(k.startswith(expected_prefixes) for k in missing), missing
    assert custom.p5_cls_texture is not custom.one2one_p5_cls_texture
    assert not ({id(p) for p in custom.p5_cls_texture.parameters()} & {id(p) for p in custom.one2one_p5_cls_texture.parameters()})
    for branch in (custom.p5_cls_texture, custom.one2one_p5_cls_texture):
        assert torch.count_nonzero(branch.proj.weight) == 0
        assert torch.count_nonzero(branch.proj.bias) == 0

    box_items, box_state_error = shared_state_exact(standard, custom, ("cv2.", "one2one_cv2."))
    cls_items, cls_state_error = shared_state_exact(standard, custom, ("cv3.", "one2one_cv3."))
    assert box_state_error == 0.0 and cls_state_error == 0.0

    standard.stride[:] = torch.tensor([8.0, 16.0, 32.0])
    custom.stride[:] = standard.stride
    standard.eval(); custom.eval()
    features = [torch.randn(1, 64, 80, 80), torch.randn(1, 128, 40, 40), torch.randn(1, 256, 20, 20)]
    with torch.no_grad():
        equivalence_error = tensor_max_abs(standard([x.clone() for x in features]), custom([x.clone() for x in features]))
        p3_cls_error = float((standard.cv3[0](features[0]) - custom.cv3[0](features[0])).abs().max())
        p4_cls_error = float((standard.cv3[1](features[1]) - custom.cv3[1](features[1])).abs().max())
    assert equivalence_error < 1e-6, equivalence_error
    assert p3_cls_error == 0.0 and p4_cls_error == 0.0

    custom.train(); custom.zero_grad(set_to_none=True)
    o2o_features = fresh_features()
    custom(o2o_features)["one2one"]["scores"].sum().backward()
    o2o_input_grad = max(float(x.grad.abs().max()) if x.grad is not None else 0.0 for x in o2o_features)
    o2o_tex_grad = max_parameter_grad(custom.one2one_p5_cls_texture.parameters())
    o2m_tex_grad_from_o2o = max_parameter_grad(custom.p5_cls_texture.parameters())
    assert o2o_input_grad == 0.0 and o2o_tex_grad > 0.0 and o2m_tex_grad_from_o2o == 0.0

    custom.zero_grad(set_to_none=True)
    o2m_features = fresh_features()
    custom(o2m_features)["one2many"]["scores"].sum().backward()
    o2m_p4_input_grad = float(o2m_features[1].grad.abs().max())
    o2m_tex_grad = max_parameter_grad(custom.p5_cls_texture.parameters())
    o2o_tex_grad_from_o2m = max_parameter_grad(custom.one2one_p5_cls_texture.parameters())
    assert o2m_p4_input_grad > 0.0 and o2m_tex_grad > 0.0 and o2o_tex_grad_from_o2m == 0.0

    return {
        "equivalence_max_abs_error": equivalence_error,
        "p3_cls_logit_error": p3_cls_error,
        "p4_cls_logit_error": p4_cls_error,
        "box_state_items": box_items,
        "box_state_max_abs_error": box_state_error,
        "cls_state_items": cls_items,
        "cls_state_max_abs_error": cls_state_error,
        "missing_texture_state_items": len(missing),
        "one2one_input_grad_max": o2o_input_grad,
        "one2one_texture_grad_max": o2o_tex_grad,
        "one2many_texture_grad_from_one2one": o2m_tex_grad_from_o2o,
        "one2many_p4_input_grad_max": o2m_p4_input_grad,
        "one2many_texture_grad_max": o2m_tex_grad,
        "one2one_texture_grad_from_one2many": o2o_tex_grad_from_o2m,
    }


def model_gflops(model):
    try:
        from ultralytics.utils.torch_utils import get_flops
        return float(get_flops(model, imgsz=640))
    except Exception as exc:  # noqa: BLE001
        print("WARN_GFLOPS", repr(exc))
        return None


def matched_tensor_count(source, target) -> int:
    source_state, target_state = source.state_dict(), target.state_dict()
    return sum(k in target_state and target_state[k].shape == v.shape for k, v in source_state.items())


def reload_worker(weights: Path) -> int:
    from ultralytics import YOLO
    wrapper = YOLO(str(weights), task="detect")
    head = wrapper.model.model[-1]
    wrapper.model.eval()
    with torch.no_grad():
        shape = output_shape(wrapper.model(torch.zeros(1, 3, 640, 640)))
    print(json.dumps({"head": type(head).__name__, "shape": shape}))
    return 0 if type(head).__name__ == "MSDGSClsTexDetect" and shape == (1, 300, 6) else 2


def model_check() -> dict:
    from ultralytics import YOLO
    cfg = generate_yaml()
    source = YOLO(str(OFFICIAL_WEIGHTS), task="detect").model
    baseline = YOLO(str(BASE_YAML), task="detect").model
    wrapper = YOLO(str(cfg), task="detect")
    model, head = wrapper.model, wrapper.model.model[-1]
    assert type(head).__name__ == "MSDGSClsTexDetect"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    assert tuple(head.input_channels) == (64, 128, 256)
    base_match = matched_tensor_count(source, baseline)
    candidate_match = matched_tensor_count(source, model)
    assert candidate_match == base_match, (candidate_match, base_match)
    wrapper.load(str(OFFICIAL_WEIGHTS))
    model.eval()
    with torch.no_grad():
        shape = output_shape(model(torch.zeros(1, 3, 640, 640)))
    assert shape == (1, 300, 6), shape
    assert [int(t[0].conv.out_channels) for t in head.cv2] == [16, 16, 16]
    assert [int(t[0].conv.out_channels) for t in head.one2one_cv2] == [16, 16, 16]

    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint = CHECK_DIR / f"{CANDIDATE}_roundtrip.pt"
    wrapper.save(str(checkpoint))
    child = subprocess.run([sys.executable, str(Path(__file__).resolve()), "--reload-check", str(checkpoint)], text=True, capture_output=True, check=False)
    print(child.stdout, end="")
    if child.stderr: print(child.stderr, file=sys.stderr, end="")
    assert child.returncode == 0, child.returncode

    gflops_eval = model_gflops(model)
    fused = copy.deepcopy(model).eval(); fused.fuse()
    fused_head = fused.model[-1]
    assert fused_head.p5_cls_texture is None and fused_head.one2one_p5_cls_texture is not None
    fused_params = int(sum(p.numel() for p in fused.parameters()))
    gflops_fused = model_gflops(fused)
    with torch.no_grad():
        fused_shape = output_shape(fused(torch.zeros(1, 3, 640, 640)))
    assert fused_shape == (1, 300, 6), fused_shape
    return {
        "cfg": str(cfg), "head": type(head).__name__, "end2end": bool(head.end2end),
        "reg_max": int(head.reg_max), "nl": int(head.nl), "input_channels": list(head.input_channels),
        "box_widths": [int(t[0].conv.out_channels) for t in head.cv2],
        "official_matched_tensors": candidate_match, "baseline_matched_tensors": base_match,
        "eval_shape": list(shape), "fused_shape": list(fused_shape),
        "params_unfused": int(sum(p.numel() for p in model.parameters())), "params_fused": fused_params,
        "gflops_eval_graph": gflops_eval, "gflops_fused_inference": gflops_fused,
        "roundtrip_checkpoint": str(checkpoint),
    }


def main() -> int:
    parser = argparse.ArgumentParser(); parser.add_argument("--reload-check", type=Path); args = parser.parse_args()
    if args.reload_check: return reload_worker(args.reload_check)
    for path in (BASE_YAML, OFFICIAL_WEIGHTS):
        if not path.exists(): raise FileNotFoundError(path)
    payload = {"behavior": behavior_check(), "candidate": model_check()}
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    report = CHECK_DIR / "report.json"
    report.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(payload, indent=2, ensure_ascii=False)); print("BUILD_CHECK_MSDGS_CLSTEX_OK", report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
