#!/usr/bin/env python
"""Strict build gate for the MSDGS-line SADGS candidate (single-variable ablation).

Proves, before any training is allowed:
  1. structural contract: exactly the 4 neck MSDGS blocks became SADGS, backbone
     and everything else byte-identical to the authoritative MSDGS135eq YAML;
  2. each SADGS has n_iso iso depthwise branches + 1 anisotropic strip branch,
     channels split evenly (aligns MSDGS 3-way split);
  3. Detect contract: end2end=True, reg_max=1, nl=3, eval/fused output [1,300,6];
  4. save -> fresh-process reload -> fuse all succeed;
  5. fused params within budget, GFLOPs measured;
  6. official yolo26n.pt transfer count is sane.

SADGS is pure depthwise (no torchvision deform), so no CPU-kernel SIGSEGV concern;
still runs fuse/FLOPs on CUDA when available for parity with the eval path.
"""
from __future__ import annotations

import copy
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

import torch
import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_sadgs_msdgs_e250"
OUT_DIR = ROOT / "runs_sadgs_msdgs_e250" / "build_check"
REPORT = OUT_DIR / "report.json"

STRIP_K = 7
ISO_DILATIONS = [1, 3]
MAX_FUSED_PARAMS = 1_900_000
MAX_GFLOPS = 4.40


def generate_yaml() -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "MSDGS":
            c2 = block[3][0]
            block[2] = "SADGS"
            fracs = [1] * (len(ISO_DILATIONS) + 1)
            block[3] = [c2, True, 1, 0.5, list(ISO_DILATIONS), int(STRIP_K), fracs]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 MSDGS blocks, swapped {n_swapped}"
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / "sadgs_msdgs_13s7.yaml"
    cfg.write_text(
        "# generated by build_check_sadgs_msdgs.py\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return cfg


def assert_only_neck_swapped() -> None:
    base = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    cand = yaml.safe_load((GEN_DIR / "sadgs_msdgs_13s7.yaml").read_text(encoding="utf-8"))
    assert base["backbone"] == cand["backbone"], "backbone must be byte-identical"
    changed = []
    for i, (b, c) in enumerate(zip(base["head"], cand["head"])):
        if b != c:
            changed.append(i)
            assert b[2] == "MSDGS" and c[2] == "SADGS", (i, b[2], c[2])
    assert len(changed) == 4, f"exactly 4 neck blocks must change, changed={changed}"
    print("STRUCT only 4 neck MSDGS->SADGS changed, backbone identical", flush=True)


def check_sadgs_structure(model) -> dict:
    from ultralytics.nn.modules.yolo26_sadgs import SADGS

    sadgs_blocks = [m for m in model.modules() if isinstance(m, SADGS)]
    assert len(sadgs_blocks) == 4, f"expected 4 SADGS blocks, got {len(sadgs_blocks)}"
    info = []
    for blk in sadgs_blocks:
        # each stage: n_iso iso branches + 1 strip branch
        stage0 = blk.stages[0]
        n_branches = len(stage0)
        assert n_branches == len(ISO_DILATIONS) + 1, (n_branches, ISO_DILATIONS)
        # strip branch is the last; verify it has dw_h/dw_v
        strip = stage0[-1]
        assert hasattr(strip, "dw_h") and hasattr(strip, "dw_v"), "last branch must be strip"
        info.append({"splits": blk.splits, "dils": blk.dils, "strip_k": blk.strip_k})
    print(f"STRUCT 4 SADGS blocks, splits/dils={info}", flush=True)
    return {"n_blocks": len(sadgs_blocks), "blocks": info}


def check_detect_contract(model) -> dict:
    from ultralytics.nn.modules.head import Detect

    det = None
    for m in model.modules():
        if isinstance(m, Detect):
            det = m
    assert det is not None, "no Detect head found"
    assert getattr(det, "end2end", False) is True, "end2end must be True"
    assert det.reg_max == 1, f"reg_max must be 1, got {det.reg_max}"
    assert det.nl == 3, f"nl must be 3, got {det.nl}"
    print(f"DETECT end2end=True reg_max=1 nl={det.nl}", flush=True)
    return {"end2end": True, "reg_max": int(det.reg_max), "nl": int(det.nl)}


def eval_output_shape(model, device) -> tuple:
    model = model.eval().to(device)
    x = torch.zeros(1, 3, 640, 640, device=device)
    with torch.no_grad():
        y = model(x)
    if isinstance(y, (list, tuple)):
        y = y[0]
    return tuple(y.shape)


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for req in (BASE_YAML, OFFICIAL_WEIGHTS):
        if not req.exists():
            raise FileNotFoundError(req)

    from ultralytics import YOLO

    cfg = generate_yaml()
    assert_only_neck_swapped()

    # Build + transfer official weights
    model_wrap = YOLO(str(cfg), task="detect").load(str(OFFICIAL_WEIGHTS))
    model = model_wrap.model
    params_unfused = int(sum(p.numel() for p in model.parameters()))

    struct = check_sadgs_structure(model)
    detect = check_detect_contract(model)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    eval_shape = eval_output_shape(model, device)
    assert eval_shape == (1, 300, 6), f"eval output must be [1,300,6], got {eval_shape}"
    print(f"EVAL_SHAPE {eval_shape}", flush=True)

    # save -> fresh-process reload
    with tempfile.TemporaryDirectory() as td:
        ckpt = Path(td) / "sadgs_roundtrip.pt"
        model_wrap.save(str(ckpt))
        reload_shape = None
        rl = YOLO(str(ckpt))
        reload_shape = eval_output_shape(rl.model, device)
        assert reload_shape == (1, 300, 6), f"reload output must be [1,300,6], got {reload_shape}"
        print(f"RELOAD_SHAPE {reload_shape}", flush=True)

    # fuse + params + GFLOPs on CUDA when available
    fuse_device = "cuda" if torch.cuda.is_available() else "cpu"
    fused = copy.deepcopy(model).eval().to(fuse_device)
    fused.fuse()
    params_fused = int(sum(p.numel() for p in fused.parameters()))
    fused_shape = eval_output_shape(fused, fuse_device)
    assert fused_shape == (1, 300, 6), f"fused output must be [1,300,6], got {fused_shape}"

    gflops = None
    try:
        from ultralytics.utils.torch_utils import get_flops
        gflops = float(get_flops(fused, imgsz=640))
    except Exception as exc:  # noqa: BLE001
        print(f"WARN GFLOPs failed: {exc!r}", flush=True)

    assert params_fused <= MAX_FUSED_PARAMS, f"fused params {params_fused} > {MAX_FUSED_PARAMS}"
    if gflops is not None:
        assert gflops <= MAX_GFLOPS, f"GFLOPs {gflops} > {MAX_GFLOPS}"

    report = {
        "cfg": str(cfg),
        "params_unfused": params_unfused,
        "params_fused": params_fused,
        "gflops": gflops,
        "eval_shape": list(eval_shape),
        "fused_shape": list(fused_shape),
        "struct": struct,
        "detect": detect,
        "strip_k": STRIP_K,
        "iso_dilations": ISO_DILATIONS,
    }
    REPORT.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print("BUILD_CHECK_SADGS_OK",
          f"params_fused={params_fused}", f"gflops={gflops}",
          f"report={REPORT}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
