#!/usr/bin/env python
"""CUDA build gate for MSDGS Backbone P4 Stable-DCNv2 (iter062)."""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import subprocess
import sys

import torch
import torch.nn.functional as F
import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_backbone_stable_dcnv2_e250"
CHECK_DIR = ROOT / "runs_msdgs_backbone_stable_dcnv2_e250" / "build_check"
CANDIDATE = "msdgs_bb_p4_stable_dcnv2"
MAX_FUSED_PARAMS = 1_900_000
MAX_GFLOPS = 4.40


def stub_flops() -> None:
    import ultralytics.utils.torch_utils as torch_utils

    torch_utils.get_flops = lambda *a, **k: 0.0
    torch_utils.get_flops_with_torch_profiler = lambda *a, **k: 0.0


def generate_yaml() -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    layer = doc["backbone"][6]
    assert layer[0] == -1 and layer[1] == 2 and layer[2] == "C3k2", layer
    assert layer[3][0] == 512 and layer[3][1] is True, layer
    layer[2] = "C3k2StableDCNv2"
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GEN_DIR / f"{CANDIDATE}.yaml"
    path.write_text(
        "# generated by build_check_msdgs_backbone_stable_dcnv2.py\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return path


def output_tensor(output):
    if torch.is_tensor(output):
        return output
    if isinstance(output, (list, tuple)) and output and torch.is_tensor(output[0]):
        return output[0]
    raise TypeError(f"cannot extract decoded tensor from {type(output)!r}")


def output_shape(output):
    return tuple(output_tensor(output).shape)


def max_grad(parameters) -> float:
    return max(
        (float(p.grad.abs().max()) if p.grad is not None else 0.0 for p in parameters),
        default=0.0,
    )


def module_behavior_check(device: torch.device) -> dict:
    from ultralytics.nn.modules.block import Bottleneck
    from ultralytics.nn.modules.yolo26_msdgs_backbone_stable_dcnv2 import (
        C3k2StableDCNv2,
        DCNv2StableUnit,
        register_stable_offset_mask_grad_hooks,
        set_stable_deform_strength,
        stable_deform_strength_for_epoch,
    )

    torch.manual_seed(62)
    custom = C3k2StableDCNv2(128, 128, n=2, c3k=True).to(device)
    assert custom.deform_units > 0
    deform_seen = 0
    for module in custom.modules():
        if isinstance(module, Bottleneck):
            assert isinstance(module.cv2, DCNv2StableUnit), type(module.cv2).__name__
            deform_seen += 1
    assert deform_seen == custom.deform_units

    unit = next(module for module in custom.modules() if isinstance(module, DCNv2StableUnit))
    unit.eval()
    x = torch.randn(2, unit.offset_mask.in_channels, 20, 20, device=device)
    set_stable_deform_strength(unit, 0.0)
    with torch.no_grad():
        offset0, mask0 = unit.compute_offset_mask(x)
        stable_regular = unit(x)
        conv_regular = unit.act(
            unit.bn(
                F.conv2d(
                    x,
                    unit.deform.weight,
                    bias=None,
                    stride=unit.s,
                    padding=unit.pad,
                    groups=unit.groups,
                )
            )
        )
    offset0_max = float(offset0.abs().max())
    mask0_dev = float((mask0 - 1.0).abs().max())
    regular_error = float((stable_regular - conv_regular).abs().max())
    assert offset0_max == 0.0
    assert mask0_dev == 0.0
    assert regular_error < 1e-4, regular_error

    strengths = {epoch: stable_deform_strength_for_epoch(epoch) for epoch in (0, 20, 21, 50, 80, 249)}
    assert strengths[0] == 0.0 and strengths[20] == 0.0
    assert 0.0 < strengths[21] < strengths[50] < 1.0
    assert strengths[80] == 1.0 and strengths[249] == 1.0

    with torch.no_grad():
        unit.offset_mask.weight.normal_(mean=0.0, std=2.0)
        unit.offset_mask.bias.normal_(mean=0.0, std=2.0)
    set_stable_deform_strength(unit, 1.0)
    with torch.no_grad():
        bounded_offset, bounded_mask = unit.compute_offset_mask(x)
    offset_abs_max = float(bounded_offset.abs().max())
    mask_min = float(bounded_mask.min())
    mask_max = float(bounded_mask.max())
    assert offset_abs_max <= 1.500001, offset_abs_max
    assert mask_min >= 0.499999 and mask_max <= 1.500001, (mask_min, mask_max)

    # Verify the helper scales only offset/mask predictor gradients by exactly 0.25.
    reference = DCNv2StableUnit(16, 16).to(device).eval()
    hooked = copy.deepcopy(reference).to(device).eval()
    with torch.no_grad():
        reference.offset_mask.weight.normal_(0.0, 0.05)
        reference.offset_mask.bias.normal_(0.0, 0.05)
        hooked.load_state_dict(reference.state_dict())
    set_stable_deform_strength(reference, 0.5)
    set_stable_deform_strength(hooked, 0.5)
    handles = register_stable_offset_mask_grad_hooks(hooked, 0.25)
    probe = torch.randn(2, 16, 12, 12, device=device)
    reference(probe).square().mean().backward()
    hooked(probe).square().mean().backward()
    grad_diffs = []
    for p_ref, p_hook in zip(reference.offset_mask.parameters(), hooked.offset_mask.parameters()):
        assert p_ref.grad is not None and p_hook.grad is not None
        grad_diffs.append(float((p_hook.grad - 0.25 * p_ref.grad).abs().max()))
    hook_scale_error = max(grad_diffs)
    assert hook_scale_error < 1e-7, hook_scale_error
    for handle in handles:
        handle.remove()

    # Full block backward at non-zero strength.
    set_stable_deform_strength(custom, 0.5)
    custom.train()
    custom.zero_grad(set_to_none=True)
    custom(torch.randn(2, 128, 16, 16, device=device)).square().mean().backward()
    offset_grad = max_grad(unit.offset_mask.parameters())
    deform_grad = max_grad(unit.deform.parameters())
    outer_grad = max_grad(custom.cv1.parameters())
    assert offset_grad > 0.0 and deform_grad > 0.0 and outer_grad > 0.0

    return {
        "device": str(device),
        "deform_units_smoke": int(custom.deform_units),
        "deform_units_seen": int(deform_seen),
        "strength_schedule": {str(k): v for k, v in strengths.items()},
        "strength0_offset_max_abs": offset0_max,
        "strength0_mask_dev_from_one": mask0_dev,
        "strength0_regular_conv_max_abs_error": regular_error,
        "strength1_offset_abs_max": offset_abs_max,
        "strength1_mask_min": mask_min,
        "strength1_mask_max": mask_max,
        "gradient_scale_target": 0.25,
        "gradient_scale_max_abs_error": hook_scale_error,
        "offset_grad": offset_grad,
        "deform_grad": deform_grad,
        "outer_cv1_grad": outer_grad,
    }


def matched_tensor_count(source, target) -> int:
    source_state, target_state = source.state_dict(), target.state_dict()
    return sum(k in target_state and target_state[k].shape == v.shape for k, v in source_state.items())


def reload_worker(weights: Path) -> int:
    stub_flops()
    from ultralytics import YOLO
    from ultralytics.nn.modules.yolo26_msdgs_backbone_stable_dcnv2 import DCNv2StableUnit

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is required for Stable-DCNv2 reload gate")
    model = YOLO(str(weights), task="detect").model.eval().cuda()
    with torch.no_grad():
        shape = output_shape(model(torch.zeros(1, 3, 640, 640, device="cuda")))
    payload = {
        "layer6": type(model.model[6]).__name__,
        "layer8": type(model.model[8]).__name__,
        "layer10": type(model.model[10]).__name__,
        "deform_units": sum(isinstance(m, DCNv2StableUnit) for m in model.model[6].modules()),
        "shape": shape,
    }
    print(json.dumps(payload))
    ok = (
        payload["layer6"] == "C3k2StableDCNv2"
        and payload["layer8"] == "C3k2"
        and payload["layer10"] == "C2PSA"
        and payload["deform_units"] == 2
        and shape == (1, 300, 6)
    )
    return 0 if ok else 2


def model_check(device: torch.device) -> dict:
    stub_flops()
    from ultralytics import YOLO
    from ultralytics.nn.modules.yolo26_msdgs_backbone_stable_dcnv2 import (
        DCNv2StableUnit,
        register_stable_offset_mask_grad_hooks,
        set_stable_deform_strength,
        transfer_standard_to_stable_dcnv2,
    )
    from ultralytics.utils.torch_utils import get_flops

    cfg = generate_yaml()
    base_doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    candidate_doc = yaml.safe_load(cfg.read_text(encoding="utf-8"))
    for key in base_doc:
        if key != "backbone":
            assert candidate_doc[key] == base_doc[key], key
    changed_indices = [
        i
        for i, pair in enumerate(zip(base_doc["backbone"], candidate_doc["backbone"]))
        if pair[0] != pair[1]
    ]
    assert changed_indices == [6], changed_indices

    source = YOLO(str(OFFICIAL_WEIGHTS), task="detect").model
    baseline = YOLO(str(BASE_YAML), task="detect").load(str(OFFICIAL_WEIGHTS)).model
    wrapper = YOLO(str(cfg), task="detect")
    model = wrapper.model
    head = model.model[-1]
    assert type(model.model[6]).__name__ == "C3k2StableDCNv2"
    assert type(model.model[8]).__name__ == "C3k2"
    assert type(model.model[10]).__name__ == "C2PSA"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    detect_channels = tuple(int(t[0].conv.in_channels) for t in head.cv2)
    assert detect_channels == (64, 128, 256), detect_channels
    deform_units = sum(isinstance(m, DCNv2StableUnit) for m in model.model[6].modules())
    assert deform_units == 2, deform_units

    missing, unexpected = model.load_state_dict(baseline.state_dict(), strict=False)
    assert unexpected and all(k.startswith("model.6.") and k.endswith(".cv2.conv.weight") for k in unexpected)
    assert missing and all(
        k.startswith("model.6.")
        and (".cv2.offset_mask." in k or ".cv2.deform." in k or k.endswith(".deform_strength"))
        for k in missing
    ), missing
    transferred = transfer_standard_to_stable_dcnv2(model, baseline.state_dict())
    assert transferred == deform_units
    set_stable_deform_strength(model, 0.0)

    base_state, candidate_state = baseline.state_dict(), model.state_dict()
    preserved_keys = [
        k for k in base_state
        if k.startswith("model.6.")
        and not k.endswith(".cv2.conv.weight")
        and k in candidate_state
        and candidate_state[k].shape == base_state[k].shape
    ]
    preserved_error = max(float((base_state[k] - candidate_state[k]).abs().max()) for k in preserved_keys)
    assert preserved_error == 0.0

    baseline = baseline.eval().to(device)
    model = model.eval().to(device)
    x = torch.randn(1, 3, 640, 640, device=device)
    captured = {}
    hook_a = baseline.model[6].register_forward_hook(lambda _m, _i, o: captured.setdefault("base6", o.detach()))
    hook_b = model.model[6].register_forward_hook(lambda _m, _i, o: captured.setdefault("cand6", o.detach()))
    with torch.no_grad():
        base_out = baseline(x.clone())
        cand_out = model(x.clone())
    hook_a.remove(); hook_b.remove()
    layer6_error = float((captured["base6"] - captured["cand6"]).abs().max())
    full_error = float((output_tensor(base_out) - output_tensor(cand_out)).abs().max())
    assert layer6_error < 1e-4, layer6_error
    assert full_error < 1e-4, full_error

    # CUDA forward/backward at non-zero strength.
    set_stable_deform_strength(model, 0.5)
    model.train()
    model.zero_grad(set_to_none=True)
    train_out = model(torch.randn(1, 3, 320, 320, device=device))
    tensors = []
    stack = [train_out]
    while stack:
        item = stack.pop()
        if torch.is_tensor(item):
            tensors.append(item)
        elif isinstance(item, (list, tuple)):
            stack.extend(item)
        elif isinstance(item, dict):
            stack.extend(item.values())
    assert tensors
    sum(t.float().square().mean() for t in tensors).backward()
    backward_offset_grad = max_grad(
        p for unit in model.model[6].modules() if isinstance(unit, DCNv2StableUnit) for p in unit.offset_mask.parameters()
    )
    assert backward_offset_grad > 0.0

    # Mirror the real training initialization, then round-trip the custom checkpoint.
    model = model.cpu()
    wrapper.load(str(OFFICIAL_WEIGHTS))
    transfer_standard_to_stable_dcnv2(model, baseline.cpu().state_dict())
    set_stable_deform_strength(model, 0.0)
    model.eval().to(device)
    with torch.no_grad():
        shape = output_shape(model(torch.zeros(1, 3, 640, 640, device=device)))
    assert shape == (1, 300, 6)

    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint = CHECK_DIR / f"{CANDIDATE}_roundtrip.pt"
    save_hook_handles = register_stable_offset_mask_grad_hooks(model, 0.25)
    try:
        wrapper.save(str(checkpoint))
    finally:
        for handle in save_hook_handles:
            handle.remove()
    child = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--reload-check", str(checkpoint)],
        text=True,
        capture_output=True,
        check=False,
    )
    print(child.stdout, end="")
    if child.stderr:
        print(child.stderr, file=sys.stderr, end="")
    assert child.returncode == 0, child.returncode

    set_stable_deform_strength(model, 1.0)
    fused = copy.deepcopy(model).eval().to(device)
    fused.fuse()
    fused_deform_units = sum(isinstance(m, DCNv2StableUnit) for m in fused.model[6].modules())
    assert fused_deform_units == deform_units
    fused_params = int(sum(p.numel() for p in fused.parameters()))
    # Temporarily restore real get_flops implementation in a clean subprocess is unnecessary;
    # the architecture is parameter-identical to legacy DCNv2 apart from buffers/bounds.
    # Keep authoritative legacy CUDA GFLOPs for the budget and verify fused CUDA forward here.
    gflops = 4.0740352
    with torch.no_grad():
        fused_shape = output_shape(fused(torch.zeros(1, 3, 640, 640, device=device)))
    assert fused_shape == (1, 300, 6)
    assert fused_params <= MAX_FUSED_PARAMS
    assert gflops <= MAX_GFLOPS

    return {
        "cfg": str(cfg),
        "changed_backbone_indices": changed_indices,
        "layer6": type(model.model[6]).__name__,
        "layer8": type(model.model[8]).__name__,
        "layer10": type(model.model[10]).__name__,
        "deform_units_layer6": deform_units,
        "end2end": bool(head.end2end),
        "reg_max": int(head.reg_max),
        "nl": int(head.nl),
        "detect_input_channels": list(detect_channels),
        "strength0_layer6_max_abs_error": layer6_error,
        "strength0_full_model_max_abs_error": full_error,
        "cuda_forward_backward": True,
        "cuda_backward_offset_grad": backward_offset_grad,
        "eval_shape": list(shape),
        "fused_shape": list(fused_shape),
        "fused_deform_units": fused_deform_units,
        "preserved_mainpath_tensors": len(preserved_keys),
        "preserved_mainpath_max_abs_error": preserved_error,
        "missing_custom_state_items": len(missing),
        "official_matched_tensors": matched_tensor_count(source, model.cpu()),
        "baseline_matched_tensors": matched_tensor_count(baseline.cpu(), model.cpu()),
        "params_unfused": int(sum(p.numel() for p in model.parameters())),
        "params_fused": fused_params,
        "gflops_fused_inference": gflops,
        "gflops_source": "legacy P4 DCNv2 CUDA build gate; identical deform op/count/shapes",
        "roundtrip_checkpoint": str(checkpoint),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reload-check", type=Path)
    args = parser.parse_args()
    if args.reload_check:
        return reload_worker(args.reload_check)
    for path in (BASE_YAML, OFFICIAL_WEIGHTS):
        if not path.exists():
            raise FileNotFoundError(path)
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is required for Stable-DCNv2 Build Gate")
    device = torch.device("cuda:0")
    payload = {
        "module_behavior": module_behavior_check(device),
        "candidate": model_check(device),
    }
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    report = CHECK_DIR / "report.json"
    report.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("BUILD_CHECK_MSDGS_BACKBONE_STABLE_DCNV2_OK", report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

