#!/usr/bin/env python
"""iter24 build 检查：确认 gsdown_neck_w075 / w100 两候选结构正确。

口径铁律：250e 训练前必须验证 end2end/reg_max/nl/输出形状/fused params。
VoVGSCSPW 只放宽 head 里 VoVGSCSP 的隐藏通道比，backbone/head 结构不变，
理论上 end2end/nl 应保留，但仍显式核实，并观察参数随 ratio 增长。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py
    python install_gsconv_modules.py
    python install_vovgscsp_wide.py
    python build_check_vovwide.py
"""
from __future__ import annotations

import os
from pathlib import Path

import torch
import yaml
from ultralytics import YOLO

import train_vovwide_gsdown as tv


def check_one(name: str) -> None:
    print(f"==== BUILD_CHECK {name} ====")
    doc = tv.BUILDERS[name]()
    tv.GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = tv.GEN_DIR / f"{name}.yaml"
    cfg.write_text("# generated by build_check_vovwide.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    head_mods = [(i, r[2]) for i, r in enumerate(doc["head"])]
    print(f"  head modules: {head_mods}")

    model = YOLO(str(cfg))
    m = model.model
    det = m.model[-1]
    end2end = getattr(det, "end2end", None)
    reg_max = getattr(det, "reg_max", None)
    nl = getattr(det, "nl", None)
    print(f"  end2end={end2end}  reg_max={reg_max}  nl={nl}")

    unfused = sum(p.numel() for p in m.parameters())
    try:
        m.fuse()
    except Exception as e:
        print(f"  fuse warn: {e}")
    fused = sum(p.numel() for p in m.parameters())
    print(f"  params unfused={unfused:,}  fused={fused:,}  (gsdown 对照 fused=1,935,817 / base 2,376,006)")

    m.eval()
    with torch.no_grad():
        y = m(torch.zeros(1, 3, 640, 640))
    shapes = [tuple(t.shape) for t in y] if isinstance(y, (list, tuple)) else [tuple(y.shape)]
    print(f"  forward out shapes={shapes}")

    ok = (end2end is True and reg_max == 1 and nl == 3)
    print(f"  VERDICT {'OK' if ok else 'CHECK_FAILED'} {name}")


def main() -> int:
    for name in tv.BUILDERS:
        try:
            check_one(name)
        except Exception:
            import traceback
            print(f"BUILD_CHECK_FAILED {name}")
            traceback.print_exc()
    print("BUILD_CHECK_ALL_DONE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
