#!/usr/bin/env python
"""Strict build gate for the MSDGS P4 Hybrid DCNv2 crazing-protection candidate."""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import subprocess
import sys

import torch
import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_backbone_hybrid_dcnv2_e250"
CHECK_DIR = ROOT / "runs_msdgs_backbone_hybrid_dcnv2_e250" / "build_check"
CANDIDATE = "msdgs_bb_p4_hybrid_dcnv2_r50"
DEFORM_RATIO = 0.50
OFFSET_LIMIT = 1.0
MASK_SPAN = 0.50
MAX_FUSED_PARAMS = 1_900_000
MAX_GFLOPS = 4.40


def generate_yaml() -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    layer = doc["backbone"][6]
    assert layer[0] == -1 and layer[1] == 2 and layer[2] == "C3k2", layer
    assert layer[3][0] == 512 and layer[3][1] is True, layer
    layer[2] = "C3k2HybridDCNv2"
    # YAML args after repeat insertion:
    # c2, n, c3k, e, attn, g, shortcut, deform_ratio, offset_limit, mask_span
    layer[3] = [512, True, 0.5, False, 1, True, DEFORM_RATIO, OFFSET_LIMIT, MASK_SPAN]
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GEN_DIR / f"{CANDIDATE}.yaml"
    path.write_text(
        "# generated by build_check_msdgs_backbone_hybrid_dcnv2.py\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return path


def output_tensor(output):
    if torch.is_tensor(output):
        return output
    if isinstance(output, (list, tuple)) and output and torch.is_tensor(output[0]):
        return output[0]
    raise TypeError(f"cannot extract decoded tensor from {type(output)!r}")


def output_shape(output):
    try:
        return tuple(output_tensor(output).shape)
    except TypeError:
        return None


def flatten_named_tensors(value, prefix=""):
    """Flatten nested Detect training/raw outputs deterministically."""
    if torch.is_tensor(value):
        return [(prefix or "tensor", value)]
    if isinstance(value, dict):
        out = []
        for key in sorted(value):
            out.extend(flatten_named_tensors(value[key], f"{prefix}.{key}" if prefix else str(key)))
        return out
    if isinstance(value, (list, tuple)):
        out = []
        for index, item in enumerate(value):
            out.extend(flatten_named_tensors(item, f"{prefix}[{index}]"))
        return out
    return []


def max_grad(parameters) -> float:
    return max((float(p.grad.abs().max()) if p.grad is not None else 0.0 for p in parameters), default=0.0)


def module_behavior_check() -> dict:
    from ultralytics.nn.modules.block import Bottleneck
    from ultralytics.nn.modules.yolo26_msdgs_backbone_hybrid_dcnv2 import (
        C3k2HybridDCNv2,
        HybridDCNv2Unit,
    )

    torch.manual_seed(59)
    custom = C3k2HybridDCNv2(
        256, 256, n=2, c3k=True,
        deform_ratio=DEFORM_RATIO, offset_limit=OFFSET_LIMIT, mask_span=MASK_SPAN,
    )
    assert custom.hybrid_units > 0
    units = []
    for module in custom.modules():
        if isinstance(module, Bottleneck):
            assert isinstance(module.cv2, HybridDCNv2Unit), type(module.cv2).__name__
            units.append(module.cv2)
    assert len(units) == custom.hybrid_units
    unit = units[0]
    assert unit.c_regular + unit.c_deform == unit.bn.num_features
    assert unit.c_regular == unit.c_deform, (unit.c_regular, unit.c_deform)

    unit.eval()
    x = torch.randn(2, unit.offset_mask.in_channels, 20, 20)
    with torch.no_grad():
        offset, mask = unit.sampling_tensors(x)
    init_offset_max = float(offset.abs().max())
    init_mask_dev = float((mask - 1.0).abs().max())
    assert init_offset_max == 0.0
    assert init_mask_dev == 0.0

    # Prove hard bounds independently of learned predictor magnitude.
    with torch.no_grad():
        unit.offset_mask.bias.fill_(100.0)
        offset_hi, mask_hi = unit.sampling_tensors(torch.zeros_like(x))
        unit.offset_mask.bias.fill_(-100.0)
        offset_lo, mask_lo = unit.sampling_tensors(torch.zeros_like(x))
        unit.offset_mask.bias.zero_()
    observed_offset_max = max(float(offset_hi.max()), float((-offset_lo).max()))
    observed_mask_min = float(mask_lo.min())
    observed_mask_max = float(mask_hi.max())
    assert observed_offset_max <= OFFSET_LIMIT + 1e-6
    assert observed_mask_min >= 1.0 - MASK_SPAN - 1e-6
    assert observed_mask_max <= 1.0 + MASK_SPAN + 1e-6

    custom.train()
    optimizer = torch.optim.SGD(custom.parameters(), lr=0.01)
    optimizer.zero_grad(set_to_none=True)
    custom(torch.randn(2, 256, 20, 20)).square().mean().backward()
    regular_grad = max_grad(unit.regular.parameters())
    deform_grad = max_grad(unit.deform.parameters())
    outer_grad = max_grad(custom.cv1.parameters())
    optimizer.step()
    optimizer.zero_grad(set_to_none=True)
    custom(torch.randn(2, 256, 20, 20)).square().mean().backward()
    offset_grad2 = max_grad(unit.offset_mask.parameters())
    assert regular_grad > 0.0 and deform_grad > 0.0 and outer_grad > 0.0 and offset_grad2 > 0.0

    return {
        "hybrid_units": len(units),
        "regular_channels": unit.c_regular,
        "deform_channels": unit.c_deform,
        "deform_ratio": unit.deform_ratio,
        "offset_limit": unit.offset_limit,
        "mask_span": unit.mask_span,
        "init_offset_max_abs": init_offset_max,
        "init_mask_dev_from_one": init_mask_dev,
        "observed_offset_bound": observed_offset_max,
        "observed_mask_min": observed_mask_min,
        "observed_mask_max": observed_mask_max,
        "regular_grad_step1": regular_grad,
        "deform_grad_step1": deform_grad,
        "outer_cv1_grad_step1": outer_grad,
        "offset_grad_step2": offset_grad2,
    }


def model_gflops(model):
    from ultralytics.utils.torch_utils import get_flops
    return float(get_flops(model, imgsz=640))


def reload_worker(weights: Path) -> int:
    import ultralytics.utils.torch_utils as torch_utils
    torch_utils.get_flops = lambda *a, **k: 0.0
    torch_utils.get_flops_with_torch_profiler = lambda *a, **k: 0.0
    from ultralytics import YOLO

    wrapper = YOLO(str(weights), task="detect")
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = wrapper.model.eval().to(device)
    with torch.no_grad():
        shape = output_shape(model(torch.zeros(1, 3, 640, 640, device=device)))
    payload = {
        "layer6": type(model.model[6]).__name__,
        "layer8": type(model.model[8]).__name__,
        "layer10": type(model.model[10]).__name__,
        "shape": shape,
        "device": device,
    }
    print(json.dumps(payload))
    ok = (
        payload["layer6"] == "C3k2HybridDCNv2"
        and payload["layer8"] == "C3k2"
        and payload["layer10"] == "C2PSA"
        and shape == (1, 300, 6)
    )
    return 0 if ok else 2


def model_check() -> dict:
    from ultralytics import YOLO
    from ultralytics.nn.modules.yolo26_msdgs_backbone_hybrid_dcnv2 import (
        HybridDCNv2Unit,
        transfer_standard_to_hybrid_dcnv2,
    )

    cfg = generate_yaml()
    base_doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    candidate_doc = yaml.safe_load(cfg.read_text(encoding="utf-8"))
    for key in base_doc:
        if key != "backbone":
            assert candidate_doc[key] == base_doc[key], key
    changed_indices = [
        i for i, (base_layer, candidate_layer) in enumerate(zip(base_doc["backbone"], candidate_doc["backbone"]))
        if base_layer != candidate_layer
    ]
    assert changed_indices == [6], changed_indices

    baseline_wrap = YOLO(str(BASE_YAML), task="detect").load(str(OFFICIAL_WEIGHTS))
    baseline = baseline_wrap.model
    wrapper = YOLO(str(cfg), task="detect")
    model = wrapper.model
    missing, unexpected = model.load_state_dict(baseline.state_dict(), strict=False)
    assert unexpected and all(k.startswith("model.6.") and k.endswith(".cv2.conv.weight") for k in unexpected), unexpected
    allowed_missing = (".cv2.regular.weight", ".cv2.deform.weight", ".cv2.offset_mask.weight", ".cv2.offset_mask.bias")
    assert missing and all(k.startswith("model.6.") and k.endswith(allowed_missing) for k in missing), missing
    transferred = transfer_standard_to_hybrid_dcnv2(model, baseline.state_dict())

    head = model.model[-1]
    layer6, layer8, layer10 = model.model[6], model.model[8], model.model[10]
    assert type(layer6).__name__ == "C3k2HybridDCNv2"
    assert type(layer8).__name__ == "C3k2"
    assert type(layer10).__name__ == "C2PSA"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    detect_channels = tuple(int(t[0].conv.in_channels) for t in head.cv2)
    assert detect_channels == (64, 128, 256), detect_channels
    units = [m for m in layer6.modules() if isinstance(m, HybridDCNv2Unit)]
    assert units and transferred == len(units) == layer6.hybrid_units
    assert all(u.c_regular == u.c_deform for u in units)

    # Full pretrained equivalence on GPU avoids torchvision's fragile CPU deform path.
    device = "cuda" if torch.cuda.is_available() else "cpu"
    baseline = baseline.eval().to(device)
    model = model.eval().to(device)
    x = torch.randn(1, 3, 640, 640, device=device)
    captured = {}
    hook_a = baseline.model[6].register_forward_hook(lambda _m, _i, o: captured.setdefault("base6", o.detach()))
    hook_b = model.model[6].register_forward_hook(lambda _m, _i, o: captured.setdefault("cand6", o.detach()))
    with torch.no_grad():
        base_out = baseline(x.clone())
        cand_out = model(x.clone())
    hook_a.remove()
    hook_b.remove()
    layer6_diff = (captured["base6"] - captured["cand6"]).abs()
    layer6_error = float(layer6_diff.max())
    layer6_mean_error = float(layer6_diff.mean())
    layer6_scale = float(captured["base6"].abs().max())
    layer6_relative = layer6_error / max(layer6_scale, 1e-12)

    # Decoded end2end output applies discrete top-k selection; a sub-milliscale
    # floating-point delta can change selected indices and make decoded boxes look
    # very different. Compare the Detect head's raw training outputs instead.
    base_head = baseline.model[-1]
    cand_head = model.model[-1]
    base_head_training, cand_head_training = base_head.training, cand_head.training
    base_head.training = True
    cand_head.training = True
    with torch.no_grad():
        base_raw = baseline(x.clone())
        cand_raw = model(x.clone())
    base_head.training = base_head_training
    cand_head.training = cand_head_training
    base_tensors = flatten_named_tensors(base_raw)
    cand_tensors = flatten_named_tensors(cand_raw)
    assert [n for n, _ in base_tensors] == [n for n, _ in cand_tensors]
    raw_max_error = 0.0
    raw_sum_error = 0.0
    raw_numel = 0
    raw_scale = 0.0
    for (name_a, tensor_a), (name_b, tensor_b) in zip(base_tensors, cand_tensors):
        assert name_a == name_b and tensor_a.shape == tensor_b.shape, (name_a, name_b, tensor_a.shape, tensor_b.shape)
        diff = (tensor_a - tensor_b).abs()
        raw_max_error = max(raw_max_error, float(diff.max()))
        raw_sum_error += float(diff.sum())
        raw_numel += diff.numel()
        raw_scale = max(raw_scale, float(tensor_a.abs().max()))
    raw_mean_error = raw_sum_error / max(raw_numel, 1)
    raw_relative = raw_max_error / max(raw_scale, 1e-12)
    print(
        "EQUIVALENCE_DIAGNOSTIC",
        f"layer6_max={layer6_error:.9g}", f"layer6_mean={layer6_mean_error:.9g}",
        f"layer6_scale={layer6_scale:.9g}", f"layer6_rel={layer6_relative:.9g}",
        f"raw_max={raw_max_error:.9g}", f"raw_mean={raw_mean_error:.9g}",
        f"raw_scale={raw_scale:.9g}", f"raw_rel={raw_relative:.9g}",
        f"raw_tensors={len(base_tensors)}",
        flush=True,
    )
    assert layer6_error < 1.5e-3, layer6_error
    assert layer6_mean_error < 2e-6, layer6_mean_error
    assert layer6_relative < 3e-4, layer6_relative
    assert raw_max_error < 3e-3, raw_max_error
    assert raw_mean_error < 3e-5, raw_mean_error
    assert raw_relative < 3e-4, raw_relative

    probe = torch.zeros(1, 3, 640, 640, device=device)
    with torch.no_grad():
        shape = output_shape(model(probe))
    assert shape == (1, 300, 6), shape

    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint = CHECK_DIR / f"{CANDIDATE}_roundtrip.pt"
    wrapper.model = model.to("cpu")
    wrapper.save(str(checkpoint))
    child = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--reload-check", str(checkpoint)],
        text=True, capture_output=True, check=False,
    )
    print(child.stdout, end="")
    if child.stderr:
        print(child.stderr, file=sys.stderr, end="")
    assert child.returncode == 0, child.returncode

    fuse_device = "cuda" if torch.cuda.is_available() else "cpu"
    fused = copy.deepcopy(model).eval().to(fuse_device)
    fused.fuse()
    fused_units = [m for m in fused.model[6].modules() if isinstance(m, HybridDCNv2Unit)]
    assert len(fused_units) == len(units)
    fused_params = int(sum(p.numel() for p in fused.parameters()))
    gflops = model_gflops(fused)
    with torch.no_grad():
        fused_shape = output_shape(fused(torch.zeros(1, 3, 640, 640, device=fuse_device)))
    assert fused_shape == (1, 300, 6), fused_shape
    assert fused_params <= MAX_FUSED_PARAMS, fused_params
    assert gflops <= MAX_GFLOPS, gflops

    return {
        "cfg": str(cfg),
        "changed_backbone_indices": changed_indices,
        "layer6": type(layer6).__name__,
        "layer8": type(layer8).__name__,
        "layer10": type(layer10).__name__,
        "hybrid_units_layer6": len(units),
        "regular_channels_per_unit": [u.c_regular for u in units],
        "deform_channels_per_unit": [u.c_deform for u in units],
        "deform_ratio": DEFORM_RATIO,
        "offset_limit": OFFSET_LIMIT,
        "mask_span": MASK_SPAN,
        "end2end": bool(head.end2end),
        "reg_max": int(head.reg_max),
        "nl": int(head.nl),
        "detect_input_channels": list(detect_channels),
        "eval_shape": list(shape),
        "fused_shape": list(fused_shape),
        "equivalence_device": device,
        "layer6_equivalence_max_abs_error": layer6_error,
        "layer6_equivalence_mean_abs_error": layer6_mean_error,
        "layer6_equivalence_relative_error": layer6_relative,
        "raw_head_equivalence_max_abs_error": raw_max_error,
        "raw_head_equivalence_mean_abs_error": raw_mean_error,
        "raw_head_equivalence_relative_error": raw_relative,
        "missing_hybrid_state_items": len(missing),
        "transferred_units": transferred,
        "params_unfused": int(sum(p.numel() for p in model.parameters())),
        "params_fused": fused_params,
        "gflops_fused_inference": gflops,
        "roundtrip_checkpoint": str(checkpoint),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reload-check", type=Path)
    args = parser.parse_args()
    if args.reload_check:
        return reload_worker(args.reload_check)
    for path in (BASE_YAML, OFFICIAL_WEIGHTS):
        if not path.exists():
            raise FileNotFoundError(path)
    payload = {"module_behavior": module_behavior_check(), "candidate": model_check()}
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    report = CHECK_DIR / "report.json"
    report.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("BUILD_CHECK_MSDGS_BACKBONE_HYBRID_DCNV2_OK", report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


