#!/usr/bin/env python
"""MSDGSDetect 四候选的构建、前向、融合、重载和梯度隔离检查。"""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import subprocess
import sys

import torch
import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
GEN_DIR = ROOT / "generated_models_msdgs_detect_e250"
CHECK_DIR = ROOT / "runs_msdgs_detect_e250" / "build_check"

SPECS = {
    "msdgs_p4p5_gate": [16, True, 0.1, False],
    "msdgs_p5box32": [32, False, 0.1, False],
    "msdgs_p4p5_gate_p5box32": [32, True, 0.1, False],
    "msdgs_p5cafm_gate": [16, False, 0.1, True],
}
EXPECTED_FUSED = {
    "msdgs_p4p5_gate": 1_811_623,
    "msdgs_p5box32": 1_821_190,
    "msdgs_p4p5_gate_p5box32": 1_855_495,
}
EXPECTED_GFLOPS = {
    "msdgs_p4p5_gate": 4.7067,
    "msdgs_p5box32": 4.7203,
    "msdgs_p4p5_gate_p5box32": 4.7770,
}


def generate_yaml(name: str) -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    last = doc["head"][-1]
    assert last[0] == [16, 19, 22] and last[2] == "Detect", last
    last[2] = "MSDGSDetect"
    last[3] = ["nc", *SPECS[name]]
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GEN_DIR / f"{name}.yaml"
    path.write_text(
        "# generated by build_check_msdgs_detect.py\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return path


def output_shape(output) -> tuple[int, ...] | None:
    if torch.is_tensor(output):
        return tuple(output.shape)
    if isinstance(output, (list, tuple)) and output and torch.is_tensor(output[0]):
        return tuple(output[0].shape)
    return None


def tensor_max_abs(a, b) -> float:
    values: list[float] = []
    if torch.is_tensor(a) and torch.is_tensor(b):
        values.append(float((a - b).abs().max()))
    elif isinstance(a, dict) and isinstance(b, dict):
        assert a.keys() == b.keys()
        values.extend(tensor_max_abs(a[k], b[k]) for k in a)
    elif isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        assert len(a) == len(b)
        values.extend(tensor_max_abs(x, y) for x, y in zip(a, b))
    else:
        assert type(a) is type(b), (type(a), type(b))
    return max(values, default=0.0)


def equivalence_check() -> float:
    from ultralytics.nn.modules.head import Detect
    from ultralytics.nn.modules.yolo26_msdgs_detect import MSDGSDetect

    Detect.legacy = False
    MSDGSDetect.legacy = False
    torch.manual_seed(7)
    standard = Detect(nc=6, reg_max=1, end2end=True, ch=(64, 128, 256))
    custom = MSDGSDetect(
        nc=6, p5_box_width=16, use_p4p5_fusion=True, gate_scale=0.1,
        use_p5_cafm=False, reg_max=1, end2end=True, ch=(64, 128, 256),
    )
    missing, unexpected = custom.load_state_dict(standard.state_dict(), strict=False)
    assert not unexpected
    assert set(missing) == {
        "alpha", "p4_to_p5.0.conv.weight", "p4_to_p5.0.bn.weight", "p4_to_p5.0.bn.bias",
        "p4_to_p5.0.bn.running_mean", "p4_to_p5.0.bn.running_var", "p4_to_p5.1.conv.weight",
        "p4_to_p5.1.bn.weight", "p4_to_p5.1.bn.bias", "p4_to_p5.1.bn.running_mean",
        "p4_to_p5.1.bn.running_var",
    }, missing
    standard.stride[:] = torch.tensor([8.0, 16.0, 32.0])
    custom.stride[:] = standard.stride
    standard.eval()
    custom.eval()
    x = [
        torch.randn(1, 64, 80, 80),
        torch.randn(1, 128, 40, 40),
        torch.randn(1, 256, 20, 20),
    ]
    with torch.no_grad():
        a = standard([t.clone() for t in x])
        b = custom([t.clone() for t in x])
    return tensor_max_abs(a, b)


def _fresh_features() -> list[torch.Tensor]:
    return [
        torch.randn(1, 64, 20, 20, requires_grad=True),
        torch.randn(1, 128, 10, 10, requires_grad=True),
        torch.randn(1, 256, 5, 5, requires_grad=True),
    ]


def _max_parameter_grad(parameters) -> float:
    return max((float(p.grad.abs().max()) if p.grad is not None else 0.0) for p in parameters)


def detach_gradient_check() -> dict:
    from ultralytics.nn.modules.yolo26_msdgs_detect import MSDGSDetect

    MSDGSDetect.legacy = False
    head = MSDGSDetect(
        nc=6, p5_box_width=16, use_p4p5_fusion=True, gate_scale=0.1,
        use_p5_cafm=False, reg_max=1, end2end=True, ch=(64, 128, 256),
    )
    head.train()
    # 非零 gate 是关键：否则 alpha=0 本身就会让融合支路梯度为零，无法证明 detach 契约。
    with torch.no_grad():
        head.alpha.fill_(0.5)
    fusion_parameters = [head.alpha, *head.p4_to_p5.parameters()]

    one2one_features = _fresh_features()
    one2one = head(one2one_features)["one2one"]
    (one2one["boxes"].sum() + one2one["scores"].sum()).backward()
    one2one_input_grad_max = max(
        (float(t.grad.abs().max()) if t.grad is not None else 0.0) for t in one2one_features
    )
    one2one_fusion_grad_max = _max_parameter_grad(fusion_parameters)
    one2one_head_grad_max = _max_parameter_grad(head.one2one_cv2.parameters())

    head.zero_grad(set_to_none=True)
    one2many_features = _fresh_features()
    one2many = head(one2many_features)["one2many"]
    (one2many["boxes"].sum() + one2many["scores"].sum()).backward()
    one2many_input_grad_max = max(
        (float(t.grad.abs().max()) if t.grad is not None else 0.0) for t in one2many_features
    )
    one2many_fusion_grad_max = _max_parameter_grad(fusion_parameters)

    return {
        "gate_alpha_for_check": float(head.alpha.detach()),
        "one2one_input_grad_max": one2one_input_grad_max,
        "one2one_fusion_grad_max": one2one_fusion_grad_max,
        "one2one_head_grad_max": one2one_head_grad_max,
        "one2many_input_grad_max": one2many_input_grad_max,
        "one2many_fusion_grad_max": one2many_fusion_grad_max,
    }


def cafm_batch_isolation_check() -> float:
    """同一样本单独/拼 batch 时输出应一致，防止门控 reshape 混入其他样本。"""
    from ultralytics.nn.modules.yolo26_msdgs_detect import MSDGSDetect

    MSDGSDetect.legacy = False
    head = MSDGSDetect(
        nc=6, p5_box_width=16, use_p4p5_fusion=False, gate_scale=0.1,
        use_p5_cafm=True, reg_max=1, end2end=True, ch=(64, 128, 256),
    ).eval()
    sample = torch.randn(1, 256, 5, 5)
    other = torch.randn(1, 256, 5, 5)
    with torch.no_grad():
        alone = head.p5_cafm(sample)
        batched = head.p5_cafm(torch.cat((sample, other), dim=0))[:1]
    return float((alone - batched).abs().max())


def model_gflops(model) -> float | None:
    try:
        from ultralytics.utils.torch_utils import get_flops

        return float(get_flops(model, imgsz=640))
    except Exception as exc:  # noqa: BLE001
        print("WARN_GFLOPS", repr(exc))
    return None


def reload_worker(weights: Path) -> int:
    from ultralytics import YOLO

    model = YOLO(str(weights), task="detect")
    model.model.eval()
    with torch.no_grad():
        output = model.model(torch.zeros(1, 3, 640, 640))
    shape = output_shape(output)
    print(json.dumps({"weights": str(weights), "shape": shape, "head": type(model.model.model[-1]).__name__}))
    return 0 if shape == (1, 300, 6) else 2


def check_candidate(name: str) -> dict:
    from ultralytics import YOLO

    cfg = generate_yaml(name)
    wrapper = YOLO(str(cfg), task="detect")
    model = wrapper.model
    head = model.model[-1]
    assert type(head).__name__ == "MSDGSDetect"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    assert tuple(head.input_channels) == (64, 128, 256)

    model.eval()
    with torch.no_grad():
        output = model(torch.zeros(1, 3, 640, 640))
    shape = output_shape(output)
    assert shape == (1, 300, 6), shape

    box_widths = [int(tower[0].conv.out_channels) for tower in head.cv2]
    o2o_widths = [int(tower[0].conv.out_channels) for tower in head.one2one_cv2]
    expected_widths = [16, 16, SPECS[name][0]]
    assert box_widths == expected_widths, (box_widths, expected_widths)
    assert o2o_widths == expected_widths, (o2o_widths, expected_widths)

    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint = CHECK_DIR / f"{name}_roundtrip.pt"
    wrapper.save(str(checkpoint))
    child = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--reload-check", str(checkpoint)],
        text=True, capture_output=True, check=False,
    )
    print(child.stdout, end="")
    if child.stderr:
        print(child.stderr, file=sys.stderr, end="")
    assert child.returncode == 0, f"reload failed rc={child.returncode}"

    gflops_eval_graph = model_gflops(model)
    fused = copy.deepcopy(model).eval()
    fused.fuse()
    fused_params = int(sum(p.numel() for p in fused.parameters()))
    gflops_fused_inference = model_gflops(fused)
    with torch.no_grad():
        fused_shape = output_shape(fused(torch.zeros(1, 3, 640, 640)))
    assert fused_shape == (1, 300, 6), fused_shape

    if name in EXPECTED_FUSED:
        assert fused_params == EXPECTED_FUSED[name], (name, fused_params, EXPECTED_FUSED[name])
    return {
        "cfg": str(cfg),
        "head": type(head).__name__,
        "end2end": bool(head.end2end),
        "reg_max": int(head.reg_max),
        "nl": int(head.nl),
        "input_channels": list(head.input_channels),
        "box_widths": box_widths,
        "eval_shape": list(shape),
        "fused_shape": list(fused_shape),
        "fused_params": fused_params,
        "expected_fused_params": EXPECTED_FUSED.get(name),
        "gflops": gflops_eval_graph,
        "gflops_fused_inference": gflops_fused_inference,
        "expected_gflops": EXPECTED_GFLOPS.get(name),
        "gflops_note": (
            "P4->P5 feature is computed once then shared by one2many/one2one; plan estimate counted it twice"
            if SPECS[name][1] else None
        ),
        "roundtrip_checkpoint": str(checkpoint),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reload-check", type=Path)
    args = parser.parse_args()
    if args.reload_check:
        return reload_worker(args.reload_check)

    if not BASE_YAML.exists():
        raise FileNotFoundError(BASE_YAML)
    equivalence_error = equivalence_check()
    assert equivalence_error < 1e-6, equivalence_error
    gradients = detach_gradient_check()
    assert gradients["one2one_input_grad_max"] == 0.0, gradients
    assert gradients["one2one_fusion_grad_max"] == 0.0, gradients
    assert gradients["one2one_head_grad_max"] > 0.0, gradients
    assert gradients["one2many_input_grad_max"] > 0.0, gradients
    assert gradients["one2many_fusion_grad_max"] > 0.0, gradients
    cafm_batch_error = cafm_batch_isolation_check()
    assert cafm_batch_error < 1e-6, cafm_batch_error

    results = {name: check_candidate(name) for name in SPECS}
    payload = {
        "equivalence_max_abs_error": equivalence_error,
        "one2one_detach_gradient_check": gradients,
        "cafm_batch_isolation_max_abs_error": cafm_batch_error,
        "candidates": results,
    }
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    report = CHECK_DIR / "report.json"
    report.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("BUILD_CHECK_MSDGS_DETECT_OK", report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())