#!/usr/bin/env python
"""Strict build gate for the MSDGS P4 directional-residual candidate."""
from __future__ import annotations

import argparse
import copy
import itertools
import json
import os
from pathlib import Path
import subprocess
import sys

import torch
import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_backbone_dirres_e250"
CHECK_DIR = ROOT / "runs_msdgs_backbone_dirres_e250" / "build_check"
CANDIDATE = "msdgs_bb_p4_dirres"
SPEC = {"branch_channels": 32, "direction_kernel": 5, "residual_scale": 0.1}


def generate_yaml() -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    layer = doc["backbone"][6]
    assert layer[0] == -1 and layer[1] == 2 and layer[2] == "C3k2", layer
    assert layer[3][0] == 512 and layer[3][1] is True, layer
    layer[2] = "C3k2DirectionalResidual"
    layer[3] = [512, True, SPEC["branch_channels"], SPEC["direction_kernel"], SPEC["residual_scale"]]
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GEN_DIR / f"{CANDIDATE}.yaml"
    path.write_text(
        "# generated by build_check_msdgs_backbone_dirres.py\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return path


def output_tensor(output):
    if torch.is_tensor(output):
        return output
    if isinstance(output, (list, tuple)) and output and torch.is_tensor(output[0]):
        return output[0]
    raise TypeError(f"cannot extract decoded tensor from {type(output)!r}")


def output_shape(output):
    try:
        return tuple(output_tensor(output).shape)
    except TypeError:
        return None


def tensor_max_abs(a, b) -> float:
    values = []
    if torch.is_tensor(a) and torch.is_tensor(b):
        values.append(float((a - b).abs().max()))
    elif isinstance(a, dict) and isinstance(b, dict):
        assert a.keys() == b.keys(), (a.keys(), b.keys())
        values.extend(tensor_max_abs(a[k], b[k]) for k in a)
    elif isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        assert len(a) == len(b)
        values.extend(tensor_max_abs(x, y) for x, y in zip(a, b))
    else:
        assert type(a) is type(b), (type(a), type(b))
    return max(values, default=0.0)


def max_grad(parameters) -> float:
    return max(
        (float(p.grad.abs().max()) if p.grad is not None else 0.0 for p in parameters),
        default=0.0,
    )


def module_behavior_check() -> dict:
    from ultralytics.nn.modules.block import C3k2
    from ultralytics.nn.modules.yolo26_msdgs_backbone_dirres import C3k2DirectionalResidual

    torch.manual_seed(55)
    standard = C3k2(128, 128, n=1, c3k=True)
    custom = C3k2DirectionalResidual(128, 128, n=1, c3k=True, **SPEC)
    missing, unexpected = custom.load_state_dict(standard.state_dict(), strict=False)
    assert not unexpected, unexpected
    residual_prefixes = (
        "dir_reduce.", "dir_h.", "dir_v.", "dir_local.", "dir_gate.", "dir_project."
    )
    assert missing and all(k.startswith(residual_prefixes) for k in missing), missing
    assert torch.count_nonzero(custom.dir_gate.weight) == 0
    assert torch.count_nonzero(custom.dir_gate.bias) == 0
    assert torch.count_nonzero(custom.dir_project.weight) == 0
    assert torch.count_nonzero(custom.dir_project.bias) == 0

    standard.eval()
    custom.eval()
    x = torch.randn(2, 128, 40, 40)
    with torch.no_grad():
        module_error = float((standard(x) - custom(x)).abs().max())
        gate = torch.softmax(custom.dir_gate(custom.dir_reduce(standard(x))), dim=1)
        gate_uniform_error = float((gate - (1.0 / 3.0)).abs().max())
    assert module_error < 1e-6, module_error
    assert gate_uniform_error < 1e-7, gate_uniform_error

    custom.train()
    optimizer = torch.optim.SGD(custom.parameters(), lr=0.01)
    optimizer.zero_grad(set_to_none=True)
    custom(torch.randn(2, 128, 40, 40)).square().mean().backward()
    project_grad_step1 = max_grad(custom.dir_project.parameters())
    reduce_grad_step1 = max_grad(custom.dir_reduce.parameters())
    directional_grad_step1 = max_grad(
        itertools.chain(custom.dir_h.parameters(), custom.dir_v.parameters(), custom.dir_local.parameters())
    )
    gate_grad_step1 = max_grad(custom.dir_gate.parameters())
    main_grad_step1 = max_grad(custom.cv1.parameters())
    assert project_grad_step1 > 0.0 and main_grad_step1 > 0.0
    assert reduce_grad_step1 == 0.0
    assert directional_grad_step1 == 0.0
    assert gate_grad_step1 == 0.0
    optimizer.step()
    assert torch.count_nonzero(custom.dir_project.weight) > 0

    optimizer.zero_grad(set_to_none=True)
    custom(torch.randn(2, 128, 40, 40)).square().mean().backward()
    project_grad_step2 = max_grad(custom.dir_project.parameters())
    reduce_grad_step2 = max_grad(custom.dir_reduce.parameters())
    directional_grad_step2 = max_grad(
        itertools.chain(custom.dir_h.parameters(), custom.dir_v.parameters(), custom.dir_local.parameters())
    )
    gate_grad_step2 = max_grad(custom.dir_gate.parameters())
    main_grad_step2 = max_grad(custom.cv1.parameters())
    assert project_grad_step2 > 0.0
    assert reduce_grad_step2 > 0.0
    assert directional_grad_step2 > 0.0
    assert gate_grad_step2 > 0.0
    assert main_grad_step2 > 0.0

    return {
        "module_equivalence_max_abs_error": module_error,
        "uniform_gate_max_abs_error": gate_uniform_error,
        "missing_residual_state_items": len(missing),
        "project_grad_step1": project_grad_step1,
        "reduce_grad_step1": reduce_grad_step1,
        "directional_grad_step1": directional_grad_step1,
        "gate_grad_step1": gate_grad_step1,
        "main_grad_step1": main_grad_step1,
        "project_grad_step2": project_grad_step2,
        "reduce_grad_step2": reduce_grad_step2,
        "directional_grad_step2": directional_grad_step2,
        "gate_grad_step2": gate_grad_step2,
        "main_grad_step2": main_grad_step2,
    }


def model_gflops(model):
    from ultralytics.utils.torch_utils import get_flops

    return float(get_flops(model, imgsz=640))


def matched_tensor_count(source, target) -> int:
    source_state, target_state = source.state_dict(), target.state_dict()
    return sum(k in target_state and target_state[k].shape == v.shape for k, v in source_state.items())


def reload_worker(weights: Path) -> int:
    from ultralytics import YOLO

    wrapper = YOLO(str(weights), task="detect")
    model = wrapper.model.eval()
    with torch.no_grad():
        shape = output_shape(model(torch.zeros(1, 3, 640, 640)))
    payload = {
        "layer6": type(model.model[6]).__name__,
        "layer8": type(model.model[8]).__name__,
        "layer10": type(model.model[10]).__name__,
        "shape": shape,
    }
    print(json.dumps(payload))
    ok = (
        payload["layer6"] == "C3k2DirectionalResidual"
        and payload["layer8"] == "C3k2"
        and payload["layer10"] == "C2PSA"
        and shape == (1, 300, 6)
    )
    return 0 if ok else 2


def model_check() -> dict:
    from ultralytics import YOLO

    cfg = generate_yaml()
    base_doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    candidate_doc = yaml.safe_load(cfg.read_text(encoding="utf-8"))
    for key in base_doc:
        if key != "backbone":
            assert candidate_doc[key] == base_doc[key], key
    assert len(candidate_doc["backbone"]) == len(base_doc["backbone"])
    changed_indices = [
        i
        for i, (base_layer, candidate_layer) in enumerate(zip(base_doc["backbone"], candidate_doc["backbone"]))
        if base_layer != candidate_layer
    ]
    assert changed_indices == [6], changed_indices

    source = YOLO(str(OFFICIAL_WEIGHTS), task="detect").model
    baseline = YOLO(str(BASE_YAML), task="detect").model
    wrapper = YOLO(str(cfg), task="detect")
    model = wrapper.model
    head = model.model[-1]
    layer6, layer8, layer10 = model.model[6], model.model[8], model.model[10]
    assert type(layer6).__name__ == "C3k2DirectionalResidual"
    assert type(layer8).__name__ == "C3k2"
    assert type(layer10).__name__ == "C2PSA"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    detect_channels = tuple(int(t[0].conv.in_channels) for t in head.cv2)
    assert detect_channels == (64, 128, 256), detect_channels

    missing, unexpected = model.load_state_dict(baseline.state_dict(), strict=False)
    assert not unexpected, unexpected
    residual_names = (
        "dir_reduce.", "dir_h.", "dir_v.", "dir_local.", "dir_gate.", "dir_project."
    )
    assert missing and all(
        "model.6." in k and any(name in k for name in residual_names) for k in missing
    ), missing

    base_state, candidate_state = baseline.state_dict(), model.state_dict()
    main_keys = [
        k for k in base_state
        if k.startswith("model.6.")
        and any(k.startswith(f"model.6.{name}.") for name in ("cv1", "cv2", "m"))
    ]
    assert main_keys
    assert all(k in candidate_state and candidate_state[k].shape == base_state[k].shape for k in main_keys)
    main_state_error = max(float((base_state[k] - candidate_state[k]).abs().max()) for k in main_keys)
    assert main_state_error == 0.0

    baseline.eval()
    model.eval()
    x = torch.randn(1, 3, 640, 640)
    captured = {}
    hook_a = baseline.model[6].register_forward_hook(
        lambda _m, _i, o: captured.setdefault("base6", o.detach())
    )
    hook_b = model.model[6].register_forward_hook(
        lambda _m, _i, o: captured.setdefault("candidate6", o.detach())
    )
    with torch.no_grad():
        baseline_output = baseline(x.clone())
        candidate_output = model(x.clone())
    hook_a.remove()
    hook_b.remove()
    layer6_error = float((captured["base6"] - captured["candidate6"]).abs().max())
    full_error = tensor_max_abs(baseline_output, candidate_output)
    assert layer6_error < 1e-6 and full_error < 1e-6, (layer6_error, full_error)

    base_match = matched_tensor_count(source, baseline)
    candidate_match = matched_tensor_count(source, model)
    assert candidate_match == base_match, (candidate_match, base_match)
    wrapper.load(str(OFFICIAL_WEIGHTS))
    model.eval()
    probe = torch.zeros(1, 3, 640, 640)
    fuse_capture = {}
    pre_fuse_hook = model.model[6].register_forward_hook(
        lambda _m, _i, o: fuse_capture.setdefault("unfused_layer6", o.detach())
    )
    with torch.no_grad():
        shape = output_shape(model(probe))
    pre_fuse_hook.remove()
    assert shape == (1, 300, 6), shape

    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint = CHECK_DIR / f"{CANDIDATE}_roundtrip.pt"
    wrapper.save(str(checkpoint))
    child = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--reload-check", str(checkpoint)],
        text=True, capture_output=True, check=False,
    )
    print(child.stdout, end="")
    if child.stderr:
        print(child.stderr, file=sys.stderr, end="")
    assert child.returncode == 0, child.returncode

    fused = copy.deepcopy(model).eval()
    fused.fuse()
    fused_params = int(sum(p.numel() for p in fused.parameters()))
    gflops = model_gflops(fused)
    fused_hook = fused.model[6].register_forward_hook(
        lambda _m, _i, o: fuse_capture.setdefault("fused_layer6", o.detach())
    )
    with torch.no_grad():
        fused_output = fused(probe)
    fused_hook.remove()
    fused_shape = output_shape(fused_output)
    fuse_error = float((fuse_capture["unfused_layer6"] - fuse_capture["fused_layer6"]).abs().max())
    assert fused_shape == (1, 300, 6), fused_shape
    assert fuse_error < 1e-3, fuse_error
    assert fused_params <= 1_860_000, fused_params
    assert gflops <= 4.30, gflops

    return {
        "cfg": str(cfg),
        "changed_backbone_indices": changed_indices,
        "layer6": type(layer6).__name__,
        "layer8": type(layer8).__name__,
        "layer10": type(layer10).__name__,
        "end2end": bool(head.end2end),
        "reg_max": int(head.reg_max),
        "nl": int(head.nl),
        "detect_input_channels": list(detect_channels),
        "eval_shape": list(shape),
        "fused_shape": list(fused_shape),
        "layer6_equivalence_max_abs_error": layer6_error,
        "model_equivalence_max_abs_error": full_error,
        "fuse_max_abs_error": fuse_error,
        "main_path_state_items": len(main_keys),
        "main_path_state_max_abs_error": main_state_error,
        "missing_residual_state_items": len(missing),
        "official_matched_tensors": candidate_match,
        "baseline_matched_tensors": base_match,
        "params_unfused": int(sum(p.numel() for p in model.parameters())),
        "params_fused": fused_params,
        "gflops_fused_inference": gflops,
        "roundtrip_checkpoint": str(checkpoint),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reload-check", type=Path)
    args = parser.parse_args()
    if args.reload_check:
        return reload_worker(args.reload_check)
    for path in (BASE_YAML, OFFICIAL_WEIGHTS):
        if not path.exists():
            raise FileNotFoundError(path)
    payload = {"module_behavior": module_behavior_check(), "candidate": model_check()}
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    report = CHECK_DIR / "report.json"
    report.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("BUILD_CHECK_MSDGS_BACKBONE_DIRRES_OK", report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
