#!/usr/bin/env python
"""Generate the single-variable MSDGS Backbone P3 C3k candidate YAML."""
from __future__ import annotations

import copy
import json
import os
from pathlib import Path

import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
GEN_DIR = ROOT / "generated_models_msdgs_backbone_p3_c3k_e250"
CANDIDATE = "msdgs_bb_p3_c3k"
CANDIDATE_YAML = GEN_DIR / f"{CANDIDATE}.yaml"
TARGET_INDEX = 4
EXPECTED_BASE_LAYER = [-1, 2, "C3k2", [512, False, 0.25]]
EXPECTED_CANDIDATE_LAYER = [-1, 2, "C3k2", [512, True, 0.25]]


def changed_backbone_indices(base_doc: dict, candidate_doc: dict) -> list[int]:
    """Return Backbone indices whose serialized layer definitions changed."""
    assert len(base_doc["backbone"]) == len(candidate_doc["backbone"])
    return [
        index
        for index, (base_layer, candidate_layer) in enumerate(
            zip(base_doc["backbone"], candidate_doc["backbone"])
        )
        if base_layer != candidate_layer
    ]


def validate_documents(base_doc: dict, candidate_doc: dict) -> list[int]:
    """Enforce that index 4's c3k flag is the only configuration change."""
    assert base_doc["backbone"][TARGET_INDEX] == EXPECTED_BASE_LAYER, base_doc["backbone"][TARGET_INDEX]
    assert candidate_doc["backbone"][TARGET_INDEX] == EXPECTED_CANDIDATE_LAYER, candidate_doc["backbone"][TARGET_INDEX]
    assert base_doc.keys() == candidate_doc.keys()
    for key in base_doc:
        if key != "backbone":
            assert candidate_doc[key] == base_doc[key], key
    changed = changed_backbone_indices(base_doc, candidate_doc)
    assert changed == [TARGET_INDEX], changed
    return changed


def generate_candidate_yaml() -> tuple[Path, dict]:
    """Deep-copy the authoritative MSDGS YAML and flip only Backbone[4].args[1]."""
    if not BASE_YAML.exists():
        raise FileNotFoundError(BASE_YAML)
    base_doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    assert base_doc["backbone"][TARGET_INDEX] == EXPECTED_BASE_LAYER, base_doc["backbone"][TARGET_INDEX]
    candidate_doc = copy.deepcopy(base_doc)
    candidate_doc["backbone"][TARGET_INDEX][3][1] = True
    changed = validate_documents(base_doc, candidate_doc)

    GEN_DIR.mkdir(parents=True, exist_ok=True)
    CANDIDATE_YAML.write_text(
        "# generated by generate_msdgs_backbone_p3_c3k.py\n"
        + yaml.safe_dump(candidate_doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    roundtrip_doc = yaml.safe_load(CANDIDATE_YAML.read_text(encoding="utf-8"))
    validate_documents(base_doc, roundtrip_doc)
    payload = {
        "base_yaml": str(BASE_YAML),
        "candidate": CANDIDATE,
        "candidate_yaml": str(CANDIDATE_YAML),
        "changed_backbone_indices": changed,
        "base_layer4": base_doc["backbone"][TARGET_INDEX],
        "candidate_layer4": roundtrip_doc["backbone"][TARGET_INDEX],
    }
    return CANDIDATE_YAML, payload


def main() -> int:
    path, payload = generate_candidate_yaml()
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("GENERATE_MSDGS_BACKBONE_P3_C3K_OK", path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())