#!/usr/bin/env python
"""串行执行 MSDGSDetect 消融、独立评测、条件晋级和多 seed 汇总。

默认协议：250 epochs / 640 / batch 32 / cache=False / seed0 / yolo26n.pt / NEU-DET。
训练 worker 与评测 worker 始终是两个独立 Python 进程；中断候选默认 fresh train，不 resume last.pt。
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import statistics
import subprocess
import sys
import time
from typing import Any

import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_detect_e250"
PROJECT = ROOT / "runs_msdgs_detect_e250"
REPORT_JSON = PROJECT / "report.json"
REPORT_MD = PROJECT / "report.md"
STATUS_JSON = PROJECT / "status.json"
LOCK_FILE = PROJECT / ".orchestrator.lock"
SCRIPT = Path(__file__).resolve()

NAMES = ["crazing", "inclusion", "patches", "pitted_surface", "rolled-in_scale", "scratches"]
SPECS = {
    "msdgs_p4p5_gate": [16, True, 0.1, False],
    "msdgs_p5box32": [32, False, 0.1, False],
    "msdgs_p4p5_gate_p5box32": [32, True, 0.1, False],
    "msdgs_p5cafm_gate": [16, False, 0.1, True],
}
A_NAME = "msdgs_p4p5_gate"
B_NAME = "msdgs_p5box32"
AB_NAME = "msdgs_p4p5_gate_p5box32"
CAFM_NAME = "msdgs_p5cafm_gate"

MSDGS_SEED0 = {
    "map50": 0.7324113100352823,
    "map50_95": 0.3988372172746915,
    "per_class": {
        "crazing": {"map50_95": 0.1770695825201802},
        "pitted_surface": {"map50_95": 0.4686952771905249},
        "rolled-in_scale": {"map50_95": 0.2584298478269593},
    },
}
MSDGS_SEED_MAP = {
    0: 0.3988372172746915,
    1: 0.3889045132193333,
    2: 0.3945805719874045,
    3: 0.3901283944375075,
}
MSDGS_MEAN = 0.39311336991106133
GSDOWN_MEAN = 0.3935348421721897
SEED0_MAP_GATE = 0.401794
SEED0_MAP50_FLOOR = 0.722411
IDEAL_MAP = 0.404


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def atomic_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    temp.replace(path)


def save_status(status: str, current: str | None, pending: list[str], note: str = "") -> None:
    atomic_json(STATUS_JSON, {
        "status": status,
        "current": current,
        "pending": pending,
        "note": note,
        "updated_at": now(),
        "report_json": str(REPORT_JSON),
        "report_md": str(REPORT_MD),
    })


def load_report() -> dict:
    base = {
        "schema_version": 2,
        "protocol": {
            "epochs": 250, "imgsz": 640, "batch": 32, "cache": False,
            "init_weights": str(OFFICIAL_WEIGHTS), "data": str(DATA),
            "final_eval": "fresh subprocess reloads best.pt for val and test",
        },
        "baseline": {
            "msdgs135eq_seed0": MSDGS_SEED0,
            "msdgs135eq_four_seed_mean": MSDGS_MEAN,
            "gsdown_four_seed_mean": GSDOWN_MEAN,
        },
        "experiments": {},
        "decisions": {},
        "summaries": {},
    }
    if not REPORT_JSON.exists():
        return base
    try:
        existing = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
        for key, value in base.items():
            existing.setdefault(key, value)
        return existing
    except Exception:  # noqa: BLE001
        backup = REPORT_JSON.with_name(f"report.polluted_{time.strftime('%Y%m%d_%H%M%S')}.json")
        shutil.copy2(REPORT_JSON, backup)
        base["decisions"]["pollution_backup"] = str(backup)
        return base


def generate_configs() -> dict[str, Path]:
    base = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    result = {}
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    for name, spec in SPECS.items():
        doc = json.loads(json.dumps(base))
        last = doc["head"][-1]
        assert last[0] == [16, 19, 22] and last[2] == "Detect", last
        last[2] = "MSDGSDetect"
        last[3] = ["nc", *spec]
        path = GEN_DIR / f"{name}.yaml"
        path.write_text(
            "# generated by train_msdgs_detect_ablation.py\n"
            + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
        result[name] = path
    return result


def run_name(candidate: str, seed: int) -> str:
    return f"{candidate}_seed{seed}"


def metric_dict(metrics) -> dict:
    infer = float(metrics.speed.get("inference", 0.0) or 0.0)
    result = {
        "map50": float(metrics.box.map50),
        "map50_95": float(metrics.box.map),
        "precision": float(metrics.box.mp),
        "recall": float(metrics.box.mr),
        "infer_ms": infer,
        "fps_infer_only": 1000.0 / infer if infer else None,
        "per_class": {},
    }
    for i, cls_index in enumerate(metrics.ap_class_index):
        cls = int(cls_index)
        name = NAMES[cls] if cls < len(NAMES) else str(cls)
        result["per_class"][name] = {
            "map50": float(metrics.box.ap50[i]),
            "map50_95": float(metrics.box.ap[i]),
            "precision": float(metrics.box.p[i]),
            "recall": float(metrics.box.r[i]),
        }
    return result


def model_gflops(model) -> float | None:
    try:
        from ultralytics.utils.torch_utils import get_flops
        return float(get_flops(model, imgsz=640))
    except Exception as exc:  # noqa: BLE001
        print("WARN_GFLOPS", repr(exc))
    return None


def train_worker(args) -> int:
    from ultralytics import YOLO

    cfg = Path(args.cfg)
    target = PROJECT / args.run_name
    if target.exists():
        archived = target.with_name(target.name + f"_interrupted_{time.strftime('%Y%m%d_%H%M%S')}")
        target.rename(archived)
        print("ARCHIVED_EXISTING_RUN", target, "->", archived, flush=True)

    print("TRAIN_WORKER_START", args.run_name, "seed", args.seed, "cfg", cfg, flush=True)
    model = YOLO(str(cfg), task="detect").load(str(OFFICIAL_WEIGHTS))
    params_unfused = int(sum(p.numel() for p in model.model.parameters()))
    model.train(
        data=str(DATA), epochs=args.epochs, imgsz=args.imgsz, batch=args.batch,
        workers=8, seed=args.seed, device=0, project=str(PROJECT), name=args.run_name,
        exist_ok=True, patience=max(args.epochs, 250), cache=False, verbose=True,
    )
    weights = target / "weights" / "best.pt"
    if not weights.exists():
        raise FileNotFoundError(weights)
    marker = target / "train_worker.json"
    atomic_json(marker, {
        "status": "done", "run_name": args.run_name, "candidate": args.candidate,
        "seed": args.seed, "cfg": str(cfg), "weights": str(weights),
        "params_unfused": params_unfused, "finished_at": now(),
    })
    print("TRAIN_WORKER_DONE", marker, flush=True)
    return 0


def eval_worker(args) -> int:
    from ultralytics import YOLO

    weights = Path(args.weights)
    if not weights.exists():
        raise FileNotFoundError(weights)
    print("EVAL_WORKER_FRESH_PROCESS", os.getpid(), weights, flush=True)
    best = YOLO(str(weights), task="detect")
    val = best.val(
        data=str(DATA), split="val", imgsz=args.imgsz, batch=args.batch, device=0,
        project=str(PROJECT), name=f"{args.run_name}_val", exist_ok=True, verbose=False,
    )
    test = best.val(
        data=str(DATA), split="test", imgsz=args.imgsz, batch=args.batch, device=0,
        project=str(PROJECT), name=f"{args.run_name}_test", exist_ok=True, verbose=False,
    )
    fused_model = YOLO(str(weights), task="detect")
    gflops_eval_graph = model_gflops(fused_model.model)
    fused_model.model.fuse()
    fused_params = int(sum(p.numel() for p in fused_model.model.parameters()))
    gflops_fused_inference = model_gflops(fused_model.model)
    stat = weights.stat()
    payload = {
        "status": "done", "run_name": args.run_name, "candidate": args.candidate,
        "seed": args.seed, "weights": str(weights), "weights_size": stat.st_size,
        "weights_mtime_ns": stat.st_mtime_ns, "params_fused": fused_params,
        "gflops": gflops_eval_graph, "gflops_fused_inference": gflops_fused_inference,
        "val": metric_dict(val), "test": metric_dict(test), "evaluated_at": now(),
        "eval_pid": os.getpid(),
    }
    output = PROJECT / args.run_name / "independent_eval.json"
    atomic_json(output, payload)
    print("EVAL_WORKER_DONE", output, flush=True)
    return 0


def subprocess_checked(arguments: list[str]) -> None:
    print("SUBPROCESS", " ".join(arguments), flush=True)
    completed = subprocess.run(arguments, check=False)
    if completed.returncode != 0:
        raise RuntimeError(f"subprocess failed rc={completed.returncode}: {' '.join(arguments)}")


def experiment_is_current(record: dict) -> bool:
    if record.get("status") != "done":
        return False
    weights = Path(record.get("weights", ""))
    if not weights.exists():
        return False
    stat = weights.stat()
    return record.get("weights_size") == stat.st_size and record.get("weights_mtime_ns") == stat.st_mtime_ns


def ensure_experiment(
    report: dict, configs: dict[str, Path], candidate: str, seed: int,
    epochs: int, batch: int, imgsz: int, force: bool = False,
) -> dict:
    key = run_name(candidate, seed)
    existing = report["experiments"].get(key, {})
    if not force and experiment_is_current(existing):
        print("SKIP_CURRENT", key, flush=True)
        return existing

    weights = PROJECT / key / "weights" / "best.pt"
    if existing.get("status") == "done" and weights.exists() and not experiment_is_current(existing):
        backup = REPORT_JSON.with_name(f"report.polluted_{key}_{time.strftime('%Y%m%d_%H%M%S')}.json")
        if REPORT_JSON.exists():
            shutil.copy2(REPORT_JSON, backup)
        report["decisions"].setdefault("pollution_backups", []).append(str(backup))
        print("REPORT_POLLUTION_DETECTED_REEVAL", key, backup, flush=True)
    else:
        save_status("training", key, [], "fresh train; resume disabled")
        subprocess_checked([
            sys.executable, str(SCRIPT), "--worker-train", "--candidate", candidate,
            "--run-name", key, "--cfg", str(configs[candidate]), "--seed", str(seed),
            "--epochs", str(epochs), "--batch", str(batch), "--imgsz", str(imgsz),
        ])

    save_status("evaluating", key, [], "fresh process reloads best.pt")
    subprocess_checked([
        sys.executable, str(SCRIPT), "--worker-eval", "--candidate", candidate,
        "--run-name", key, "--weights", str(weights), "--seed", str(seed),
        "--batch", str(batch), "--imgsz", str(imgsz),
    ])
    evaluated = json.loads((PROJECT / key / "independent_eval.json").read_text(encoding="utf-8"))
    train_marker = PROJECT / key / "train_worker.json"
    if train_marker.exists():
        evaluated.update({
            "cfg": str(configs[candidate]), "epochs": epochs, "batch": batch, "imgsz": imgsz,
            "params_unfused": json.loads(train_marker.read_text(encoding="utf-8")).get("params_unfused"),
        })
    report["experiments"][key] = evaluated
    atomic_json(REPORT_JSON, report)
    write_markdown(report)
    return evaluated


def safe_ensure_experiment(
    report: dict, configs: dict[str, Path], candidate: str, seed: int,
    epochs: int, batch: int, imgsz: int, force: bool = False,
) -> dict | None:
    """隔离单候选失败：记录证据后继续后续候选，不让一个异常掐掉整批。"""
    key = run_name(candidate, seed)
    try:
        return ensure_experiment(report, configs, candidate, seed, epochs, batch, imgsz, force)
    except Exception as exc:  # noqa: BLE001
        import traceback
        traceback.print_exc()
        report["experiments"][key] = {
            "status": "failed", "candidate": candidate, "seed": seed,
            "error": repr(exc), "failed_at": now(),
        }
        atomic_json(REPORT_JSON, report)
        write_markdown(report)
        save_status("running", None, [], f"candidate {key} failed and was isolated")
        print("CANDIDATE_FAILED_ISOLATED", key, repr(exc), flush=True)
        return None


def seed0_gate(record: dict) -> dict:
    test = record["test"]
    classes = test["per_class"]
    pitted_delta = classes["pitted_surface"]["map50_95"] - MSDGS_SEED0["per_class"]["pitted_surface"]["map50_95"]
    rolled_delta = classes["rolled-in_scale"]["map50_95"] - MSDGS_SEED0["per_class"]["rolled-in_scale"]["map50_95"]
    crazing_delta = classes["crazing"]["map50_95"] - MSDGS_SEED0["per_class"]["crazing"]["map50_95"]
    checks = {
        "map50_95_gt_0.401794": test["map50_95"] > SEED0_MAP_GATE,
        "map50_ge_0.722411": test["map50"] >= SEED0_MAP50_FLOOR,
        "target_class_gain_ge_0.01": max(pitted_delta, rolled_delta) >= 0.01,
        "crazing_drop_le_0.02": crazing_delta >= -0.02,
    }
    return {
        "pass": all(checks.values()), "ideal": test["map50_95"] >= IDEAL_MAP,
        "checks": checks, "deltas_vs_msdgs": {
            "map50": test["map50"] - MSDGS_SEED0["map50"],
            "map50_95": test["map50_95"] - MSDGS_SEED0["map50_95"],
            "pitted_surface_map50_95": pitted_delta,
            "rolled-in_scale_map50_95": rolled_delta,
            "crazing_map50_95": crazing_delta,
        },
    }


def multiseed_summary(report: dict, candidate: str) -> dict | None:
    records = []
    for seed in range(4):
        record = report["experiments"].get(run_name(candidate, seed))
        if not record or record.get("status") != "done":
            return None
        records.append(record)
    values = [r["test"]["map50_95"] for r in records]
    map50_values = [r["test"]["map50"] for r in records]
    fps_values = [r["test"].get("fps_infer_only") for r in records]
    valid_fps = [value for value in fps_values if value is not None]
    diffs = [values[i] - MSDGS_SEED_MAP[i] for i in range(4)]
    mean = statistics.fmean(values)
    summary = {
        "seeds": [0, 1, 2, 3], "test_map50_95": values,
        "mean_map50_95": mean, "std_map50_95": statistics.stdev(values),
        "mean_map50": statistics.fmean(map50_values),
        "params_fused": records[0].get("params_fused"),
        "gflops_fused_inference": records[0].get("gflops_fused_inference"),
        "mean_fps_infer_only": statistics.fmean(valid_fps) if valid_fps else None,
        "paired_diff_vs_msdgs": diffs,
        "paired_mean_gain": statistics.fmean(diffs),
        "positive_seeds": sum(delta > 0 for delta in diffs),
    }
    summary["checks"] = {
        "paired_mean_gain_ge_0.003": summary["paired_mean_gain"] >= 0.003,
        "positive_seeds_ge_3": summary["positive_seeds"] >= 3,
        "mean_gt_msdgs": mean > MSDGS_MEAN,
        "mean_gt_gsdown": mean > GSDOWN_MEAN,
    }
    summary["pass"] = all(summary["checks"].values())
    return summary


def rank_multiseed_summaries(summaries: dict[str, dict | None]) -> list[dict]:
    """按主指标排序；距组首 <0.001 时依次按 mAP50/参数/FLOPs/FPS 决胜。"""
    items = [{"candidate": candidate, **summary} for candidate, summary in summaries.items() if summary]
    items.sort(key=lambda x: x["mean_map50_95"], reverse=True)
    ranked: list[dict] = []
    index = 0
    while index < len(items):
        leader = items[index]["mean_map50_95"]
        end = index + 1
        while end < len(items) and leader - items[end]["mean_map50_95"] < 0.001:
            end += 1
        tied = items[index:end]
        tied.sort(key=lambda x: (
            -x["mean_map50"],
            x.get("params_fused") if x.get("params_fused") is not None else 10**12,
            x.get("gflops_fused_inference") if x.get("gflops_fused_inference") is not None else 10**9,
            -(x.get("mean_fps_infer_only") or 0.0),
        ))
        ranked.extend(tied)
        index = end
    return ranked


def write_markdown(report: dict) -> None:
    """生成人可读总报告，包含总体指标、六类 AP、成本、门槛、多 seed 和最终排名。"""

    def fmt(value: Any, digits: int = 6) -> str:
        if value is None or value == "":
            return ""
        if isinstance(value, bool):
            return "PASS" if value else "FAIL"
        if isinstance(value, int):
            return str(value)
        return f"{float(value):.{digits}f}"

    experiments = report.get("experiments", {})
    decisions = report.get("decisions", {})
    gates = decisions.get("seed0_gates", {})
    lines = [
        "# MSDGS P5 定向 Detect 实验报告", "",
        f"更新时间：{now()}", "",
        "固定协议：250 epochs / imgsz 640 / batch 32 / cache=False / yolo26n.pt / NEU-DET；最终指标均由独立新进程重载 `best.pt`。",
        "", "## 总体结果", "",
        "| 候选 | Seed | Split | Precision | Recall | mAP50 | mAP50-95 | fused 参数 | fused GFLOPs | infer ms | FPS | Seed0 晋级 |",
        "|---|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    for key, record in sorted(experiments.items()):
        if record.get("status") != "done":
            continue
        gate = gates.get(key, {})
        for split in ("val", "test"):
            metric = record[split]
            lines.append(
                f"| {record.get('candidate')} | {record.get('seed')} | {split} | "
                f"{fmt(metric.get('precision'))} | {fmt(metric.get('recall'))} | "
                f"{fmt(metric.get('map50'))} | {fmt(metric.get('map50_95'))} | "
                f"{record.get('params_fused', '')} | {fmt(record.get('gflops_fused_inference'))} | "
                f"{fmt(metric.get('infer_ms'))} | {fmt(metric.get('fps_infer_only'), 2)} | "
                f"{fmt(gate.get('pass')) if record.get('seed') == 0 else '-'} |"
            )

    lines.extend([
        "", "## Seed0 六类 AP", "",
        "| 候选 | Split | 类别 | AP50 | AP50-95 |",
        "|---|---|---|---:|---:|",
    ])
    for key, record in sorted(experiments.items()):
        if record.get("status") != "done" or record.get("seed") != 0:
            continue
        for split in ("val", "test"):
            for class_name in NAMES:
                metric = record[split].get("per_class", {}).get(class_name, {})
                lines.append(
                    f"| {record.get('candidate')} | {split} | {class_name} | "
                    f"{fmt(metric.get('map50'))} | {fmt(metric.get('map50_95'))} |"
                )

    lines.extend(["", "## Seed0 条件决策", ""])
    if gates:
        lines.extend([
            "| 候选 | mAP50-95 门槛 | mAP50 下限 | 目标类增益 | crazing 保护 | 总判定 | 理想值 |",
            "|---|---|---|---|---|---|---|",
        ])
        for key, gate in sorted(gates.items()):
            checks = gate.get("checks", {})
            lines.append(
                f"| {key} | {fmt(checks.get('map50_95_gt_0.401794'))} | "
                f"{fmt(checks.get('map50_ge_0.722411'))} | "
                f"{fmt(checks.get('target_class_gain_ge_0.01'))} | "
                f"{fmt(checks.get('crazing_drop_le_0.02'))} | {fmt(gate.get('pass'))} | "
                f"{fmt(gate.get('ideal'))} |"
            )
    else:
        lines.append("尚无完成的 seed0 判定。")
    lines.extend(["", "```json", json.dumps(decisions, indent=2, ensure_ascii=False), "```"])

    lines.extend([
        "", "## 多 Seed 汇总", "",
        "| 候选 | mean mAP50-95 | std | mean mAP50 | 配对平均增益 | 正增益 seeds | mean FPS | 最终门槛 |",
        "|---|---:|---:|---:|---:|---:|---:|---|",
    ])
    summaries = report.get("summaries", {})
    for candidate, summary in sorted(summaries.items()):
        if not summary:
            continue
        lines.append(
            f"| {candidate} | {fmt(summary.get('mean_map50_95'))} | {fmt(summary.get('std_map50_95'))} | "
            f"{fmt(summary.get('mean_map50'))} | {fmt(summary.get('paired_mean_gain'))} | "
            f"{summary.get('positive_seeds', '')}/4 | {fmt(summary.get('mean_fps_infer_only'), 2)} | "
            f"{fmt(summary.get('pass'))} |"
        )
    if not any(summaries.values()):
        lines.append("| - | - | - | - | - | - | - | - |")

    lines.extend([
        "", "## 最终排名", "",
        "| 排名 | 候选 | mean mAP50-95 | mean mAP50 | 参数 | GFLOPs | FPS | 验收 |",
        "|---:|---|---:|---:|---:|---:|---:|---|",
    ])
    ranking = report.get("final_ranking", [])
    for index, item in enumerate(ranking, 1):
        lines.append(
            f"| {index} | {item.get('candidate')} | {fmt(item.get('mean_map50_95'))} | "
            f"{fmt(item.get('mean_map50'))} | {item.get('params_fused', '')} | "
            f"{fmt(item.get('gflops_fused_inference'))} | {fmt(item.get('mean_fps_infer_only'), 2)} | "
            f"{fmt(item.get('pass'))} |"
        )
    if not ranking:
        lines.append("| - | 尚未形成多 seed 排名 | - | - | - | - | - | - |")
    lines.append("")
    REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


def assert_gpu_idle_before_start() -> None:
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader"],
            text=True, capture_output=True, check=False,
        )
    except FileNotFoundError:
        return
    busy = result.stdout.strip()
    if busy:
        raise RuntimeError(f"GPU already has compute processes; refusing duplicate training:\n{busy}")


def orchestrate(args) -> int:
    import fcntl

    PROJECT.mkdir(parents=True, exist_ok=True)
    lock_handle = LOCK_FILE.open("a+")
    try:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        raise RuntimeError("another MSDGSDetect orchestrator is already running") from exc

    assert_gpu_idle_before_start()
    for required in (DATA, BASE_YAML, OFFICIAL_WEIGHTS):
        if not required.exists():
            raise FileNotFoundError(required)
    configs = generate_configs()
    report = load_report()
    # 每次恢复都从当前磁盘 checkpoint 重算派生决策，避免旧 gate/summary 混入新排名。
    report.setdefault("decisions", {})["seed0_gates"] = {}
    for key in ("combo", "p5_cafm", "multiseed_candidates"):
        report["decisions"].pop(key, None)
    report["summaries"] = {}
    report.pop("final_ranking", None)
    report.pop("finished_at", None)
    atomic_json(REPORT_JSON, report)
    save_status("running", None, [A_NAME, B_NAME], "seed0 stage")

    seed0_records: dict[str, dict] = {}
    for candidate in (A_NAME, B_NAME):
        record = safe_ensure_experiment(report, configs, candidate, 0, args.epochs, args.batch, args.imgsz, args.force)
        if record is None:
            continue
        gate = seed0_gate(record)
        report["decisions"].setdefault("seed0_gates", {})[run_name(candidate, 0)] = gate
        seed0_records[candidate] = record
        atomic_json(REPORT_JSON, report)
        write_markdown(report)

    ab_pass = any(
        report["decisions"].get("seed0_gates", {}).get(run_name(x, 0), {}).get("pass", False)
        for x in (A_NAME, B_NAME)
    )
    if ab_pass:
        combo = safe_ensure_experiment(report, configs, AB_NAME, 0, args.epochs, args.batch, args.imgsz, args.force)
        if combo is not None:
            report["decisions"].setdefault("seed0_gates", {})[run_name(AB_NAME, 0)] = seed0_gate(combo)
            seed0_records[AB_NAME] = combo
        report["decisions"]["combo"] = "trained because A or B passed seed0 gate"
    else:
        report["decisions"]["combo"] = "skipped because neither A nor B exceeded the full seed0 gate"

    primary = list(seed0_records.values())
    if primary:
        best_primary = max(primary, key=lambda r: r["test"]["map50_95"])
        best_gate = seed0_gate(best_primary)
        target = best_gate["deltas_vs_msdgs"]
        cafm_needed = (
            not any(seed0_gate(r)["pass"] for r in primary)
            or best_primary["test"]["map50_95"] < IDEAL_MAP
            or (target["pitted_surface_map50_95"] < 0 and target["rolled-in_scale_map50_95"] < 0)
        )
    else:
        cafm_needed = True
    if cafm_needed:
        cafm = safe_ensure_experiment(report, configs, CAFM_NAME, 0, args.epochs, args.batch, args.imgsz, args.force)
        if cafm is not None:
            report["decisions"].setdefault("seed0_gates", {})[run_name(CAFM_NAME, 0)] = seed0_gate(cafm)
            seed0_records[CAFM_NAME] = cafm
        report["decisions"]["p5_cafm"] = "trained because preceding candidates did not fully reach ideal/target-class condition"
    else:
        report["decisions"]["p5_cafm"] = "skipped because a preceding candidate reached the ideal and target-class condition"

    passing = [
        candidate for candidate in seed0_records
        if report["decisions"]["seed0_gates"][run_name(candidate, 0)]["pass"]
    ]
    report["decisions"]["multiseed_candidates"] = passing
    atomic_json(REPORT_JSON, report)
    write_markdown(report)

    for candidate in passing:
        for seed in (1, 2, 3):
            safe_ensure_experiment(report, configs, candidate, seed, args.epochs, args.batch, args.imgsz, args.force)
        report["summaries"][candidate] = multiseed_summary(report, candidate)
        atomic_json(REPORT_JSON, report)
        write_markdown(report)

    report["final_ranking"] = rank_multiseed_summaries(report["summaries"])
    report["finished_at"] = now()
    atomic_json(REPORT_JSON, report)
    write_markdown(report)
    save_status("done", None, [], "all conditional stages finished")
    print("MSDGS_DETECT_ABLATION_DONE", REPORT_JSON, flush=True)
    return 0


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser()
    p.add_argument("--worker-train", action="store_true")
    p.add_argument("--worker-eval", action="store_true")
    p.add_argument("--candidate", choices=list(SPECS))
    p.add_argument("--run-name")
    p.add_argument("--cfg")
    p.add_argument("--weights")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--epochs", type=int, default=250)
    p.add_argument("--batch", type=int, default=32)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--force", action="store_true")
    return p


def main() -> int:
    args = parser().parse_args()
    if args.worker_train:
        return train_worker(args)
    if args.worker_eval:
        return eval_worker(args)
    return orchestrate(args)


if __name__ == "__main__":
    raise SystemExit(main())