#!/usr/bin/env python
"""iter30：MSDGS neck 基座 + backbone P4 层6 C3k2 → DySnakeC3k2（Dynamic Snake Conv）。

核心假设（承接 iter29 诊断）：
crazing 是本 goal 万年最弱类（test mAP50 0.443），形态是弥散弯曲的裂纹网；map50-95/map50
比值 0.347 全场最低 → 定位吃亏于「弯曲细长结构」。Dynamic Snake Conv（DSCNet, ICCV2023）卷积核
沿蛇形曲线可学习变形、蜿蜒采样，天生追踪细长/弯曲结构，属本 goal 唯一有效规律「几何自适应类」。

集成：MSDGS(135eq) neck 基座 + backbone 层6 C3k2 → DySnakeC3k2（通道守恒双朝向蛇形 bottleneck）。
build 验证已过：fused 1.805M(<1.936M) / end2end=True / reg_max=1 / nl=3 / 输出(1,300,6)。

对照 = gsdown 独立真值 test mAP50 0.7338 / mAP50-95 0.4018；MSDGS135eq 单独 test mAP50 0.73241 /
       mAP50-95 0.39884 / crazing map50 0.4712（历史最好，本轮起点）。base_gsdown crazing map50 0.4431。

判定（停止规则，owner 定）：只跑 seed0，盯 crazing 的 test map50 动没动。
- crazing 明显涨（+0.05 级，往 0.49+ 走）→ 机理坐实，继续多 seed + 原创化；
- 不动 → 坐实 crazing 瓶颈在数据/标注而非结构，收口回 MSDGS 效率线，不开新赛道。
纪律（13hf 教训）：单 seed 破线不算数，破线也须再上 multi-seed 配对检验。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py      # SPDConv/DySample
    python install_gsconv_modules.py          # GSConv/VoVGSCSP（gsdown head 依赖链）
    python install_msdgs_module.py            # MSDGS
    python install_dysnake_module.py          # DySnakeC3k2
    python -u train_dysnake_gsdown.py

输出：
- runs_dysnake_gsdown_e250/<name>/weights/best.pt
- generated_models_dysnake_gsdown_e250/<name>.yaml
- runs_dysnake_gsdown_e250/report.json / status.json
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import time

import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
PROJECT = ROOT / "runs_dysnake_gsdown_e250"
GEN_DIR = ROOT / "generated_models_dysnake_gsdown_e250"
REPORT_JSON = PROJECT / "report.json"
STATUS_JSON = PROJECT / "status.json"

NAMES = ["crazing", "inclusion", "patches", "pitted_surface", "rolled-in_scale", "scratches"]

# 对照真值（独立进程 fused 口径）
GSDOWN_TRUTH = {"test_map50": 0.7338, "test_map50_95": 0.4018, "crazing_map50": 0.4431}
MSDGS135EQ_TRUTH = {"test_map50": 0.73241, "test_map50_95": 0.39884, "crazing_map50": 0.4712}


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def _swap_neck_to_msdgs(doc: dict, dilations=(1, 3, 5), fracs=(1, 1, 1)) -> int:
    """把 gsdown head 里所有 VoVGSCSP 换成 MSDGS(135eq)。返回替换数。"""
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            block[2] = "MSDGS"
            block[3] = [c2, True, 1, 0.5, list(dilations), list(fracs)]
            n_swapped += 1
    return n_swapped


def build_msdgs_dysnake_p4_doc() -> dict:
    """MSDGS neck + backbone 层6 C3k2 → DySnakeC3k2。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_neck = _swap_neck_to_msdgs(doc)
    assert n_neck == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_neck}"
    bb = doc["backbone"]
    assert bb[6][2] == "C3k2", f"backbone[6] expected C3k2, got {bb[6][2]}"
    bb[6][2] = "DySnakeC3k2"
    print("msdgs_dysnake_p4: neck 4×VoVGSCSP→MSDGS, backbone 层6 C3k2→DySnakeC3k2")
    return doc


BUILDERS = {
    "msdgs_dysnake_p4": build_msdgs_dysnake_p4_doc,
}


def save_status(status: str, current, pending) -> None:
    PROJECT.mkdir(parents=True, exist_ok=True)
    STATUS_JSON.write_text(json.dumps({
        "status": status, "current": current, "pending": pending,
        "updated_at": now(), "report_json": str(REPORT_JSON),
    }, indent=2, ensure_ascii=False), encoding="utf-8")


def metric_dict(m) -> dict:
    infer = float(m.speed.get("inference", 0.0) or 0.0)
    out = {
        "map50": float(m.box.map50), "map50_95": float(m.box.map),
        "precision": float(m.box.mp), "recall": float(m.box.mr),
        "infer_ms": infer, "fps_infer_only": (1000.0 / infer) if infer else None,
        "per_class": {},
    }
    for i, c in enumerate(m.ap_class_index):
        name = NAMES[int(c)] if int(c) < len(NAMES) else str(int(c))
        out["per_class"][name] = {"map50": float(m.box.ap50[i]), "map50_95": float(m.box.ap[i])}
    return out


def run_one(name: str, epochs: int, batch: int, imgsz: int, seed: int) -> dict:
    doc = BUILDERS[name]()
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{name}.yaml"
    cfg.write_text("# generated by train_dysnake_gsdown.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"CFG {cfg}")
    print(f"INIT_WEIGHTS {name} <- {OFFICIAL_WEIGHTS}")
    model = YOLO(str(cfg)).load(str(OFFICIAL_WEIGHTS))
    print(f"TRAIN_START {name} epochs={epochs} batch={batch} imgsz={imgsz} seed={seed}")
    model.train(
        data=str(DATA), epochs=epochs, imgsz=imgsz, batch=batch, workers=8,
        seed=seed, device=0, project=str(PROJECT), name=name, exist_ok=True,
        patience=max(epochs, 250), cache=False, verbose=True,
    )
    print(f"TRAIN_DONE {name}")

    weights = PROJECT / name / "weights" / "best.pt"
    best = YOLO(str(weights))
    params = int(sum(p.numel() for p in best.model.parameters()))
    v = best.val(data=str(DATA), split="val", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_val", exist_ok=True, verbose=False)
    t = best.val(data=str(DATA), split="test", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_test", exist_ok=True, verbose=False)
    return {
        "status": "done", "cfg": str(cfg), "weights": str(weights),
        "epochs": epochs, "batch": batch, "imgsz": imgsz, "seed": seed,
        "params_unfused": params,
        "val": metric_dict(v), "test": metric_dict(t),
        "finished_at": now(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=250)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--only", default="", help="逗号分隔候选名，只跑指定")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    PROJECT.mkdir(parents=True, exist_ok=True)
    selected = [x.strip() for x in args.only.split(",") if x.strip()] or list(BUILDERS)
    unknown = [x for x in selected if x not in BUILDERS]
    if unknown:
        raise SystemExit(f"unknown candidates: {unknown}")

    report = {}
    if REPORT_JSON.exists():
        report = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
    report.setdefault("schema_version", 1)
    report.setdefault("experiments", {})
    report["baseline"] = {"gsdown": GSDOWN_TRUTH, "msdgs135eq": MSDGS135EQ_TRUTH}
    completed = {k for k, v in report["experiments"].items() if v.get("status") == "done"}

    save_status("running", selected[0], selected)
    for pos, name in enumerate(selected, 1):
        if name in completed and not args.force:
            print(f"SKIP_DONE {name}")
            continue
        save_status("running", name, selected[pos:])
        try:
            result = run_one(name, args.epochs, args.batch, args.imgsz, args.seed)
        except Exception as exc:  # noqa: BLE001
            import traceback
            traceback.print_exc()
            report["experiments"][name] = {"status": "failed", "error": repr(exc), "failed_at": now()}
            REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
            save_status("failed", name, selected[pos:])
            print(f"CANDIDATE_FAILED {name} (isolated, continue)")
            continue
        report["experiments"][name] = result
        REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        d_gsdown = result["test"]["map50_95"] - GSDOWN_TRUTH["test_map50_95"]
        crazing = result["test"]["per_class"].get("crazing", {})
        print("DYSNAKE_RESULT", name,
              f"test_mAP50={result['test']['map50']:.5f}",
              f"test_mAP50-95={result['test']['map50_95']:.5f}",
              f"vs_gsdown={d_gsdown:+.5f}",
              f"crazing_map50={crazing.get('map50', float('nan')):.5f}",
              f"(gsdown 0.4431 / msdgs 0.4712)",
              f"params_unfused={result['params_unfused']}")

    save_status("done", None, [])
    print(f"DYSNAKE_DONE report={REPORT_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
