#!/usr/bin/env python
"""iter27→C：异质频率解耦 neck（HFDGS）叠到 vovgscsp_gsdown，250e 串行对照训练。

设计动机（iter027 的关键发现，本轮 C 方向）：
- iter026 把 crazing + rolled-in 打包成"弥漫纹理弱类、统一补全局上下文"，iter027（GCDGS）证伪：
  两弱类机理相反——全局加倍(13g_heavy)时 rolled-in 升到 0.296(全场最高)、crazing 跌到 0.133(全场最低)。
  crazing(裂纹网)靠细密局部高频边缘，全局池化把它抹平；rolled-in(氧化皮)靠大面积周期统计，吃全局。
- 目前最好仍是 MSDGS 135eq(test 0.3988/1.777M)，卡整体的一直是 crazing(0.13-0.18，谁都救不动)。

HFDGS = 异质分工：以 MSDGS 多尺度 local 为底座(强类已全守住)，另加机理匹配的支路——
  高频支路(治 crazing，x - avgpool(x) 提高频残差，全分辨率无空洞不抹细节)
  + 可选全局支路(治 rolled-in，iter027 已证有效)。物理隔离各支路参数与梯度，总预算对齐 VoVGSCSP。

候选（全部在 gsdown 基础上、从 yolo26n.pt 迁移、保 end2end/reg_max=1）：
- gsdown_hfdgs_135hf   : dils=(1,3,5) + HF          最干净的 HF 假设检验(对照 MSDGS 135eq 加一路 HF)
- gsdown_hfdgs_13hf    : dils=(1,3)   + HF          双尺度 local + HF
- gsdown_hfdgs_13hf_g  : dils=(1,3)   + HF + global 完整异质分工(crazing→HF/rolled-in→global/强类→local)

对照 = gsdown 独立真值 test mAP50 0.7338 / mAP50-95 0.4018 / 1.936M（轻量交付模型）。
       MSDGS 最佳 135eq 独立真值 test 0.7324 / 0.3988 / 1.777M。
判定：test 真值 > 0.4018 且保住轻量，才算破线；核心看 HF 支路能否把 crazing 拉起而不掉强类。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py      # SPDConv/DySample（gsdown 谱系依赖链）
    python install_gsconv_modules.py          # GSConv/VoVGSCSP（gsdown head 必需）
    python install_hfdgs_module.py            # HFDGS（本轮）
    python -u train_hfdgs_gsdown.py

输出：
- runs_hfdgs_gsdown_e250/<name>/weights/best.pt
- generated_models_hfdgs_gsdown_e250/<name>.yaml
- runs_hfdgs_gsdown_e250/report.json / status.json
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import time

import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
PROJECT = ROOT / "runs_hfdgs_gsdown_e250"
GEN_DIR = ROOT / "generated_models_hfdgs_gsdown_e250"
REPORT_JSON = PROJECT / "report.json"
STATUS_JSON = PROJECT / "status.json"

NAMES = ["crazing", "inclusion", "patches", "pitted_surface", "rolled-in_scale", "scratches"]


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def build_doc(dilations, hf_frac, global_frac, pool_k=3, r=4) -> dict:
    """把 gsdown head 里所有 VoVGSCSP 换成 HFDGS。backbone 一字不动。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            # VoVGSCSP args=[c2] -> HFDGS args=[c2, shortcut, g, e, dilations, hf_frac, global_frac, pool_k, r]
            block[2] = "HFDGS"
            block[3] = [c2, True, 1, 0.5, list(dilations), float(hf_frac), float(global_frac), int(pool_k), int(r)]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_swapped}"
    print(f"swapped {n_swapped} VoVGSCSP -> HFDGS (dils={dilations}, hf={hf_frac}, gc={global_frac})")
    return doc


BUILDERS = {
    "y26n_gsdown_hfdgs_135hf_e250": lambda: build_doc((1, 3, 5), 1.0, 0.0),
    "y26n_gsdown_hfdgs_13hf_e250": lambda: build_doc((1, 3), 1.0, 0.0),
    "y26n_gsdown_hfdgs_13hf_g_e250": lambda: build_doc((1, 3), 1.0, 1.0),
}


def save_status(status: str, current, pending) -> None:
    PROJECT.mkdir(parents=True, exist_ok=True)
    STATUS_JSON.write_text(json.dumps({
        "status": status, "current": current, "pending": pending,
        "updated_at": now(), "report_json": str(REPORT_JSON),
    }, indent=2, ensure_ascii=False), encoding="utf-8")


def metric_dict(m) -> dict:
    infer = float(m.speed.get("inference", 0.0) or 0.0)
    out = {
        "map50": float(m.box.map50), "map50_95": float(m.box.map),
        "precision": float(m.box.mp), "recall": float(m.box.mr),
        "infer_ms": infer, "fps_infer_only": (1000.0 / infer) if infer else None,
        "per_class": {},
    }
    for i, c in enumerate(m.ap_class_index):
        name = NAMES[int(c)] if int(c) < len(NAMES) else str(int(c))
        out["per_class"][name] = {"map50": float(m.box.ap50[i]), "map50_95": float(m.box.ap[i])}
    return out


def run_one(name: str, epochs: int, batch: int, imgsz: int, seed: int) -> dict:
    doc = BUILDERS[name]()
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{name}.yaml"
    cfg.write_text("# generated by train_hfdgs_gsdown.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"CFG {cfg}")
    print(f"INIT_WEIGHTS {name} <- {OFFICIAL_WEIGHTS}")
    model = YOLO(str(cfg)).load(str(OFFICIAL_WEIGHTS))
    print(f"TRAIN_START {name} epochs={epochs} batch={batch} imgsz={imgsz}")
    model.train(
        data=str(DATA), epochs=epochs, imgsz=imgsz, batch=batch, workers=8,
        seed=seed, device=0, project=str(PROJECT), name=name, exist_ok=True,
        patience=max(epochs, 250), cache=False, verbose=True,
    )
    print(f"TRAIN_DONE {name}")

    weights = PROJECT / name / "weights" / "best.pt"
    best = YOLO(str(weights))
    params = int(sum(p.numel() for p in best.model.parameters()))
    v = best.val(data=str(DATA), split="val", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_val", exist_ok=True, verbose=False)
    t = best.val(data=str(DATA), split="test", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_test", exist_ok=True, verbose=False)
    return {
        "status": "done", "cfg": str(cfg), "weights": str(weights),
        "epochs": epochs, "batch": batch, "imgsz": imgsz, "seed": seed,
        "params_unfused": params,
        "val": metric_dict(v), "test": metric_dict(t),
        "finished_at": now(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=250)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--only", default="", help="逗号分隔候选名，只跑指定")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    PROJECT.mkdir(parents=True, exist_ok=True)
    selected = [x.strip() for x in args.only.split(",") if x.strip()] or list(BUILDERS)
    unknown = [x for x in selected if x not in BUILDERS]
    if unknown:
        raise SystemExit(f"unknown candidates: {unknown}")

    report = {}
    if REPORT_JSON.exists():
        report = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
    report.setdefault("schema_version", 1)
    report.setdefault("experiments", {})
    completed = {k for k, v in report["experiments"].items() if v.get("status") == "done"}

    save_status("running", selected[0], selected)
    for pos, name in enumerate(selected, 1):
        if name in completed and not args.force:
            print(f"SKIP_DONE {name}")
            continue
        save_status("running", name, selected[pos:])
        try:
            result = run_one(name, args.epochs, args.batch, args.imgsz, args.seed)
        except Exception as exc:  # noqa: BLE001
            import traceback
            traceback.print_exc()
            report["experiments"][name] = {"status": "failed", "error": repr(exc), "failed_at": now()}
            REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
            save_status("failed", name, selected[pos:])
            print(f"CANDIDATE_FAILED {name} (isolated, continue)")
            continue  # 错误隔离：单候选崩溃不拖垮后续
        report["experiments"][name] = result
        REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        print("HFDGS_RESULT", name,
              f"val_mAP50={result['val']['map50']:.5f}",
              f"val_mAP50-95={result['val']['map50_95']:.5f}",
              f"test_mAP50={result['test']['map50']:.5f}",
              f"test_mAP50-95={result['test']['map50_95']:.5f}",
              f"params_unfused={result['params_unfused']}")

    save_status("done", None, [])
    print(f"HFDGS_DONE report={REPORT_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
