#!/usr/bin/env python
"""收口验证：MSDGS(135eq，效率线候选) vs gsdown(基线) 多 seed 稳健性验证。

动机：MSDGS 135eq 目前 test mAP50-95 0.3988 / fused 1.777M（参数 -8.2%、精度持平基线
0.4018），但和 iter028 的 13hf 一样，只是 seed0 单点。13hf 已被多 seed 证伪（配对 t=-0.31）。
在把 MSDGS 当"轻量不掉点"效率主线写进论文前，必须同样过多 seed 检验，否则重蹈覆辙。

方案（省算力关键）：gsdown 的 4 个 seed 已在 13hf 那轮全部训完并写入
runs_multiseed_13hf_vs_gsdown/report.json（seed0 0.4018 / seed1 0.39795 / seed2 0.39569 /
seed3 0.37870），口径为同进程 val 评估。本轮直接复用，只补 MSDGS 135eq 的 seed 1/2/3，
与 gsdown 已有 seed 同口径配对。seed0 两配置均已有值直接并入。

- MSDGS135eq = gsdown neck 的 VoVGSCSP 换成 MSDGS(dils=(1,3,5), fracs=(1,1,1))  —— 与 iter026 135eq 完全一致
- gsdown     = 原始 vovgscsp_gsdown（基线），4 seed 复用 13hf 轮结果，本脚本不重训

判定：同 seed 下 MSDGS-gsdown 差值配对 t 检验。n=4, df=3, 单尾 t_0.05=2.353。
预期：MSDGS 精度持平（差值均值≈0），t 不显著 —— 若如此，效率故事(参数-8.2%不掉点)成立；
若 MSDGS 显著更差，则效率线也不牢，需换赛道。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py
    python install_gsconv_modules.py
    python install_msdgs_module.py
    python -u train_multiseed_msdgs_vs_gsdown.py

输出：
- runs_multiseed_msdgs_vs_gsdown/msdgs135eq_seed<k>/weights/best.pt
- runs_multiseed_msdgs_vs_gsdown/report.json / status.json
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import time

import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
PROJECT = ROOT / "runs_multiseed_msdgs_vs_gsdown"
GEN_DIR = ROOT / "generated_models_multiseed_msdgs_vs_gsdown"
REPORT_JSON = PROJECT / "report.json"
STATUS_JSON = PROJECT / "status.json"

NAMES = ["crazing", "inclusion", "patches", "pitted_surface", "rolled-in_scale", "scratches"]

# 只补 MSDGS 135eq 的 seed 1/2/3；gsdown 4 seed 与 MSDGS seed0 均直接并入汇总，不重训。
SEEDS = [1, 2, 3]

# MSDGS 135eq seed0 真值（runs_msdgs_gsdown_e250/report.json，同进程评估口径）
MSDGS_SEED0 = {"test_map50": 0.73241, "test_map50_95": 0.39884}

# gsdown 4 seed 真值：seed0 独立真值 0.4018，seed1/2/3 复用 13hf 轮同进程评估
# （来源 runs_multiseed_13hf_vs_gsdown/report.json summary.gsdown_test_map50_95）
GSDOWN_TRUTH = {
    0: {"test_map50_95": 0.4018},
    1: {"test_map50_95": 0.39794662549626497},
    2: {"test_map50_95": 0.3956895455958647},
    3: {"test_map50_95": 0.378703197596629},
}


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def build_msdgs135eq_doc() -> dict:
    """gsdown head 里所有 VoVGSCSP 换成 MSDGS(dils=(1,3,5), fracs=(1,1,1))。与 iter026 135eq 一致。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            # VoVGSCSP args=[c2] -> MSDGS args=[c2, shortcut, g, e, dilations, fracs]
            block[2] = "MSDGS"
            block[3] = [c2, True, 1, 0.5, [1, 3, 5], [1, 1, 1]]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_swapped}"
    return doc


def save_status(status: str, current, pending) -> None:
    PROJECT.mkdir(parents=True, exist_ok=True)
    STATUS_JSON.write_text(json.dumps({
        "status": status, "current": current, "pending": pending,
        "updated_at": now(), "report_json": str(REPORT_JSON),
    }, indent=2, ensure_ascii=False), encoding="utf-8")


def metric_dict(m) -> dict:
    infer = float(m.speed.get("inference", 0.0) or 0.0)
    out = {
        "map50": float(m.box.map50), "map50_95": float(m.box.map),
        "precision": float(m.box.mp), "recall": float(m.box.mr),
        "infer_ms": infer, "fps_infer_only": (1000.0 / infer) if infer else None,
        "per_class": {},
    }
    for i, c in enumerate(m.ap_class_index):
        name = NAMES[int(c)] if int(c) < len(NAMES) else str(int(c))
        out["per_class"][name] = {"map50": float(m.box.ap50[i]), "map50_95": float(m.box.ap[i])}
    return out


def run_one(seed: int, epochs: int, batch: int, imgsz: int) -> dict:
    doc = build_msdgs135eq_doc()
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / "msdgs135eq.yaml"
    cfg.write_text("# generated by train_multiseed_msdgs_vs_gsdown.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    name = f"msdgs135eq_seed{seed}"
    print(f"CFG {cfg}")
    print(f"INIT_WEIGHTS {name} <- {OFFICIAL_WEIGHTS}")
    model = YOLO(str(cfg)).load(str(OFFICIAL_WEIGHTS))
    print(f"TRAIN_START {name} epochs={epochs} batch={batch} imgsz={imgsz} seed={seed}")
    model.train(
        data=str(DATA), epochs=epochs, imgsz=imgsz, batch=batch, workers=8,
        seed=seed, device=0, project=str(PROJECT), name=name, exist_ok=True,
        patience=max(epochs, 250), cache=False, verbose=True,
    )
    print(f"TRAIN_DONE {name}")

    weights = PROJECT / name / "weights" / "best.pt"
    best = YOLO(str(weights))
    params = int(sum(p.numel() for p in best.model.parameters()))
    v = best.val(data=str(DATA), split="val", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_val", exist_ok=True, verbose=False)
    t = best.val(data=str(DATA), split="test", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_test", exist_ok=True, verbose=False)
    return {
        "status": "done", "config": "msdgs135eq", "seed": seed, "cfg": str(cfg),
        "weights": str(weights), "epochs": epochs, "batch": batch, "imgsz": imgsz,
        "params_unfused": params,
        "val": metric_dict(v), "test": metric_dict(t),
        "finished_at": now(),
    }


def summarize(report: dict) -> dict:
    """汇总 MSDGS 各 seed test mAP50-95，与 gsdown 复用值做配对差值统计。"""
    exps = report.get("experiments", {})
    msdgs = {0: MSDGS_SEED0["test_map50_95"]}
    for _, r in exps.items():
        if r.get("status") == "done":
            msdgs[int(r["seed"])] = r["test"]["map50_95"]
    gsdown = {s: v["test_map50_95"] for s, v in GSDOWN_TRUTH.items()}

    common = sorted(set(msdgs) & set(gsdown))
    diffs = [msdgs[s] - gsdown[s] for s in common]

    def _stats(vals):
        n = len(vals)
        mean = sum(vals) / n if n else 0.0
        var = sum((x - mean) ** 2 for x in vals) / (n - 1) if n > 1 else 0.0
        return {"n": n, "mean": mean, "std": var ** 0.5}

    msdgs_vals = [msdgs[s] for s in common]
    gs_vals = [gsdown[s] for s in common]
    d_stat = _stats(diffs)
    n = d_stat["n"]
    se = (d_stat["std"] / (n ** 0.5)) if n > 1 and d_stat["std"] > 0 else 0.0
    t_stat = (d_stat["mean"] / se) if se > 0 else None
    return {
        "seeds": common,
        "msdgs135eq_test_map50_95": {s: msdgs[s] for s in common},
        "gsdown_test_map50_95": {s: gsdown[s] for s in common},
        "msdgs135eq_stats": _stats(msdgs_vals),
        "gsdown_stats": _stats(gs_vals),
        "paired_diff": diffs,
        "paired_diff_stats": d_stat,
        "paired_t": t_stat,
        "note": "MSDGS-gsdown 差值；t 值绝对值 > 单尾临界(n=4,df=3,t_0.05=2.353)才显著。"
                "效率线期望：差值≈0、t 不显著（持平即可，参数已省 8.2%）。",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=250)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    PROJECT.mkdir(parents=True, exist_ok=True)

    report = {}
    if REPORT_JSON.exists():
        report = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
    report.setdefault("schema_version", 1)
    report.setdefault("experiments", {})
    completed = {k for k, v in report["experiments"].items() if v.get("status") == "done"}

    job_names = [f"msdgs135eq_seed{s}" for s in SEEDS]
    save_status("running", job_names[0] if job_names else None, job_names)
    for pos, seed in enumerate(SEEDS, 1):
        name = f"msdgs135eq_seed{seed}"
        if name in completed and not args.force:
            print(f"SKIP_DONE {name}")
            continue
        save_status("running", name, job_names[pos:])
        try:
            result = run_one(seed, args.epochs, args.batch, args.imgsz)
        except Exception as exc:  # noqa: BLE001
            import traceback
            traceback.print_exc()
            report["experiments"][name] = {"status": "failed", "config": "msdgs135eq", "seed": seed,
                                           "error": repr(exc), "failed_at": now()}
            REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
            save_status("failed", name, job_names[pos:])
            print(f"JOB_FAILED {name} (isolated, continue)")
            continue
        report["experiments"][name] = result
        report["summary"] = summarize(report)
        REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        print("MULTISEED_RESULT", name,
              f"test_mAP50={result['test']['map50']:.5f}",
              f"test_mAP50-95={result['test']['map50_95']:.5f}")

    report["summary"] = summarize(report)
    REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    save_status("done", None, [])
    print("MULTISEED_SUMMARY", json.dumps(report["summary"], ensure_ascii=False))
    print(f"MULTISEED_DONE report={REPORT_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
