#!/usr/bin/env python
"""iter063：对 iter37 PKI 候选 msdgs_pki_l4 补跑 seed 1/2/3，独立重载评测每个 best.pt。

背景与 owner 决策：
- iter37 PKI（MSDGS135eq 基座 + backbone 层4 C3k2->PKIC3k2 并联 DW 3/5/7）seed0 单点
  test mAP50=0.73878（+0.5pp vs gsdown 0.7338，+0.6pp vs MSDGS 0.732411），但当时因
  test mAP50-95 掉（0.38788 < 0.4018）被双指标标准判死、未上多 seed。
- owner 现放宽判定为「只要 mAP50 多 seed 均值稳健提升即可」（mAP50-95/crazing 仍完整记录，
  不作否决项）。本轮补跑 seed 1/2/3，与现存 seed0 合并成四 seed，看 mAP50 均值是否稳健
  > MSDGS 锚点 0.7324（最好 > gsdown 0.7379）。

铁律（同 DCNv2 多 seed 口径）：
- 结构、训练协议与 iter37 seed0 完全一致，只改 seed 和 run name。
- 每个 seed 训完由独立新进程（eval_msdgs_candidate.py）重载磁盘 best.pt 做 val/test 真值。
- seed0 复用 iter37 现存 runs_pki_gsdown_e250/report.json 的权威结果，不重训。
- DCNv2 seed0 涨 mAP50、多 seed 塌回的教训：单 seed 涨不算数，只认多 seed 均值。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_gsconv_modules.py    # GSConv/VoVGSCSP（gsdown head 必需）
    python install_msdgs_module.py      # MSDGS（基座 neck）
    python install_pki_module.py        # PKIC3k2（本候选）
    setsid python -u train_multiseed_pki.py > pki_multiseed_e250.log 2>&1 &

输出：
- runs_pki_multiseed_e250/msdgs_pki_l4_seed{1,2,3}/weights/best.pt
- runs_pki_multiseed_e250/independent_seed{1,2,3}_report.json
- runs_pki_multiseed_e250/report.json / report.md / status.json
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import statistics
import subprocess
import sys
import time
import traceback

import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_pki_multiseed_e250"
PROJECT = ROOT / "runs_pki_multiseed_e250"
STATUS = PROJECT / "status.json"
REPORT = PROJECT / "report.json"
REPORT_MD = PROJECT / "report.md"
LOCK = PROJECT / ".train.lock"
SCRIPT = Path(__file__).resolve()
EVALUATOR = ROOT / "eval_msdgs_candidate.py"
# iter37 seed0 权威独立真值来源（report.json 里 experiments.msdgs_pki_l4）。
SEED0_REPORT = ROOT / "runs_pki_gsdown_e250" / "report.json"
SEED0_KEY = "msdgs_pki_l4"
CANDIDATE = "msdgs_pki_l4"
DEFAULT_SEEDS = (1, 2, 3)

# 对照锚（iter37 权威独立真值）。
GSDOWN = {
    "test_map50": 0.7338,
    "test_map50_95": 0.4018,
    "fused_params": 1935814,
}
MSDGS = {
    "test_map50": 0.7324113100352823,
    "test_map50_95": 0.3988372172746915,
    "test_crazing_map50_95": 0.1770695825201802,
}


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def atomic_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(path)


def save_status(status: str, current=None, pending=None, note: str = "", **extra) -> None:
    atomic_json(
        STATUS,
        {
            "status": status,
            "candidate": CANDIDATE,
            "current": current,
            "pending": list(pending or []),
            "note": note,
            "updated_at": now(),
            "pid": os.getpid(),
            "project": str(PROJECT),
            "report": str(REPORT),
            **extra,
        },
    )


def generate_yaml() -> Path:
    """把 MSDGS 基座 backbone 层4 的 C3k2[512,false,0.25] 换成 PKIC3k2。

    与 iter37 train_pki_gsdown.py build_pki_l4 识别逻辑一致：定位 backbone 里
    module=='C3k2' 且 args==[512, False, ...] 的第一处（层4，运行时 width=0.25->128）。
    """
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    bb = doc.get("backbone", [])
    swapped_at = []
    for i, block in enumerate(bb):
        if (
            len(block) >= 4
            and block[2] == "C3k2"
            and block[3]
            and block[3][0] == 512
            and len(block[3]) >= 2
            and block[3][1] is False
        ):
            block[2] = "PKIC3k2"
            swapped_at.append(i)
            break
    assert len(swapped_at) == 1, f"expected 1 layer4 C3k2[512,false], swapped at {swapped_at}"
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{CANDIDATE}.yaml"
    cfg.write_text(
        "# generated by train_multiseed_pki.py (iter063)\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"CFG {cfg}  swapped backbone index {swapped_at[0]} C3k2 -> PKIC3k2 (layer4)")
    return cfg


def gpu_idle() -> None:
    result = subprocess.run(
        ["nvidia-smi", "--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader"],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"nvidia-smi failed: {result.stderr.strip()}")
    if result.stdout.strip():
        raise RuntimeError(f"GPU already busy; refusing duplicate training:\n{result.stdout.strip()}")


def run_checked(command: list[str]) -> None:
    print("SUBPROCESS", " ".join(command), flush=True)
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"subprocess failed rc={result.returncode}: {' '.join(command)}")


def archive_partial(target: Path) -> None:
    if not target.exists():
        return
    archive = target.with_name(target.name + f"_interrupted_{time.strftime('%Y%m%d_%H%M%S')}")
    shutil.move(str(target), str(archive))
    print("ARCHIVED_EXISTING_RUN", target, "->", archive, flush=True)


def train_worker(args) -> int:
    from ultralytics import YOLO

    target = PROJECT / args.name
    archive_partial(target)
    print("TRAIN_WORKER_START", os.getpid(), args.name, f"seed={args.seed}", flush=True)
    model = YOLO(args.cfg, task="detect").load(str(OFFICIAL_WEIGHTS))

    # 结构断言：层4 = PKIC3k2；neck/head 不变；end2end/reg_max=1。
    layer4 = model.model.model[4]
    head = model.model.model[-1]
    assert type(layer4).__name__ == "PKIC3k2", type(layer4).__name__
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    assert tuple(int(t[0].conv.in_channels) for t in head.cv2) == (64, 128, 256)

    params_unfused = int(sum(p.numel() for p in model.model.parameters()))
    model.train(
        data=str(DATA),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        workers=8,
        seed=args.seed,
        device=0,
        project=str(PROJECT),
        name=args.name,
        exist_ok=True,
        patience=max(args.epochs, 250),
        cache=False,
        resume=False,
        verbose=True,
    )
    weights = target / "weights" / "best.pt"
    if not weights.is_file():
        raise FileNotFoundError(weights)
    atomic_json(
        target / "train_worker.json",
        {
            "status": "done",
            "candidate": CANDIDATE,
            "name": args.name,
            "seed": args.seed,
            "cfg": args.cfg,
            "weights": str(weights),
            "params_unfused": params_unfused,
            "finished_at": now(),
        },
    )
    print("TRAIN_WORKER_DONE", args.name, weights, flush=True)
    return 0


def gate(result: dict) -> dict:
    """owner 放宽后的主判定 = mAP50；mAP50-95/crazing 完整记录不否决。"""
    test = result["test"]
    crazing = test["per_class"]["crazing"]["map50_95"]
    return {
        "map50_gt_msdgs": test["map50"] > MSDGS["test_map50"],
        "map50_gt_gsdown": test["map50"] > GSDOWN["test_map50"],
        "deltas": {
            "map50_vs_msdgs": test["map50"] - MSDGS["test_map50"],
            "map50_vs_gsdown": test["map50"] - GSDOWN["test_map50"],
            "map50_95_vs_gsdown": test["map50_95"] - GSDOWN["test_map50_95"],
            "crazing_map50_95_vs_msdgs": crazing - MSDGS["test_crazing_map50_95"],
        },
    }


def normalize_result(result: dict, seed: int, name: str, cfg: Path, source: str) -> dict:
    normalized = dict(result)
    normalized.update(
        {
            "status": "done",
            "candidate": CANDIDATE,
            "name": name,
            "seed": seed,
            "cfg": str(cfg),
            "source": source,
        }
    )
    normalized["gate"] = gate(normalized)
    return normalized


def metric_stats(values: list[float]) -> dict:
    return {
        "n": len(values),
        "mean": statistics.mean(values),
        "std": statistics.stdev(values) if len(values) > 1 else 0.0,
        "min": min(values),
        "max": max(values),
        "range": max(values) - min(values),
    }


def summarize(experiments: dict) -> dict:
    done = sorted(
        (item for item in experiments.values() if item.get("status") == "done"),
        key=lambda item: int(item["seed"]),
    )
    if not done:
        return {"n": 0}
    map50 = [item["test"]["map50"] for item in done]
    map5095 = [item["test"]["map50_95"] for item in done]
    crazing = [item["test"]["per_class"]["crazing"]["map50_95"] for item in done]
    seeds = [int(item["seed"]) for item in done]
    map50_stats = metric_stats(map50)
    return {
        "n": len(done),
        "seeds": seeds,
        "test_map50": map50_stats,
        "test_map50_95": metric_stats(map5095),
        "test_crazing_map50_95": metric_stats(crazing),
        # owner 放宽判定：mAP50 均值稳健性。
        "map50_mean_gt_msdgs": map50_stats["mean"] > MSDGS["test_map50"],
        "map50_mean_gt_gsdown": map50_stats["mean"] > GSDOWN["test_map50"],
        "map50_min_gt_msdgs": map50_stats["min"] > MSDGS["test_map50"],
        "map50_mean_vs_msdgs": map50_stats["mean"] - MSDGS["test_map50"],
        "map50_mean_vs_gsdown": map50_stats["mean"] - GSDOWN["test_map50"],
    }


def write_markdown(payload: dict) -> None:
    experiments = payload.get("experiments", {})
    summary = payload.get("summary", {})
    lines = [
        "# iter063 PKI (msdgs_pki_l4) 多 seed mAP50 稳健性报告",
        "",
        "固定协议：250 epochs / imgsz=640 / batch=32 / cache=False / resume=False / yolo26n.pt。",
        "结构=MSDGS135eq 基座 + backbone 层4 C3k2->PKIC3k2（并联 DW 3/5/7）。",
        "seed0 复用 iter37 权威独立真值；seed1/2/3 本轮补跑，均由独立新进程重载 best.pt 评测。",
        "owner 放宽判定：主指标=test mAP50 多 seed 均值（mAP50-95/crazing 完整记录，不否决）。",
        "",
        "| seed | test mAP50 | test mAP50-95 | crazing mAP50-95 | params_fused | 来源 |",
        "|---:|---:|---:|---:|---:|---|",
    ]
    for item in sorted(experiments.values(), key=lambda x: int(x.get("seed", 999))):
        if item.get("status") != "done":
            lines.append(f"| {item.get('seed')} | - | - | - | - | {item.get('status', 'pending')} |")
            continue
        test = item["test"]
        crazing = test["per_class"]["crazing"]["map50_95"]
        fused = item.get("params_fused", "-")
        src = "iter37" if int(item["seed"]) == 0 else "本轮"
        lines.append(
            f"| {item['seed']} | {test['map50']:.6f} | {test['map50_95']:.6f} | "
            f"{crazing:.6f} | {fused} | {src} |"
        )
    # 对照锚行。
    lines += [
        f"| gsdown | {GSDOWN['test_map50']:.6f} | {GSDOWN['test_map50_95']:.6f} | - | {GSDOWN['fused_params']} | baseline |",
        f"| MSDGS | {MSDGS['test_map50']:.6f} | {MSDGS['test_map50_95']:.6f} | {MSDGS['test_crazing_map50_95']:.6f} | 1777318 | 主线 |",
    ]
    if summary.get("n"):
        s50 = summary["test_map50"]
        lines += [
            "",
            "## mAP50 稳健性判定",
            "",
            f"- n={summary['n']}  seeds={summary['seeds']}",
            f"- test mAP50 均值 = {s50['mean']:.6f}（std {s50['std']:.6f}, min {s50['min']:.6f}, max {s50['max']:.6f}, range {s50['range']:.6f}）",
            f"- 均值 vs MSDGS 0.7324 = {summary['map50_mean_vs_msdgs']:+.6f}  ->  {'PASS' if summary['map50_mean_gt_msdgs'] else 'FAIL'}",
            f"- 均值 vs gsdown 0.7338 = {summary['map50_mean_vs_gsdown']:+.6f}  ->  {'PASS' if summary['map50_mean_gt_gsdown'] else 'FAIL'}",
            f"- 最差 seed mAP50 > MSDGS 均值 = {'是' if summary['map50_min_gt_msdgs'] else '否'}",
        ]
    lines += ["", "## 汇总 JSON", "", "```json", json.dumps(summary, indent=2, ensure_ascii=False), "```", ""]
    REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


def load_seed0(cfg: Path) -> dict:
    """从 iter37 report.json 取 seed0 权威独立真值。"""
    src = json.loads(SEED0_REPORT.read_text(encoding="utf-8"))
    seed0 = src["experiments"][SEED0_KEY]
    result = {
        "weights": seed0.get("weights"),
        "params_unfused": seed0.get("params_unfused"),
        "params_fused": seed0.get("params_fused"),
        "val": seed0["val"],
        "test": seed0["test"],
    }
    return normalize_result(result, 0, CANDIDATE, cfg, "iter37 runs_pki_gsdown_e250/report.json")


def load_or_initialize(cfg: Path, args) -> dict:
    if REPORT.exists():
        payload = json.loads(REPORT.read_text(encoding="utf-8"))
    else:
        payload = {
            "schema_version": 1,
            "iteration": 63,
            "candidate": CANDIDATE,
            "started_at": now(),
            "protocol": {
                "epochs": args.epochs,
                "imgsz": args.imgsz,
                "batch": args.batch,
                "seeds_requested": list(args.seeds),
                "cache": False,
                "resume": False,
                "init_weights": str(OFFICIAL_WEIGHTS),
                "data": str(DATA),
                "final_eval": "independent subprocess reloads each best.pt for val and test",
                "decision": "owner 放宽判定为 mAP50 多 seed 均值稳健提升；mAP50-95/crazing 完整记录不否决",
            },
            "baseline": {"gsdown": GSDOWN, "msdgs135eq": MSDGS},
            "experiments": {},
        }
    payload.setdefault("experiments", {})
    payload.setdefault("protocol", {})["seeds_requested"] = list(args.seeds)
    payload["protocol"]["epochs"] = args.epochs
    payload["protocol"]["imgsz"] = args.imgsz
    payload["protocol"]["batch"] = args.batch
    if "seed0" not in payload["experiments"]:
        payload["experiments"]["seed0"] = load_seed0(cfg)
    payload["summary"] = summarize(payload["experiments"])
    atomic_json(REPORT, payload)
    write_markdown(payload)
    return payload


def orchestrate(args) -> int:
    import fcntl

    PROJECT.mkdir(parents=True, exist_ok=True)
    lock_handle = LOCK.open("a+")
    try:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        raise RuntimeError("another PKI multiseed run is already active") from exc

    for required in (DATA, BASE_YAML, OFFICIAL_WEIGHTS, EVALUATOR, SEED0_REPORT):
        if not required.exists():
            raise FileNotFoundError(required)
    gpu_idle()
    cfg = generate_yaml()
    payload = load_or_initialize(cfg, args)
    completed = {
        int(item["seed"])
        for item in payload["experiments"].values()
        if item.get("status") == "done"
    }
    pending = [seed for seed in args.seeds if seed not in completed or args.force]
    save_status("running", pending[0] if pending else None, pending, "fresh PKI multiseed run")

    for index, seed in enumerate(pending):
        name = f"{CANDIDATE}_seed{seed}"
        key = f"seed{seed}"
        remaining = pending[index + 1 :]
        save_status("training", seed, remaining, f"training {name}")
        try:
            run_checked(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--worker-train",
                    "--cfg",
                    str(cfg),
                    "--name",
                    name,
                    "--epochs",
                    str(args.epochs),
                    "--imgsz",
                    str(args.imgsz),
                    "--batch",
                    str(args.batch),
                    "--seed",
                    str(seed),
                ]
            )
            weights = PROJECT / name / "weights" / "best.pt"
            independent = PROJECT / f"independent_seed{seed}_report.json"
            save_status("evaluating", seed, remaining, f"independent reload {name}")
            run_checked(
                [
                    sys.executable,
                    str(EVALUATOR),
                    "--weights",
                    str(weights),
                    "--data",
                    str(DATA),
                    "--project",
                    str(PROJECT),
                    "--name",
                    name,
                    "--output",
                    str(independent),
                    "--imgsz",
                    str(args.imgsz),
                    "--batch",
                    str(args.batch),
                ]
            )
            result = json.loads(independent.read_text(encoding="utf-8"))
            payload["experiments"][key] = normalize_result(
                result, seed, name, cfg, f"independent_seed{seed}_report.json"
            )
            print(
                "MULTISEED_RESULT",
                f"seed={seed}",
                f"test_mAP50={result['test']['map50']:.6f}",
                f"test_mAP50-95={result['test']['map50_95']:.6f}",
                f"crazing={result['test']['per_class']['crazing']['map50_95']:.6f}",
                flush=True,
            )
        except Exception as exc:  # noqa: BLE001
            traceback.print_exc()
            payload["experiments"][key] = {
                "status": "failed",
                "candidate": CANDIDATE,
                "name": name,
                "seed": seed,
                "cfg": str(cfg),
                "error": repr(exc),
                "failed_at": now(),
            }
            print("MULTISEED_JOB_FAILED", f"seed={seed}", repr(exc), flush=True)
        payload["summary"] = summarize(payload["experiments"])
        atomic_json(REPORT, payload)
        write_markdown(payload)

    payload["summary"] = summarize(payload["experiments"])
    payload["finished_at"] = now()
    failures = [
        item for item in payload["experiments"].values()
        if int(item.get("seed", -1)) in args.seeds and item.get("status") != "done"
    ]
    final_status = "failed" if failures else "done"
    atomic_json(REPORT, payload)
    write_markdown(payload)
    save_status(final_status, None, [], "multiseed run complete", failures=len(failures))
    print("MULTISEED_PKI_DONE", final_status, REPORT, flush=True)
    print("MULTISEED_SUMMARY", json.dumps(payload["summary"], ensure_ascii=False), flush=True)
    return 1 if failures else 0


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser()
    p.add_argument("--worker-train", action="store_true")
    p.add_argument("--cfg")
    p.add_argument("--name")
    p.add_argument("--epochs", type=int, default=250)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--batch", type=int, default=32)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--seeds", type=int, nargs="+", default=list(DEFAULT_SEEDS))
    p.add_argument("--force", action="store_true")
    return p


def main() -> int:
    args = parser().parse_args()
    if args.worker_train:
        if not args.cfg or not args.name:
            raise SystemExit("--worker-train requires --cfg and --name")
        return train_worker(args)
    return orchestrate(args)


if __name__ == "__main__":
    raise SystemExit(main())
