#!/usr/bin/env python
"""Train and independently evaluate the MSDGS Hybrid DCNv2 r50 candidate.

The candidate keeps 50% fixed-grid output channels and 50% bounded DCNv2
channels in every replaced inner 3x3 Bottleneck conv. It is initialized exactly
from the standard pretrained conv by output-channel slicing.

The authoritative verdict is a fresh-process reload of best.pt on val and test.
The requested three-metric target is the iter058 ideal gate:
    test mAP50             >= 0.738
    test mAP50-95          >= 0.402
    test crazing mAP50-95  >= 0.187
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
import traceback

import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_backbone_hybrid_dcnv2_e250"
PROJECT = ROOT / "runs_msdgs_backbone_hybrid_dcnv2_e250"
RUN_NAME = "msdgs_bb_p4_hybrid_dcnv2_r50"
STATUS = PROJECT / "status.json"
REPORT_JSON = PROJECT / "report.json"
REPORT_MD = PROJECT / "report.md"
LOCK = PROJECT / ".train.lock"
SCRIPT = Path(__file__).resolve()
EVALUATOR = ROOT / "eval_msdgs_candidate.py"

DEFORM_RATIO = 0.50
OFFSET_LIMIT = 1.0
MASK_SPAN = 0.50
MSDGS = {
    "test_map50": 0.7324113100352823,
    "test_map50_95": 0.3988372172746915,
    "test_crazing_map50_95": 0.1770695825201802,
}
IDEAL = {"test_map50": 0.738, "test_map50_95": 0.402, "test_crazing_map50_95": 0.187}


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def atomic_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(path)


def save_status(status: str, note: str = "", **extra) -> None:
    atomic_json(
        STATUS,
        {
            "status": status,
            "candidate": RUN_NAME,
            "note": note,
            "updated_at": now(),
            "pid": os.getpid(),
            "project": str(PROJECT),
            "report_json": str(REPORT_JSON),
            **extra,
        },
    )


def generate_yaml() -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    layer = doc["backbone"][6]
    assert layer[0] == -1 and layer[1] == 2 and layer[2] == "C3k2", layer
    assert layer[3][0] == 512 and layer[3][1] is True, layer
    layer[2] = "C3k2HybridDCNv2"
    layer[3] = [512, True, 0.5, False, 1, True, DEFORM_RATIO, OFFSET_LIMIT, MASK_SPAN]
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{RUN_NAME}.yaml"
    cfg.write_text(
        "# generated by train_msdgs_backbone_hybrid_dcnv2.py\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return cfg


def gpu_idle() -> None:
    result = subprocess.run(
        ["nvidia-smi", "--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader"],
        text=True, capture_output=True, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"nvidia-smi failed: {result.stderr.strip()}")
    if result.stdout.strip():
        raise RuntimeError(f"GPU already busy; refusing duplicate training:\n{result.stdout.strip()}")


def run_checked(command: list[str]) -> None:
    print("SUBPROCESS", " ".join(command), flush=True)
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"subprocess failed rc={result.returncode}: {' '.join(command)}")


def train_worker(args) -> int:
    from ultralytics import YOLO
    from ultralytics.nn.modules.yolo26_msdgs_backbone_hybrid_dcnv2 import (
        HybridDCNv2Unit,
        transfer_standard_to_hybrid_dcnv2,
    )

    target = PROJECT / RUN_NAME
    if target.exists():
        archive = target.with_name(target.name + f"_interrupted_{time.strftime('%Y%m%d_%H%M%S')}")
        shutil.move(str(target), str(archive))
        print("ARCHIVED_EXISTING_RUN", target, "->", archive, flush=True)

    # Avoid torchvision CPU deform_conv2d inside cosmetic model profiling.
    import ultralytics.utils.torch_utils as torch_utils
    torch_utils.get_flops = lambda *a, **k: 0.0
    torch_utils.get_flops_with_torch_profiler = lambda *a, **k: 0.0

    model = YOLO(args.cfg, task="detect").load(str(OFFICIAL_WEIGHTS))
    baseline_std = YOLO(str(BASE_YAML), task="detect").load(str(OFFICIAL_WEIGHTS))
    transferred = transfer_standard_to_hybrid_dcnv2(model.model, baseline_std.model.state_dict())
    del baseline_std

    layer6 = model.model.model[6]
    head = model.model.model[-1]
    assert type(layer6).__name__ == "C3k2HybridDCNv2"
    assert type(model.model.model[8]).__name__ == "C3k2"
    assert type(model.model.model[10]).__name__ == "C2PSA"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    detect_channels = tuple(int(t[0].conv.in_channels) for t in head.cv2)
    assert detect_channels == (64, 128, 256), detect_channels
    units = [m for m in layer6.modules() if isinstance(m, HybridDCNv2Unit)]
    assert units and transferred == len(units) == layer6.hybrid_units
    assert all(u.c_regular == u.c_deform for u in units)
    params_unfused = int(sum(p.numel() for p in model.model.parameters()))
    print(
        "HYBRID_INIT",
        f"units={len(units)}",
        f"regular={units[0].c_regular}",
        f"deform={units[0].c_deform}",
        f"offset_limit={units[0].offset_limit}",
        f"mask_span={units[0].mask_span}",
        f"transferred={transferred}",
        flush=True,
    )

    model.train(
        data=str(DATA), epochs=args.epochs, imgsz=args.imgsz, batch=args.batch,
        workers=args.workers, seed=args.seed, device=0,
        project=str(PROJECT), name=RUN_NAME, exist_ok=True,
        patience=max(args.epochs, 250), cache=False, resume=False, verbose=True,
    )
    weights = target / "weights" / "best.pt"
    if not weights.exists():
        raise FileNotFoundError(weights)
    atomic_json(
        target / "train_worker.json",
        {
            "status": "done", "candidate": RUN_NAME, "seed": args.seed,
            "cfg": args.cfg, "weights": str(weights), "params_unfused": params_unfused,
            "hybrid_units": len(units), "deform_ratio": DEFORM_RATIO,
            "offset_limit": OFFSET_LIMIT, "mask_span": MASK_SPAN,
            "finished_at": now(),
        },
    )
    print("TRAIN_WORKER_DONE", weights, flush=True)
    return 0


def gate(report: dict) -> dict:
    test = report["test"]
    crazing = test["per_class"]["crazing"]["map50_95"]
    deltas = {
        "map50": test["map50"] - MSDGS["test_map50"],
        "map50_95": test["map50_95"] - MSDGS["test_map50_95"],
        "crazing_map50_95": crazing - MSDGS["test_crazing_map50_95"],
    }
    owner_checks = {
        "test_map50_gt_msdgs": test["map50"] > MSDGS["test_map50"],
        "test_map50_95_ge_msdgs": test["map50_95"] >= MSDGS["test_map50_95"],
        "test_crazing_map50_95_gt_msdgs": crazing > MSDGS["test_crazing_map50_95"],
    }
    ideal_checks = {
        "test_map50_ge_0.738": test["map50"] >= IDEAL["test_map50"],
        "test_map50_95_ge_0.402": test["map50_95"] >= IDEAL["test_map50_95"],
        "test_crazing_map50_95_ge_0.187": crazing >= IDEAL["test_crazing_map50_95"],
    }
    return {
        "owner_gate_pass": all(owner_checks.values()),
        "owner_checks": owner_checks,
        "ideal_gate_pass": all(ideal_checks.values()),
        "ideal_checks": ideal_checks,
        "deltas_vs_msdgs": deltas,
    }


def write_report(payload: dict) -> None:
    atomic_json(REPORT_JSON, payload)
    item = payload.get("experiment", {})
    lines = [
        "# MSDGS Backbone P4 Hybrid DCNv2 r50 seed0 报告", "",
        "保护机制：50% 规则网格通道 + 50% 有界 DCNv2 通道；offset∈[-1,1]，mask∈[0.5,1.5]。",
        "固定协议：250 epochs / imgsz=640 / batch=32 / seed0 / cache=False / yolo26n.pt。",
        "最终真值由独立新进程重新加载磁盘 `best.pt`，分别评测 val/test。", "",
    ]
    if item.get("status") == "done":
        test, result_gate = item["test"], item["gate"]
        crazing = test["per_class"]["crazing"]["map50_95"]
        lines += [
            "| test mAP50 | test mAP50-95 | crazing mAP50-95 | fused 参数 | GFLOPs | Owner gate | 理想三指标 |",
            "|---:|---:|---:|---:|---:|---|---|",
            f"| {test['map50']:.6f} | {test['map50_95']:.6f} | {crazing:.6f} | {item.get('params_fused')} | {item.get('gflops')} | {'PASS' if result_gate['owner_gate_pass'] else 'FAIL'} | {'PASS' if result_gate['ideal_gate_pass'] else 'FAIL'} |",
            "", "## 相对 MSDGS 与 gate", "", "```json",
            json.dumps(result_gate, indent=2, ensure_ascii=False), "```",
        ]
    else:
        lines += ["当前状态：`" + item.get("status", "pending") + "`。"]
    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def orchestrate(args) -> int:
    import fcntl

    PROJECT.mkdir(parents=True, exist_ok=True)
    lock_handle = LOCK.open("a+")
    try:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        raise RuntimeError("another Hybrid DCNv2 run is already active") from exc
    for required in (DATA, BASE_YAML, OFFICIAL_WEIGHTS, EVALUATOR):
        if not required.exists():
            raise FileNotFoundError(required)
    gpu_idle()
    cfg = generate_yaml()
    payload = {
        "schema_version": 1,
        "started_at": now(),
        "candidate": RUN_NAME,
        "protocol": {
            "epochs": args.epochs, "imgsz": args.imgsz, "batch": args.batch, "seed": args.seed,
            "cache": False, "resume": False, "init_weights": str(OFFICIAL_WEIGHTS),
            "data": str(DATA), "base": str(BASE_YAML),
            "hybrid": {
                "deform_ratio": DEFORM_RATIO,
                "regular_ratio": 1.0 - DEFORM_RATIO,
                "offset_limit": OFFSET_LIMIT,
                "mask_span": MASK_SPAN,
            },
            "final_eval": "independent subprocess reloads best.pt for val and test",
        },
        "baseline": MSDGS,
        "ideal": IDEAL,
        "experiment": {"status": "training", "cfg": str(cfg)},
    }
    write_report(payload)
    try:
        save_status("training", "fresh train; resume disabled", cfg=str(cfg))
        run_checked([
            sys.executable, str(SCRIPT), "--worker-train", "--cfg", str(cfg),
            "--epochs", str(args.epochs), "--imgsz", str(args.imgsz),
            "--batch", str(args.batch), "--workers", str(args.workers), "--seed", str(args.seed),
        ])
        weights = PROJECT / RUN_NAME / "weights" / "best.pt"
        independent = PROJECT / "independent_seed0_report.json"
        save_status("evaluating", "fresh process reloads best.pt", weights=str(weights))
        run_checked([
            sys.executable, str(EVALUATOR), "--weights", str(weights), "--data", str(DATA),
            "--project", str(PROJECT), "--name", RUN_NAME, "--output", str(independent),
            "--imgsz", str(args.imgsz), "--batch", str(args.batch),
        ])
        result = json.loads(independent.read_text(encoding="utf-8"))
        result.update({"status": "done", "candidate": RUN_NAME, "cfg": str(cfg), "gate": gate(result)})
        payload["experiment"] = result
        payload["finished_at"] = now()
        write_report(payload)
        save_status(
            "done", "seed0 train and independent eval complete",
            owner_gate_pass=result["gate"]["owner_gate_pass"],
            ideal_gate_pass=result["gate"]["ideal_gate_pass"],
        )
        print("MSDGS_BACKBONE_HYBRID_DCNV2_DONE", REPORT_JSON, flush=True)
        return 0
    except Exception as exc:  # noqa: BLE001
        traceback.print_exc()
        payload["experiment"] = {"status": "failed", "cfg": str(cfg), "error": repr(exc), "failed_at": now()}
        write_report(payload)
        save_status("failed", repr(exc))
        raise


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser()
    p.add_argument("--worker-train", action="store_true")
    p.add_argument("--cfg")
    p.add_argument("--epochs", type=int, default=250)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--batch", type=int, default=32)
    p.add_argument("--workers", type=int, default=8)
    p.add_argument("--seed", type=int, default=0)
    return p


def main() -> int:
    args = parser().parse_args()
    if args.worker_train:
        if not args.cfg:
            raise SystemExit("--worker-train requires --cfg")
        return train_worker(args)
    return orchestrate(args)


if __name__ == "__main__":
    raise SystemExit(main())
