#!/usr/bin/env python
"""Train the MSDGS-line SADGS candidate and independently evaluate best.pt.

SADGS = MSDGS 的单变量消融：把 neck 里 4 个 MSDGS(各向同性 dilations=(1,3,5))
换成 SADGS(各向同性 (1,3) + 追加 1 条各向异性 strip 分支 k)。通道结构对齐
(3 分支均等)，总预算对齐 MSDGS ~1.777M。backbone/Detect/end2end/reg_max/损失/
训练协议全部不变，从 yolo26n.pt 迁移。

底座 = MSDGS135eq 主线（owner 指定），不是 gsdown。判定唯一真值由独立新进程
重新加载磁盘 best.pt 评测 val/test（train-process 数值虚高，绝不作判据）。
Owner gate = 三项同时高于 MSDGS 基线：
    test mAP50            > 0.7324113100
    test mAP50-95         >= 0.3988372173
    test crazing mAP50-95 > 0.1770695825
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
import traceback

import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_sadgs_msdgs_e250"
PROJECT = ROOT / "runs_sadgs_msdgs_e250"
RUN_NAME = "sadgs_msdgs_13s7"
STATUS = PROJECT / "status.json"
REPORT_JSON = PROJECT / "report.json"
REPORT_MD = PROJECT / "report.md"
LOCK = PROJECT / ".train.lock"
SCRIPT = Path(__file__).resolve()
EVALUATOR = ROOT / "eval_msdgs_candidate.py"

# SADGS 各向异性条带分支的核长（k=7：strip 1x7 + 7x1 depthwise 参数量 ~= 3x3 dilated depthwise，
# 通道均等三分，与 MSDGS (1,3,5) 完全对齐的单变量对照）。
STRIP_K = 7
ISO_DILATIONS = [1, 3]

MSDGS = {
    "test_map50": 0.7324113100352823,
    "test_map50_95": 0.3988372172746915,
    "test_crazing_map50_95": 0.1770695825201802,
}
IDEAL = {"test_map50": 0.738, "test_map50_95": 0.402, "test_crazing_map50_95": 0.187}


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def atomic_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(path)


def save_status(status: str, note: str = "", **extra) -> None:
    atomic_json(
        STATUS,
        {
            "status": status,
            "candidate": RUN_NAME,
            "note": note,
            "updated_at": now(),
            "pid": os.getpid(),
            "project": str(PROJECT),
            "report_json": str(REPORT_JSON),
            **extra,
        },
    )


def generate_yaml() -> Path:
    """把 neck 里 4 个 MSDGS 块单变量换成 SADGS(iso=(1,3) + strip k)。backbone 一字不动。"""
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "MSDGS":
            c2 = block[3][0]
            # MSDGS args=[c2, shortcut, g, e, dilations, fracs]
            # SADGS args=[c2, shortcut, g, e, iso_dilations, strip_k, fracs]
            block[2] = "SADGS"
            n_iso = len(ISO_DILATIONS)
            fracs = [1] * (n_iso + 1)  # iso 分支 + 1 条 strip，通道均等
            block[3] = [c2, True, 1, 0.5, list(ISO_DILATIONS), int(STRIP_K), fracs]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 MSDGS in neck, got {n_swapped}"
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{RUN_NAME}.yaml"
    cfg.write_text(
        "# generated by train_sadgs_msdgs.py (MSDGS-line SADGS single-variable ablation)\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return cfg


def gpu_idle() -> None:
    result = subprocess.run(
        ["nvidia-smi", "--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader"],
        text=True, capture_output=True, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"nvidia-smi failed: {result.stderr.strip()}")
    if result.stdout.strip():
        raise RuntimeError(f"GPU already busy; refusing duplicate training:\n{result.stdout.strip()}")


def run_checked(command: list[str]) -> None:
    print("SUBPROCESS", " ".join(command), flush=True)
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"subprocess failed rc={result.returncode}: {' '.join(command)}")


def train_worker(args) -> int:
    from ultralytics import YOLO

    target = PROJECT / RUN_NAME
    if target.exists():
        archive = target.with_name(target.name + f"_interrupted_{time.strftime('%Y%m%d_%H%M%S')}")
        shutil.move(str(target), str(archive))
        print(f"ARCHIVED old run dir -> {archive}", flush=True)

    model = YOLO(str(args.cfg), task="detect").load(str(OFFICIAL_WEIGHTS))
    params_unfused = int(sum(p.numel() for p in model.model.parameters()))
    print(f"PARAMS_UNFUSED {params_unfused}", flush=True)

    model.train(
        data=str(DATA),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        workers=args.workers,
        seed=args.seed,
        device=0,
        project=str(PROJECT),
        name=RUN_NAME,
        exist_ok=True,
        patience=max(args.epochs, 250),
        cache=False,
        resume=False,
        verbose=True,
    )
    weights = target / "weights" / "best.pt"
    if not weights.exists():
        raise FileNotFoundError(weights)
    atomic_json(
        target / "train_worker.json",
        {
            "status": "done", "candidate": RUN_NAME, "seed": args.seed,
            "cfg": args.cfg, "weights": str(weights), "params_unfused": params_unfused,
            "finished_at": now(),
        },
    )
    print("TRAIN_WORKER_DONE", weights, flush=True)
    return 0


def gate(report: dict) -> dict:
    test = report["test"]
    crazing = test["per_class"]["crazing"]["map50_95"]
    deltas = {
        "map50": test["map50"] - MSDGS["test_map50"],
        "map50_95": test["map50_95"] - MSDGS["test_map50_95"],
        "crazing_map50_95": crazing - MSDGS["test_crazing_map50_95"],
    }
    owner_checks = {
        "test_map50_gt_msdgs": test["map50"] > MSDGS["test_map50"],
        "test_map50_95_ge_msdgs": test["map50_95"] >= MSDGS["test_map50_95"],
        "test_crazing_map50_95_gt_msdgs": crazing > MSDGS["test_crazing_map50_95"],
    }
    ideal_checks = {
        "test_map50_ge_0.738": test["map50"] >= IDEAL["test_map50"],
        "test_map50_95_ge_0.402": test["map50_95"] >= IDEAL["test_map50_95"],
        "test_crazing_map50_95_ge_0.187": crazing >= IDEAL["test_crazing_map50_95"],
    }
    return {
        "owner_gate_pass": all(owner_checks.values()),
        "owner_checks": owner_checks,
        "ideal_gate_pass": all(ideal_checks.values()),
        "ideal_checks": ideal_checks,
        "deltas_vs_msdgs": deltas,
    }


def write_report(payload: dict) -> None:
    atomic_json(REPORT_JSON, payload)
    item = payload.get("experiment", {})
    lines = [
        "# MSDGS-line SADGS（各向异性条带解耦 neck）seed0 报告", "",
        "SADGS = MSDGS 单变量消融：neck 4×MSDGS(d1,d3,d5) → SADGS(d1,d3,strip)。",
        "固定协议：250 epochs / imgsz=640 / batch=32 / seed0 / cache=False / yolo26n.pt。",
        "最终真值由独立新进程重新加载磁盘 `best.pt`，分别评测 val/test。", "",
    ]
    if item.get("status") == "done":
        test, result_gate = item["test"], item["gate"]
        crazing = test["per_class"]["crazing"]["map50_95"]
        lines += [
            "| test mAP50 | test mAP50-95 | crazing mAP50-95 | fused 参数 | GFLOPs | Owner gate |",
            "|---:|---:|---:|---:|---:|---|",
            f"| {test['map50']:.6f} | {test['map50_95']:.6f} | {crazing:.6f} | {item.get('params_fused')} | {item.get('gflops')} | {'PASS' if result_gate['owner_gate_pass'] else 'FAIL'} |",
            "", "## 相对 MSDGS", "", "```json",
            json.dumps(result_gate, indent=2, ensure_ascii=False), "```",
        ]
    else:
        lines += ["当前状态：`" + item.get("status", "pending") + "`。"]
    REPORT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def orchestrate(args) -> int:
    import fcntl

    PROJECT.mkdir(parents=True, exist_ok=True)
    lock_handle = LOCK.open("a+")
    try:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        raise RuntimeError("another SADGS MSDGS-line run is already active") from exc
    for required in (DATA, BASE_YAML, OFFICIAL_WEIGHTS, EVALUATOR):
        if not required.exists():
            raise FileNotFoundError(required)
    gpu_idle()
    cfg = generate_yaml()
    payload = {
        "schema_version": 1,
        "started_at": now(),
        "candidate": RUN_NAME,
        "protocol": {
            "epochs": args.epochs, "imgsz": args.imgsz, "batch": args.batch, "seed": args.seed,
            "cache": False, "resume": False, "init_weights": str(OFFICIAL_WEIGHTS),
            "data": str(DATA), "base": str(BASE_YAML),
            "sadgs": {"iso_dilations": ISO_DILATIONS, "strip_k": STRIP_K},
            "final_eval": "independent subprocess reloads best.pt for val and test",
        },
        "baseline": MSDGS,
        "ideal": IDEAL,
        "experiment": {"status": "training", "cfg": str(cfg)},
    }
    write_report(payload)
    try:
        save_status("training", "fresh train; resume disabled", cfg=str(cfg))
        run_checked([
            sys.executable, str(SCRIPT), "--worker-train", "--cfg", str(cfg),
            "--epochs", str(args.epochs), "--imgsz", str(args.imgsz),
            "--batch", str(args.batch), "--seed", str(args.seed),
        ])
        weights = PROJECT / RUN_NAME / "weights" / "best.pt"
        independent = PROJECT / "independent_seed0_report.json"
        save_status("evaluating", "fresh process reloads best.pt", weights=str(weights))
        run_checked([
            sys.executable, str(EVALUATOR), "--weights", str(weights), "--data", str(DATA),
            "--project", str(PROJECT), "--name", RUN_NAME, "--output", str(independent),
            "--imgsz", str(args.imgsz), "--batch", str(args.batch),
        ])
        result = json.loads(independent.read_text(encoding="utf-8"))
        result.update({"status": "done", "candidate": RUN_NAME, "cfg": str(cfg), "gate": gate(result)})
        payload["experiment"] = result
        payload["finished_at"] = now()
        write_report(payload)
        save_status(
            "done", "seed0 train and independent eval complete",
            owner_gate_pass=result["gate"]["owner_gate_pass"],
        )
        print("SADGS_MSDGS_DONE", REPORT_JSON, flush=True)
        return 0
    except Exception as exc:  # noqa: BLE001
        traceback.print_exc()
        payload["experiment"] = {
            "status": "failed", "cfg": str(cfg), "error": repr(exc), "failed_at": now()
        }
        write_report(payload)
        save_status("failed", repr(exc))
        raise


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser()
    p.add_argument("--worker-train", action="store_true")
    p.add_argument("--cfg")
    p.add_argument("--epochs", type=int, default=250)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--batch", type=int, default=32)
    p.add_argument("--workers", type=int, default=8)
    p.add_argument("--seed", type=int, default=0)
    return p


def main() -> int:
    args = parser().parse_args()
    if args.worker_train:
        if not args.cfg:
            raise SystemExit("--worker-train requires --cfg")
        return train_worker(args)
    return orchestrate(args)


if __name__ == "__main__":
    raise SystemExit(main())
