#!/usr/bin/env python
"""Run MSDGS Backbone P4 DCNv2 on seeds 1/2/3 and independently evaluate each best.pt.

This is a stability follow-up for Iteration 058. The architecture and training
protocol are identical to ``msdgs_bb_p4_dcnv2`` seed0; only ``seed`` and the run
name change. Every final metric comes from a fresh evaluator subprocess that
reloads the checkpoint from disk.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import statistics
import subprocess
import sys
import time
import traceback

import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_backbone_dcnv2_multiseed_e250"
PROJECT = ROOT / "runs_msdgs_backbone_dcnv2_multiseed_e250"
STATUS = PROJECT / "status.json"
REPORT = PROJECT / "report.json"
REPORT_MD = PROJECT / "report.md"
LOCK = PROJECT / ".train.lock"
SCRIPT = Path(__file__).resolve()
EVALUATOR = ROOT / "eval_msdgs_candidate.py"
SEED0_REPORT = ROOT / "runs_msdgs_backbone_dcnv2_e250" / "independent_seed0_report.json"
CANDIDATE = "msdgs_bb_p4_dcnv2"
DEFAULT_SEEDS = (1, 2, 3)

MSDGS = {
    "test_map50": 0.7324113100352823,
    "test_map50_95": 0.3988372172746915,
    "test_crazing_map50_95": 0.1770695825201802,
}
IDEAL = {
    "test_map50": 0.738,
    "test_map50_95": 0.402,
    "test_crazing_map50_95": 0.187,
}


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def atomic_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(path)


def save_status(status: str, current=None, pending=None, note: str = "", **extra) -> None:
    atomic_json(
        STATUS,
        {
            "status": status,
            "candidate": CANDIDATE,
            "current": current,
            "pending": list(pending or []),
            "note": note,
            "updated_at": now(),
            "pid": os.getpid(),
            "project": str(PROJECT),
            "report": str(REPORT),
            **extra,
        },
    )


def generate_yaml() -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    layer = doc["backbone"][6]
    assert layer[0] == -1 and layer[1] == 2 and layer[2] == "C3k2", layer
    assert layer[3][0] == 512 and layer[3][1] is True, layer
    layer[2] = "C3k2DCNv2"
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{CANDIDATE}.yaml"
    cfg.write_text(
        "# generated by train_multiseed_msdgs_backbone_dcnv2.py\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return cfg


def gpu_idle() -> None:
    result = subprocess.run(
        ["nvidia-smi", "--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader"],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"nvidia-smi failed: {result.stderr.strip()}")
    if result.stdout.strip():
        raise RuntimeError(f"GPU already busy; refusing duplicate training:\n{result.stdout.strip()}")


def run_checked(command: list[str]) -> None:
    print("SUBPROCESS", " ".join(command), flush=True)
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"subprocess failed rc={result.returncode}: {' '.join(command)}")


def archive_partial(target: Path) -> None:
    if not target.exists():
        return
    archive = target.with_name(target.name + f"_interrupted_{time.strftime('%Y%m%d_%H%M%S')}")
    shutil.move(str(target), str(archive))
    print("ARCHIVED_EXISTING_RUN", target, "->", archive, flush=True)


def train_worker(args) -> int:
    # Avoid torchvision 0.18 CPU deform_conv2d SIGSEGV in cosmetic FLOPs profiling.
    import ultralytics.utils.torch_utils as torch_utils

    torch_utils.get_flops = lambda *a, **k: 0.0
    torch_utils.get_flops_with_torch_profiler = lambda *a, **k: 0.0

    from ultralytics import YOLO
    from ultralytics.nn.modules.yolo26_msdgs_backbone_dcnv2 import (
        DCNv2Unit,
        transfer_standard_to_dcnv2,
    )

    target = PROJECT / args.name
    archive_partial(target)
    print("TRAIN_WORKER_START", os.getpid(), args.name, f"seed={args.seed}", flush=True)
    model = YOLO(args.cfg, task="detect").load(str(OFFICIAL_WEIGHTS))
    baseline_std = YOLO(str(BASE_YAML), task="detect").load(str(OFFICIAL_WEIGHTS))
    transferred = transfer_standard_to_dcnv2(model.model, baseline_std.model.state_dict())
    del baseline_std

    layer6 = model.model.model[6]
    head = model.model.model[-1]
    deform_units = sum(1 for module in layer6.modules() if isinstance(module, DCNv2Unit))
    assert type(layer6).__name__ == "C3k2DCNv2"
    assert transferred == deform_units and deform_units > 0, (transferred, deform_units)
    assert type(model.model.model[8]).__name__ == "C3k2"
    assert type(model.model.model[10]).__name__ == "C2PSA"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    assert tuple(int(t[0].conv.in_channels) for t in head.cv2) == (64, 128, 256)

    params_unfused = int(sum(p.numel() for p in model.model.parameters()))
    model.train(
        data=str(DATA),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        workers=8,
        seed=args.seed,
        device=0,
        project=str(PROJECT),
        name=args.name,
        exist_ok=True,
        patience=max(args.epochs, 250),
        cache=False,
        resume=False,
        verbose=True,
    )
    weights = target / "weights" / "best.pt"
    if not weights.is_file():
        raise FileNotFoundError(weights)
    atomic_json(
        target / "train_worker.json",
        {
            "status": "done",
            "candidate": CANDIDATE,
            "name": args.name,
            "seed": args.seed,
            "cfg": args.cfg,
            "weights": str(weights),
            "params_unfused": params_unfused,
            "deform_units": deform_units,
            "finished_at": now(),
        },
    )
    print("TRAIN_WORKER_DONE", args.name, weights, flush=True)
    return 0


def gate(result: dict) -> dict:
    test = result["test"]
    crazing = test["per_class"]["crazing"]["map50_95"]
    owner_checks = {
        "test_map50_gt_msdgs": test["map50"] > MSDGS["test_map50"],
        "test_map50_95_ge_msdgs": test["map50_95"] >= MSDGS["test_map50_95"],
        "test_crazing_map50_95_gt_msdgs": crazing > MSDGS["test_crazing_map50_95"],
    }
    ideal_checks = {
        "test_map50_ge_0.738": test["map50"] >= IDEAL["test_map50"],
        "test_map50_95_ge_0.402": test["map50_95"] >= IDEAL["test_map50_95"],
        "test_crazing_map50_95_ge_0.187": crazing >= IDEAL["test_crazing_map50_95"],
    }
    return {
        "owner_gate_pass": all(owner_checks.values()),
        "owner_checks": owner_checks,
        "ideal_gate_pass": all(ideal_checks.values()),
        "ideal_checks": ideal_checks,
        "deltas_vs_msdgs": {
            "map50": test["map50"] - MSDGS["test_map50"],
            "map50_95": test["map50_95"] - MSDGS["test_map50_95"],
            "crazing_map50_95": crazing - MSDGS["test_crazing_map50_95"],
        },
    }


def normalize_result(result: dict, seed: int, name: str, cfg: Path, source: str) -> dict:
    normalized = dict(result)
    normalized.update(
        {
            "status": "done",
            "candidate": CANDIDATE,
            "name": name,
            "seed": seed,
            "cfg": str(cfg),
            "source": source,
        }
    )
    normalized["gate"] = gate(normalized)
    return normalized


def metric_stats(values: list[float]) -> dict:
    return {
        "n": len(values),
        "mean": statistics.mean(values),
        "std": statistics.stdev(values) if len(values) > 1 else 0.0,
        "min": min(values),
        "max": max(values),
        "range": max(values) - min(values),
    }


def summarize(experiments: dict) -> dict:
    done = sorted(
        (item for item in experiments.values() if item.get("status") == "done"),
        key=lambda item: int(item["seed"]),
    )
    if not done:
        return {"n": 0}
    map50 = [item["test"]["map50"] for item in done]
    map5095 = [item["test"]["map50_95"] for item in done]
    crazing = [item["test"]["per_class"]["crazing"]["map50_95"] for item in done]
    seeds = [int(item["seed"]) for item in done]
    return {
        "n": len(done),
        "seeds": seeds,
        "test_map50": metric_stats(map50),
        "test_map50_95": metric_stats(map5095),
        "test_crazing_map50_95": metric_stats(crazing),
        "ideal_pass_count": sum(bool(item["gate"]["ideal_gate_pass"]) for item in done),
        "owner_pass_count": sum(bool(item["gate"]["owner_gate_pass"]) for item in done),
        "per_metric_ideal_pass_count": {
            "test_map50": sum(value >= IDEAL["test_map50"] for value in map50),
            "test_map50_95": sum(value >= IDEAL["test_map50_95"] for value in map5095),
            "test_crazing_map50_95": sum(value >= IDEAL["test_crazing_map50_95"] for value in crazing),
        },
        "all_four_ideal_pass": len(done) == 4 and all(item["gate"]["ideal_gate_pass"] for item in done),
        "all_seed123_ideal_pass": all(
            item["gate"]["ideal_gate_pass"] for item in done if int(item["seed"]) in DEFAULT_SEEDS
        ) and all(seed in seeds for seed in DEFAULT_SEEDS),
    }


def write_markdown(payload: dict) -> None:
    experiments = payload.get("experiments", {})
    lines = [
        "# MSDGS Backbone P4 DCNv2 多 seed 稳定性报告",
        "",
        "固定协议：250 epochs / imgsz=640 / batch=32 / cache=False / resume=False / yolo26n.pt。",
        "所有指标由独立新进程从磁盘重载各 seed 的 best.pt 后评测。",
        "",
        "| seed | test mAP50 | test mAP50-95 | crazing mAP50-95 | 理想三项同时通过 |",
        "|---:|---:|---:|---:|---|",
    ]
    for item in sorted(experiments.values(), key=lambda x: int(x.get("seed", 999))):
        if item.get("status") != "done":
            lines.append(f"| {item.get('seed')} | - | - | - | {item.get('status', 'pending')} |")
            continue
        test = item["test"]
        crazing = test["per_class"]["crazing"]["map50_95"]
        lines.append(
            f"| {item['seed']} | {test['map50']:.6f} | {test['map50_95']:.6f} | "
            f"{crazing:.6f} | {'PASS' if item['gate']['ideal_gate_pass'] else 'FAIL'} |"
        )
    lines += ["", "## 汇总", "", "```json", json.dumps(payload.get("summary", {}), indent=2, ensure_ascii=False), "```", ""]
    REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


def load_or_initialize(cfg: Path, args) -> dict:
    if REPORT.exists():
        payload = json.loads(REPORT.read_text(encoding="utf-8"))
    else:
        payload = {
            "schema_version": 1,
            "candidate": CANDIDATE,
            "started_at": now(),
            "protocol": {
                "epochs": args.epochs,
                "imgsz": args.imgsz,
                "batch": args.batch,
                "seeds_requested": list(args.seeds),
                "cache": False,
                "resume": False,
                "init_weights": str(OFFICIAL_WEIGHTS),
                "data": str(DATA),
                "final_eval": "independent subprocess reloads each best.pt for val and test",
            },
            "baseline": MSDGS,
            "ideal": IDEAL,
            "experiments": {},
        }
    payload.setdefault("experiments", {})
    payload.setdefault("protocol", {})["seeds_requested"] = list(args.seeds)
    payload["protocol"]["epochs"] = args.epochs
    payload["protocol"]["imgsz"] = args.imgsz
    payload["protocol"]["batch"] = args.batch
    if "seed0" not in payload["experiments"]:
        seed0 = json.loads(SEED0_REPORT.read_text(encoding="utf-8"))
        payload["experiments"]["seed0"] = normalize_result(
            seed0, 0, CANDIDATE, cfg, "Iteration 058 independent_seed0_report.json"
        )
    payload["summary"] = summarize(payload["experiments"])
    atomic_json(REPORT, payload)
    write_markdown(payload)
    return payload


def orchestrate(args) -> int:
    import fcntl

    PROJECT.mkdir(parents=True, exist_ok=True)
    lock_handle = LOCK.open("a+")
    try:
        fcntl.flock(lock_handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        raise RuntimeError("another DCNv2 multiseed run is already active") from exc

    for required in (DATA, BASE_YAML, OFFICIAL_WEIGHTS, EVALUATOR, SEED0_REPORT):
        if not required.exists():
            raise FileNotFoundError(required)
    gpu_idle()
    cfg = generate_yaml()
    payload = load_or_initialize(cfg, args)
    completed = {
        int(item["seed"])
        for item in payload["experiments"].values()
        if item.get("status") == "done"
    }
    pending = [seed for seed in args.seeds if seed not in completed or args.force]
    save_status("running", pending[0] if pending else None, pending, "fresh multiseed stability run")

    for index, seed in enumerate(pending):
        name = f"{CANDIDATE}_seed{seed}"
        key = f"seed{seed}"
        remaining = pending[index + 1 :]
        save_status("training", seed, remaining, f"training {name}")
        try:
            run_checked(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--worker-train",
                    "--cfg",
                    str(cfg),
                    "--name",
                    name,
                    "--epochs",
                    str(args.epochs),
                    "--imgsz",
                    str(args.imgsz),
                    "--batch",
                    str(args.batch),
                    "--seed",
                    str(seed),
                ]
            )
            weights = PROJECT / name / "weights" / "best.pt"
            independent = PROJECT / f"independent_seed{seed}_report.json"
            save_status("evaluating", seed, remaining, f"independent reload {name}")
            run_checked(
                [
                    sys.executable,
                    str(EVALUATOR),
                    "--weights",
                    str(weights),
                    "--data",
                    str(DATA),
                    "--project",
                    str(PROJECT),
                    "--name",
                    name,
                    "--output",
                    str(independent),
                    "--imgsz",
                    str(args.imgsz),
                    "--batch",
                    str(args.batch),
                ]
            )
            result = json.loads(independent.read_text(encoding="utf-8"))
            payload["experiments"][key] = normalize_result(
                result, seed, name, cfg, f"independent_seed{seed}_report.json"
            )
            print(
                "MULTISEED_RESULT",
                f"seed={seed}",
                f"test_mAP50={result['test']['map50']:.6f}",
                f"test_mAP50-95={result['test']['map50_95']:.6f}",
                f"crazing={result['test']['per_class']['crazing']['map50_95']:.6f}",
                flush=True,
            )
        except Exception as exc:  # noqa: BLE001
            traceback.print_exc()
            payload["experiments"][key] = {
                "status": "failed",
                "candidate": CANDIDATE,
                "name": name,
                "seed": seed,
                "cfg": str(cfg),
                "error": repr(exc),
                "failed_at": now(),
            }
            print("MULTISEED_JOB_FAILED", f"seed={seed}", repr(exc), flush=True)
        payload["summary"] = summarize(payload["experiments"])
        atomic_json(REPORT, payload)
        write_markdown(payload)

    payload["summary"] = summarize(payload["experiments"])
    payload["finished_at"] = now()
    failures = [
        item for item in payload["experiments"].values()
        if int(item.get("seed", -1)) in args.seeds and item.get("status") != "done"
    ]
    final_status = "failed" if failures else "done"
    atomic_json(REPORT, payload)
    write_markdown(payload)
    save_status(final_status, None, [], "multiseed run complete", failures=len(failures))
    print("MULTISEED_DCNV2_DONE", final_status, REPORT, flush=True)
    print("MULTISEED_SUMMARY", json.dumps(payload["summary"], ensure_ascii=False), flush=True)
    return 1 if failures else 0


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser()
    p.add_argument("--worker-train", action="store_true")
    p.add_argument("--cfg")
    p.add_argument("--name")
    p.add_argument("--epochs", type=int, default=250)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--batch", type=int, default=32)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--seeds", type=int, nargs="+", default=list(DEFAULT_SEEDS))
    p.add_argument("--force", action="store_true")
    return p


def main() -> int:
    args = parser().parse_args()
    if args.worker_train:
        if not args.cfg or not args.name:
            raise SystemExit("--worker-train requires --cfg and --name")
        return train_worker(args)
    return orchestrate(args)


if __name__ == "__main__":
    raise SystemExit(main())
