#!/usr/bin/env python
"""iter35：各向异性条带解耦 neck（SADGS）叠到 vovgscsp_gsdown，250e 串行对照训练。

正交新轴 = 方向性/各向异性（详见 install_sadgs_module.py 的设计动机）：
- MSDGS135eq=(d1,d3,d5) 是唯一站住的解耦底座（-8.2% 参数、n=4 精度持平 0.393）。
- SADGS 把最大空洞 d5（各向同性）换成条带分支（1xk + kx1，各向异性长程），
  给带状/细长缺陷（rolled-in/scratches，混淆矩阵指出的可恢复空间）方向上下文，
  且比已证伪的 global 池化少伤无主方向的 crazing。

候选（全部 gsdown head 4×VoVGSCSP → SADGS，从 yolo26n.pt 迁移，保 end2end/reg_max=1）：
- gsdown_sadgs_13s7   : dilations=(1,3), strip_k=7, fracs=(1,1,1)   主候选：d5→strip(k=7)，三分支均等
- gsdown_sadgs_13s11  : dilations=(1,3), strip_k=11, fracs=(1,1,1)  更长条带（消融 strip_k）
- gsdown_sadgs_135s7  : dilations=(1,3,5), strip_k=7, fracs=(1,1,1,1) 保 d5 再加 strip（四分支，消融是否该保留 d5）

对照锚：
- gsdown 独立真值 test mAP50 0.7338 / mAP50-95 0.4018 / fused 1.936M。
- MSDGS135eq 独立真值 test 0.732411 / 0.398837 / fused 1.777M（-8.2%）。
判定：test mAP50-95 真值稳定 > 0.4018（且保住轻量）→ 候选进 n=4 多 seed 配对复核。
     单 seed 破线只算候选（13hf 教训：单 seed 不算结论）。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_gsconv_modules.py          # GSConv/VoVGSCSP（gsdown head 必需）
    python install_sadgs_module.py            # SADGS（本轮）
    python -u train_sadgs_gsdown.py

输出：
- runs_sadgs_gsdown_e250/<name>/weights/best.pt
- generated_models_sadgs_gsdown_e250/<name>.yaml
- runs_sadgs_gsdown_e250/report.json / status.json
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import time

import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
PROJECT = ROOT / "runs_sadgs_gsdown_e250"
GEN_DIR = ROOT / "generated_models_sadgs_gsdown_e250"
REPORT_JSON = PROJECT / "report.json"
STATUS_JSON = PROJECT / "status.json"

NAMES = ["crazing", "inclusion", "patches", "pitted_surface", "rolled-in_scale", "scratches"]

GSDOWN_TRUTH = {
    "test_map50": 0.7338, "test_map50_95": 0.4018,
    "crazing_map50": 0.4432, "crazing_recall": 0.3794,
    "inclusion_map50": 0.7403, "inclusion_recall": 0.7016,
    "rolled_map50": 0.6023, "rolled_recall": 0.593,
    "scratches_map50": 0.9240, "scratches_recall": 0.8931,
}
MSDGS_TRUTH = {"test_map50": 0.732411, "test_map50_95": 0.398837, "fused_params": 1777318}


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def build_doc(dilations, strip_k, fracs) -> dict:
    """把 gsdown head 里所有 VoVGSCSP 换成 SADGS(dilations, strip_k, fracs)。backbone 一字不动。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            # VoVGSCSP args=[c2] -> SADGS args=[c2, shortcut, g, e, dilations, strip_k, fracs]
            block[2] = "SADGS"
            block[3] = [c2, True, 1, 0.5, list(dilations), int(strip_k), list(fracs)]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_swapped}"
    print(f"swapped {n_swapped} VoVGSCSP -> SADGS (dilations={dilations}, strip_k={strip_k}, fracs={fracs})")
    return doc


BUILDERS = {
    "gsdown_sadgs_13s7": lambda: build_doc((1, 3), 7, (1, 1, 1)),
    "gsdown_sadgs_13s11": lambda: build_doc((1, 3), 11, (1, 1, 1)),
    "gsdown_sadgs_135s7": lambda: build_doc((1, 3, 5), 7, (1, 1, 1, 1)),
}


def save_status(status: str, current, pending) -> None:
    PROJECT.mkdir(parents=True, exist_ok=True)
    STATUS_JSON.write_text(json.dumps({
        "status": status, "current": current, "pending": pending,
        "updated_at": now(), "report_json": str(REPORT_JSON),
    }, indent=2, ensure_ascii=False), encoding="utf-8")


def metric_dict(m) -> dict:
    infer = float(m.speed.get("inference", 0.0) or 0.0)
    out = {
        "map50": float(m.box.map50), "map50_95": float(m.box.map),
        "precision": float(m.box.mp), "recall": float(m.box.mr),
        "infer_ms": infer, "fps_infer_only": (1000.0 / infer) if infer else None,
        "per_class": {},
    }
    for i, c in enumerate(m.ap_class_index):
        name = NAMES[int(c)] if int(c) < len(NAMES) else str(int(c))
        out["per_class"][name] = {
            "map50": float(m.box.ap50[i]), "map50_95": float(m.box.ap[i]),
            "precision": float(m.box.p[i]), "recall": float(m.box.r[i]),
        }
    return out


def run_one(name: str, epochs: int, batch: int, imgsz: int, seed: int) -> dict:
    doc = BUILDERS[name]()
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{name}.yaml"
    cfg.write_text("# generated by train_sadgs_gsdown.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"CFG {cfg}")
    print(f"INIT_WEIGHTS {name} <- {OFFICIAL_WEIGHTS}")
    model = YOLO(str(cfg)).load(str(OFFICIAL_WEIGHTS))
    print(f"TRAIN_START {name} epochs={epochs} batch={batch} imgsz={imgsz} seed={seed}")
    model.train(
        data=str(DATA), epochs=epochs, imgsz=imgsz, batch=batch, workers=8,
        seed=seed, device=0, project=str(PROJECT), name=name, exist_ok=True,
        patience=max(epochs, 250), cache=False, verbose=True,
    )
    print(f"TRAIN_DONE {name}")

    weights = PROJECT / name / "weights" / "best.pt"
    best = YOLO(str(weights))
    params = int(sum(p.numel() for p in best.model.parameters()))
    v = best.val(data=str(DATA), split="val", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_val", exist_ok=True, verbose=False)
    t = best.val(data=str(DATA), split="test", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_test", exist_ok=True, verbose=False)
    return {
        "status": "done", "cfg": str(cfg), "weights": str(weights),
        "epochs": epochs, "batch": batch, "imgsz": imgsz, "seed": seed,
        "params_unfused": params,
        "val": metric_dict(v), "test": metric_dict(t),
        "finished_at": now(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=250)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--only", default="", help="逗号分隔候选名，只跑指定")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    PROJECT.mkdir(parents=True, exist_ok=True)
    selected = [x.strip() for x in args.only.split(",") if x.strip()] or list(BUILDERS)
    unknown = [x for x in selected if x not in BUILDERS]
    if unknown:
        raise SystemExit(f"unknown candidates: {unknown}")

    report = {}
    if REPORT_JSON.exists():
        report = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
    report.setdefault("schema_version", 1)
    report.setdefault("experiments", {})
    report["baseline"] = {"gsdown": GSDOWN_TRUTH, "msdgs135eq": MSDGS_TRUTH}
    completed = {k for k, v in report["experiments"].items() if v.get("status") == "done"}

    save_status("running", selected[0], selected)
    for pos, name in enumerate(selected, 1):
        if name in completed and not args.force:
            print(f"SKIP_DONE {name}")
            continue
        save_status("running", name, selected[pos:])
        try:
            result = run_one(name, args.epochs, args.batch, args.imgsz, args.seed)
        except Exception as exc:  # noqa: BLE001
            import traceback
            traceback.print_exc()
            report["experiments"][name] = {"status": "failed", "error": repr(exc), "failed_at": now()}
            REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
            save_status("failed", name, selected[pos:])
            print(f"CANDIDATE_FAILED {name} (isolated, continue)")
            continue  # 错误隔离：单候选崩溃不拖垮后续
        report["experiments"][name] = result
        REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        print("SADGS_RESULT", name,
              f"val_mAP50={result['val']['map50']:.5f}",
              f"val_mAP50-95={result['val']['map50_95']:.5f}",
              f"test_mAP50={result['test']['map50']:.5f}",
              f"test_mAP50-95={result['test']['map50_95']:.5f}",
              f"params_unfused={result['params_unfused']}")

    save_status("done", None, [])
    print(f"SADGS_DONE report={REPORT_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
