#!/usr/bin/env python
"""iter27：全局上下文解耦 neck（GCDGS）叠到 vovgscsp_gsdown，250e 串行对照训练。

设计动机（iter026 锁定的靶点，本轮 A 方向精修）：
- iter026 多尺度解耦 MSDGS 根治了 iter025 的"顾此失彼"——三强类首次同时守住
  （patches 0.589 / scratches 0.520 / pitted 0.469），证明"物理隔离多尺度分支"框架对。
- 但三候选全 < gsdown 0.4018（最好 135eq 0.3988，仅差 0.003），瓶颈锁定在两弱类
  （crazing 0.177 / rolled-in 0.258）。关键负结果：非对称偏 local（135local/13local）
  反而更差，证明弱类要的不是 local 容量。
- 机理：crazing（裂纹网）/rolled-in（氧化皮）是弥漫纹理缺陷，靠全图统计而非局部形状判别。
  depthwise 空洞卷积即便 d=5，有效感受野仍有限、且有网格伪影，喂不饱这类"全局统计型"纹理。

GCDGS = MSDGS + 一条全局上下文分支（GCNet 式：注意力池化聚全局 -> 轻量 transform -> 广播加回），
让弥漫纹理支路每个空间位置都拿到图像级上下文。解耦（参数/梯度隔离）与轻量保持不变。

候选（全部在 gsdown 基础上、从 yolo26n.pt 迁移、保 end2end/reg_max=1）：
- gsdown_gcdgs_13g_eq    : dilations=(1,3),   global_frac=1  2 local(d1,d3)+global 三等分（对照 msdgs 135eq）
- gsdown_gcdgs_135g      : dilations=(1,3,5), global_frac=1  3 local(d1,d3,d5)+global（多尺度+全局全都要）
- gsdown_gcdgs_13g_heavy : dilations=(1,3),   global_frac=2  global 分支加倍通道（若更好 => 弱类要全局假设坐实）

对照 = gsdown 独立真值 test mAP50 0.7338 / mAP50-95 0.4018 / 1.936M（轻量交付模型）。
iter26 最好 135eq 独立真值 test 0.7324 / 0.3988 / 1.777M（强类守住，弱类拖后腿）。
判定：test 真值 > 0.4018 且保住轻量，才算打破劫富济贫、提精度成功。
关键看点：弱类 crazing/rolled-in 能否被全局上下文抬起，同时不掉强类。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py      # SPDConv/DySample（gsdown 谱系依赖链）
    python install_gsconv_modules.py          # GSConv/VoVGSCSP（gsdown head 必需）
    python install_gcdgs_module.py            # GCDGS（本轮）
    python -u train_gcdgs_gsdown.py

输出：
- runs_gcdgs_gsdown_e250/<name>/weights/best.pt
- generated_models_gcdgs_gsdown_e250/<name>.yaml
- runs_gcdgs_gsdown_e250/report.json / status.json
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import time

import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
PROJECT = ROOT / "runs_gcdgs_gsdown_e250"
GEN_DIR = ROOT / "generated_models_gcdgs_gsdown_e250"
REPORT_JSON = PROJECT / "report.json"
STATUS_JSON = PROJECT / "status.json"

NAMES = ["crazing", "inclusion", "patches", "pitted_surface", "rolled-in_scale", "scratches"]


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def build_doc(dilations, global_frac, r=4) -> dict:
    """把 gsdown head 里所有 VoVGSCSP 换成 GCDGS(dilations, global_frac, r)。backbone 一字不动。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            # VoVGSCSP args=[c2] -> GCDGS args=[c2, shortcut, g, e, dilations, global_frac, r]
            block[2] = "GCDGS"
            block[3] = [c2, True, 1, 0.5, list(dilations), float(global_frac), int(r)]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_swapped}"
    print(f"swapped {n_swapped} VoVGSCSP -> GCDGS (dilations={dilations}, global_frac={global_frac}, r={r})")
    return doc


BUILDERS = {
    "y26n_gsdown_gcdgs_13g_eq_e250": lambda: build_doc((1, 3), 1.0),
    "y26n_gsdown_gcdgs_135g_e250": lambda: build_doc((1, 3, 5), 1.0),
    "y26n_gsdown_gcdgs_13g_heavy_e250": lambda: build_doc((1, 3), 2.0),
}


def save_status(status: str, current, pending) -> None:
    PROJECT.mkdir(parents=True, exist_ok=True)
    STATUS_JSON.write_text(json.dumps({
        "status": status, "current": current, "pending": pending,
        "updated_at": now(), "report_json": str(REPORT_JSON),
    }, indent=2, ensure_ascii=False), encoding="utf-8")


def metric_dict(m) -> dict:
    infer = float(m.speed.get("inference", 0.0) or 0.0)
    out = {
        "map50": float(m.box.map50), "map50_95": float(m.box.map),
        "precision": float(m.box.mp), "recall": float(m.box.mr),
        "infer_ms": infer, "fps_infer_only": (1000.0 / infer) if infer else None,
        "per_class": {},
    }
    for i, c in enumerate(m.ap_class_index):
        name = NAMES[int(c)] if int(c) < len(NAMES) else str(int(c))
        out["per_class"][name] = {"map50": float(m.box.ap50[i]), "map50_95": float(m.box.ap[i])}
    return out


def run_one(name: str, epochs: int, batch: int, imgsz: int, seed: int) -> dict:
    doc = BUILDERS[name]()
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{name}.yaml"
    cfg.write_text("# generated by train_gcdgs_gsdown.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"CFG {cfg}")
    print(f"INIT_WEIGHTS {name} <- {OFFICIAL_WEIGHTS}")
    model = YOLO(str(cfg)).load(str(OFFICIAL_WEIGHTS))
    print(f"TRAIN_START {name} epochs={epochs} batch={batch} imgsz={imgsz}")
    model.train(
        data=str(DATA), epochs=epochs, imgsz=imgsz, batch=batch, workers=8,
        seed=seed, device=0, project=str(PROJECT), name=name, exist_ok=True,
        patience=max(epochs, 250), cache=False, verbose=True,
    )
    print(f"TRAIN_DONE {name}")

    weights = PROJECT / name / "weights" / "best.pt"
    best = YOLO(str(weights))
    params = int(sum(p.numel() for p in best.model.parameters()))
    v = best.val(data=str(DATA), split="val", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_val", exist_ok=True, verbose=False)
    t = best.val(data=str(DATA), split="test", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_test", exist_ok=True, verbose=False)
    return {
        "status": "done", "cfg": str(cfg), "weights": str(weights),
        "epochs": epochs, "batch": batch, "imgsz": imgsz, "seed": seed,
        "params_unfused": params,
        "val": metric_dict(v), "test": metric_dict(t),
        "finished_at": now(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=250)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--only", default="", help="逗号分隔候选名，只跑指定")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    PROJECT.mkdir(parents=True, exist_ok=True)
    selected = [x.strip() for x in args.only.split(",") if x.strip()] or list(BUILDERS)
    unknown = [x for x in selected if x not in BUILDERS]
    if unknown:
        raise SystemExit(f"unknown candidates: {unknown}")

    report = {}
    if REPORT_JSON.exists():
        report = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
    report.setdefault("schema_version", 1)
    report.setdefault("experiments", {})
    completed = {k for k, v in report["experiments"].items() if v.get("status") == "done"}

    save_status("running", selected[0], selected)
    for pos, name in enumerate(selected, 1):
        if name in completed and not args.force:
            print(f"SKIP_DONE {name}")
            continue
        save_status("running", name, selected[pos:])
        try:
            result = run_one(name, args.epochs, args.batch, args.imgsz, args.seed)
        except Exception as exc:  # noqa: BLE001
            import traceback
            traceback.print_exc()
            report["experiments"][name] = {"status": "failed", "error": repr(exc), "failed_at": now()}
            REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
            save_status("failed", name, selected[pos:])
            print(f"CANDIDATE_FAILED {name} (isolated, continue)")
            continue  # 错误隔离：单候选崩溃不拖垮后续
        report["experiments"][name] = result
        REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        print("GCDGS_RESULT", name,
              f"val_mAP50={result['val']['map50']:.5f}",
              f"val_mAP50-95={result['val']['map50_95']:.5f}",
              f"test_mAP50={result['test']['map50']:.5f}",
              f"test_mAP50-95={result['test']['map50_95']:.5f}",
              f"params_unfused={result['params_unfused']}")

    save_status("done", None, [])
    print(f"GCDGS_DONE report={REPORT_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
