#!/usr/bin/env python
"""iter028 收口 G：13hf(最优) vs gsdown(基线) 多 seed 稳健性验证。

动机：iter028 首次破线 13hf test mAP50-95 0.4041 vs gsdown 0.4018，领先仅 +0.0023。
必须证明这不是单 seed 随机噪声，否则后续论文结论不牢。

方案：两配置各补 seed 1/2/3（seed 0 两者均已有独立真值：13hf 0.4041 / gsdown 0.4018），
凑齐 4 个配对样本，做配对 t 检验（同 seed 下 13hf - gsdown 的差值分布是否显著 > 0）。

- 13hf   = gsdown neck 的 VoVGSCSP 换成 HFDGS(dils=(1,3), hf=1.0, gc=0.0)  —— 与 iter028 完全一致
- gsdown = 原始 vovgscsp_gsdown YAML，不做任何 swap（基线）

每个 run 训完立刻在同一进程内 val + test 评估并写入 report（注意：口径铁律仍要求最终用
独立进程 per_class_test.py 复核关键 seed；本脚本内评估仅供多 seed 汇总，判定以独立复核为准）。

远程用法：
    source /root/miniconda3/etc/profile.d/conda.sh && conda activate yolo26
    cd /root/autodl-tmp/neu-det-yolo26
    python install_yolo26_exp_modules.py
    python install_gsconv_modules.py
    python install_hfdgs_module.py
    python -u train_multiseed_13hf_vs_gsdown.py

输出：
- runs_multiseed_13hf_vs_gsdown/<config>_seed<k>/weights/best.pt
- runs_multiseed_13hf_vs_gsdown/report.json / status.json
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import time

import yaml
from ultralytics import YOLO

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
GSDOWN_YAML = ROOT / "generated_models_module_stage3_e250" / "y26n_s3_vovgscsp_gsdown_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
PROJECT = ROOT / "runs_multiseed_13hf_vs_gsdown"
GEN_DIR = ROOT / "generated_models_multiseed_13hf_vs_gsdown"
REPORT_JSON = PROJECT / "report.json"
STATUS_JSON = PROJECT / "status.json"

NAMES = ["crazing", "inclusion", "patches", "pitted_surface", "rolled-in_scale", "scratches"]

# 只补 seed 1/2/3；seed 0 两配置均已有独立真值，直接并入汇总，不重训。
SEEDS = [1, 2, 3]
SEED0_TRUTH = {  # iter028 独立进程 fused 真值（口径铁律锁死）
    "13hf": {"test_map50": 0.7355540692094995, "test_map50_95": 0.4041016695083072},
    "gsdown": {"test_map50": 0.7338, "test_map50_95": 0.4018},
}


def now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def build_13hf_doc() -> dict:
    """gsdown head 里所有 VoVGSCSP 换成 HFDGS(dils=(1,3), hf=1.0, gc=0.0)。与 iter028 13hf 完全一致。"""
    doc = yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))
    n_swapped = 0
    for block in doc.get("head", []):
        if len(block) >= 4 and block[2] == "VoVGSCSP":
            c2 = block[3][0]
            # VoVGSCSP args=[c2] -> HFDGS args=[c2, shortcut, g, e, dilations, hf_frac, global_frac, pool_k, r]
            block[2] = "HFDGS"
            block[3] = [c2, True, 1, 0.5, [1, 3], 1.0, 0.0, 3, 4]
            n_swapped += 1
    assert n_swapped == 4, f"expected 4 VoVGSCSP in gsdown neck, got {n_swapped}"
    return doc


def build_gsdown_doc() -> dict:
    """原始 vovgscsp_gsdown，不做任何 swap（基线）。"""
    return yaml.safe_load(GSDOWN_YAML.read_text(encoding="utf-8"))


CONFIGS = {
    "13hf": build_13hf_doc,
    "gsdown": build_gsdown_doc,
}


def save_status(status: str, current, pending) -> None:
    PROJECT.mkdir(parents=True, exist_ok=True)
    STATUS_JSON.write_text(json.dumps({
        "status": status, "current": current, "pending": pending,
        "updated_at": now(), "report_json": str(REPORT_JSON),
    }, indent=2, ensure_ascii=False), encoding="utf-8")


def metric_dict(m) -> dict:
    infer = float(m.speed.get("inference", 0.0) or 0.0)
    out = {
        "map50": float(m.box.map50), "map50_95": float(m.box.map),
        "precision": float(m.box.mp), "recall": float(m.box.mr),
        "infer_ms": infer, "fps_infer_only": (1000.0 / infer) if infer else None,
        "per_class": {},
    }
    for i, c in enumerate(m.ap_class_index):
        name = NAMES[int(c)] if int(c) < len(NAMES) else str(int(c))
        out["per_class"][name] = {"map50": float(m.box.ap50[i]), "map50_95": float(m.box.ap[i])}
    return out


def run_one(config: str, seed: int, epochs: int, batch: int, imgsz: int) -> dict:
    doc = CONFIGS[config]()
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    cfg = GEN_DIR / f"{config}.yaml"
    cfg.write_text("# generated by train_multiseed_13hf_vs_gsdown.py\n"
                   + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    name = f"{config}_seed{seed}"
    print(f"CFG {cfg}")
    print(f"INIT_WEIGHTS {name} <- {OFFICIAL_WEIGHTS}")
    model = YOLO(str(cfg)).load(str(OFFICIAL_WEIGHTS))
    print(f"TRAIN_START {name} epochs={epochs} batch={batch} imgsz={imgsz} seed={seed}")
    model.train(
        data=str(DATA), epochs=epochs, imgsz=imgsz, batch=batch, workers=8,
        seed=seed, device=0, project=str(PROJECT), name=name, exist_ok=True,
        patience=max(epochs, 250), cache=False, verbose=True,
    )
    print(f"TRAIN_DONE {name}")

    weights = PROJECT / name / "weights" / "best.pt"
    best = YOLO(str(weights))
    params = int(sum(p.numel() for p in best.model.parameters()))
    v = best.val(data=str(DATA), split="val", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_val", exist_ok=True, verbose=False)
    t = best.val(data=str(DATA), split="test", imgsz=imgsz, batch=batch, device=0,
                 project=str(PROJECT), name=f"{name}_test", exist_ok=True, verbose=False)
    return {
        "status": "done", "config": config, "seed": seed, "cfg": str(cfg),
        "weights": str(weights), "epochs": epochs, "batch": batch, "imgsz": imgsz,
        "params_unfused": params,
        "val": metric_dict(v), "test": metric_dict(t),
        "finished_at": now(),
    }


def summarize(report: dict) -> dict:
    """汇总每配置各 seed 的 test mAP50-95，并做配对差值统计。"""
    exps = report.get("experiments", {})
    # 收集每配置 seed->test_map50_95
    by_cfg = {"13hf": {}, "gsdown": {}}
    for _, r in exps.items():
        if r.get("status") != "done":
            continue
        by_cfg.setdefault(r["config"], {})[int(r["seed"])] = {
            "test_map50_95": r["test"]["map50_95"], "test_map50": r["test"]["map50"],
        }
    # 并入 seed0 真值
    by_cfg["13hf"][0] = SEED0_TRUTH["13hf"]
    by_cfg["gsdown"][0] = SEED0_TRUTH["gsdown"]

    common = sorted(set(by_cfg["13hf"]) & set(by_cfg["gsdown"]))
    diffs = [by_cfg["13hf"][s]["test_map50_95"] - by_cfg["gsdown"][s]["test_map50_95"] for s in common]

    def _stats(vals):
        n = len(vals)
        mean = sum(vals) / n if n else 0.0
        var = sum((x - mean) ** 2 for x in vals) / (n - 1) if n > 1 else 0.0
        return {"n": n, "mean": mean, "std": var ** 0.5}

    hf_vals = [by_cfg["13hf"][s]["test_map50_95"] for s in common]
    gs_vals = [by_cfg["gsdown"][s]["test_map50_95"] for s in common]
    d_stat = _stats(diffs)
    # 配对 t 统计量（不查表，仅给 t 值供人工/后续判显著）
    n = d_stat["n"]
    se = (d_stat["std"] / (n ** 0.5)) if n > 1 and d_stat["std"] > 0 else 0.0
    t_stat = (d_stat["mean"] / se) if se > 0 else None
    return {
        "seeds": common,
        "13hf_test_map50_95": {s: by_cfg["13hf"][s]["test_map50_95"] for s in common},
        "gsdown_test_map50_95": {s: by_cfg["gsdown"][s]["test_map50_95"] for s in common},
        "13hf_stats": _stats(hf_vals),
        "gsdown_stats": _stats(gs_vals),
        "paired_diff": diffs,
        "paired_diff_stats": d_stat,
        "paired_t": t_stat,
        "note": "t 值 > 对应自由度(n-1)的单尾临界值即显著；n=4 时 df=3, t_0.05=2.353",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=250)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    PROJECT.mkdir(parents=True, exist_ok=True)

    report = {}
    if REPORT_JSON.exists():
        report = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
    report.setdefault("schema_version", 1)
    report.setdefault("experiments", {})
    completed = {k for k, v in report["experiments"].items() if v.get("status") == "done"}

    # 任务清单：两配置 × seed 1/2/3，交错排（先跑同 seed 的两配置，尽早得到可比对）
    jobs = []
    for seed in SEEDS:
        for config in ("13hf", "gsdown"):
            jobs.append((config, seed))
    job_names = [f"{c}_seed{s}" for c, s in jobs]

    save_status("running", job_names[0] if job_names else None, job_names)
    for pos, (config, seed) in enumerate(jobs, 1):
        name = f"{config}_seed{seed}"
        if name in completed and not args.force:
            print(f"SKIP_DONE {name}")
            continue
        save_status("running", name, job_names[pos:])
        try:
            result = run_one(config, seed, args.epochs, args.batch, args.imgsz)
        except Exception as exc:  # noqa: BLE001
            import traceback
            traceback.print_exc()
            report["experiments"][name] = {"status": "failed", "config": config, "seed": seed,
                                           "error": repr(exc), "failed_at": now()}
            REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
            save_status("failed", name, job_names[pos:])
            print(f"JOB_FAILED {name} (isolated, continue)")
            continue
        report["experiments"][name] = result
        report["summary"] = summarize(report)
        REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
        print("MULTISEED_RESULT", name,
              f"test_mAP50={result['test']['map50']:.5f}",
              f"test_mAP50-95={result['test']['map50_95']:.5f}")

    report["summary"] = summarize(report)
    REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    save_status("done", None, [])
    print("MULTISEED_SUMMARY", json.dumps(report["summary"], ensure_ascii=False))
    print(f"MULTISEED_DONE report={REPORT_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
