data_path: /root/autodl-tmp/neu-det-yolo26/gold_yolo_data/neudet.yaml
conf_file: /root/autodl-tmp/neu-det-yolo26/Gold-YOLO-src/Detection/Gold-YOLO/configs/gold_yolo-n.py
use_syncbn: false
img_size: 640
batch_size: 32
epochs: 250
workers: 8
device: '0'
eval_interval: 20
eval_final_only: true
heavy_eval_range: 50
check_images: false
check_labels: false
output_dir: /root/autodl-tmp/neu-det-yolo26/runs_sota_gold_yolo_n_seed0_e250/neudet
name: gold_yolo_n_seed0
dist_url: env://
gpu_count: 0
local_rank: -1
resume: false
write_trainbatch_tb: false
stop_aug_last_n_epoch: 15
save_ckpt_on_last_n_epoch: -1
distill: false
distill_feat: false
quant: false
calib: false
teacher_model_path: null
temperature: 20
fuse_ab: true
bs_per_gpu: 32
rank: -1
world_size: 1
save_dir: /root/autodl-tmp/neu-det-yolo26/runs_sota_gold_yolo_n_seed0_e250/neudet/gold_yolo_n_seed0
