#!/usr/bin/env python
"""Strict build gate for the MSDGS P4 DCNv2 single-module replacement (iter057).

Unlike the residual candidates (iter052/054/055), C3k2DCNv2 replaces the inner
Bottleneck 3x3 convs by freshly-initialized deformable convs, so the candidate is
NOT bit-exact equivalent to the standard C3k2 at init. Instead the gate proves:
  1. structural contract (layer6 = C3k2DCNv2, layer8=C3k2, layer10=C2PSA, head
     end2end/reg_max/nl/channels, eval + fused output = (1,300,6));
  2. YAML changes only backbone[6];
  3. deform init behavior: offset predictor -> zero offset, mask -> 1.0 (regular
     3x3 grid sampling at init) so training starts from a standard-conv geometry;
  4. pretrained transfer: cv1 / C3k outer / non-deform params still match yolo26n
     (only the deform main weights are fresh);
  5. gradient flow into offset predictor, deform weight, and untouched main path;
  6. fuse keeps deform units intact (non-fusable) and output stays (1,300,6);
  7. param / GFLOPs budget (fused params <= 1.90M, GFLOPs <= 4.40).
"""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import subprocess
import sys

import torch
import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_backbone_dcnv2_e250"
CHECK_DIR = ROOT / "runs_msdgs_backbone_dcnv2_e250" / "build_check"
CANDIDATE = "msdgs_bb_p4_dcnv2"
MAX_FUSED_PARAMS = 1_900_000
MAX_GFLOPS = 4.40


def generate_yaml() -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    layer = doc["backbone"][6]
    assert layer[0] == -1 and layer[1] == 2 and layer[2] == "C3k2", layer
    assert layer[3][0] == 512 and layer[3][1] is True, layer
    layer[2] = "C3k2DCNv2"
    # Signature identical to C3k2 -> args unchanged ([512, True] => c2=512, c3k=True).
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GEN_DIR / f"{CANDIDATE}.yaml"
    path.write_text(
        "# generated by build_check_msdgs_backbone_dcnv2.py\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    return path


def output_tensor(output):
    if torch.is_tensor(output):
        return output
    if isinstance(output, (list, tuple)) and output and torch.is_tensor(output[0]):
        return output[0]
    raise TypeError(f"cannot extract decoded tensor from {type(output)!r}")


def output_shape(output):
    try:
        return tuple(output_tensor(output).shape)
    except TypeError:
        return None


def max_grad(parameters) -> float:
    return max(
        (float(p.grad.abs().max()) if p.grad is not None else 0.0 for p in parameters),
        default=0.0,
    )


def module_behavior_check() -> dict:
    from ultralytics.nn.modules.block import Bottleneck
    from ultralytics.nn.modules.yolo26_msdgs_backbone_dcnv2 import C3k2DCNv2, DCNv2Unit

    torch.manual_seed(57)
    # Match MSDGS layer6: C3k2(512, n=2, c3k=True). Use 128 channels smoke instance
    # plus a full-size instance to count deform units.
    custom = C3k2DCNv2(256, 256, n=2, c3k=True)
    assert custom.deform_units > 0, custom.deform_units
    # Every deform unit must be a DCNv2Unit sitting where a Bottleneck.cv2 was.
    deform_seen = 0
    for module in custom.modules():
        if isinstance(module, Bottleneck):
            assert isinstance(module.cv2, DCNv2Unit), type(module.cv2).__name__
            deform_seen += 1
    assert deform_seen == custom.deform_units, (deform_seen, custom.deform_units)

    unit = None
    for module in custom.modules():
        if isinstance(module, DCNv2Unit):
            unit = module
            break
    assert unit is not None
    # Init behavior: offset predictor produces zero offset, mask = 1.0.
    unit.eval()
    x = torch.randn(2, unit.offset_mask.in_channels, 20, 20)
    with torch.no_grad():
        om = unit.offset_mask(x)
        offset = om[:, : unit._split]
        mask = 2.0 * torch.sigmoid(om[:, unit._split :])
    offset_max = float(offset.abs().max())
    mask_dev = float((mask - 1.0).abs().max())
    assert offset_max == 0.0, offset_max
    assert mask_dev == 0.0, mask_dev

    # Gradient flow: offset predictor, deform main weight, and outer cv1 all learn.
    custom.train()
    optimizer = torch.optim.SGD(custom.parameters(), lr=0.01)
    optimizer.zero_grad(set_to_none=True)
    custom(torch.randn(2, 256, 20, 20)).square().mean().backward()
    offset_grad = max_grad(unit.offset_mask.parameters())
    deform_grad = max_grad(unit.deform.parameters())
    outer_grad = max_grad(custom.cv1.parameters())
    # offset predictor is zero-weight at init, so its first-step grad may be 0 for
    # the weight but the bias receives gradient once mask/offset feed the loss.
    assert deform_grad > 0.0, deform_grad
    assert outer_grad > 0.0, outer_grad
    optimizer.step()
    optimizer.zero_grad(set_to_none=True)
    custom(torch.randn(2, 256, 20, 20)).square().mean().backward()
    offset_grad2 = max_grad(unit.offset_mask.parameters())
    deform_grad2 = max_grad(unit.deform.parameters())
    assert offset_grad2 > 0.0, offset_grad2
    assert deform_grad2 > 0.0, deform_grad2

    return {
        "deform_units_full_c3k": int(custom.deform_units),
        "deform_units_seen": int(deform_seen),
        "init_offset_max_abs": offset_max,
        "init_mask_dev_from_one": mask_dev,
        "offset_grad_step1": offset_grad,
        "deform_grad_step1": deform_grad,
        "outer_cv1_grad_step1": outer_grad,
        "offset_grad_step2": offset_grad2,
        "deform_grad_step2": deform_grad2,
    }


def model_gflops(model):
    from ultralytics.utils.torch_utils import get_flops

    return float(get_flops(model, imgsz=640))


def matched_tensor_count(source, target) -> int:
    source_state, target_state = source.state_dict(), target.state_dict()
    return sum(k in target_state and target_state[k].shape == v.shape for k, v in source_state.items())


def reload_worker(weights: Path) -> int:
    from ultralytics import YOLO

    wrapper = YOLO(str(weights), task="detect")
    model = wrapper.model.eval()
    with torch.no_grad():
        shape = output_shape(model(torch.zeros(1, 3, 640, 640)))
    payload = {
        "layer6": type(model.model[6]).__name__,
        "layer8": type(model.model[8]).__name__,
        "layer10": type(model.model[10]).__name__,
        "shape": shape,
    }
    print(json.dumps(payload))
    ok = (
        payload["layer6"] == "C3k2DCNv2"
        and payload["layer8"] == "C3k2"
        and payload["layer10"] == "C2PSA"
        and shape == (1, 300, 6)
    )
    return 0 if ok else 2


def model_check() -> dict:
    from ultralytics import YOLO
    from ultralytics.nn.modules.yolo26_msdgs_backbone_dcnv2 import (
        DCNv2Unit,
        transfer_standard_to_dcnv2,
    )

    cfg = generate_yaml()
    base_doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    candidate_doc = yaml.safe_load(cfg.read_text(encoding="utf-8"))
    for key in base_doc:
        if key != "backbone":
            assert candidate_doc[key] == base_doc[key], key
    assert len(candidate_doc["backbone"]) == len(base_doc["backbone"])
    changed_indices = [
        i
        for i, (base_layer, candidate_layer) in enumerate(zip(base_doc["backbone"], candidate_doc["backbone"]))
        if base_layer != candidate_layer
    ]
    assert changed_indices == [6], changed_indices

    source = YOLO(str(OFFICIAL_WEIGHTS), task="detect").model
    baseline = YOLO(str(BASE_YAML), task="detect").model
    wrapper = YOLO(str(cfg), task="detect")
    model = wrapper.model
    head = model.model[-1]
    layer6, layer8, layer10 = model.model[6], model.model[8], model.model[10]
    assert type(layer6).__name__ == "C3k2DCNv2"
    assert type(layer8).__name__ == "C3k2"
    assert type(layer10).__name__ == "C2PSA"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    detect_channels = tuple(int(t[0].conv.in_channels) for t in head.cv2)
    assert detect_channels == (64, 128, 256), detect_channels

    deform_units = sum(1 for m in layer6.modules() if isinstance(m, DCNv2Unit))
    assert deform_units == layer6.deform_units and deform_units > 0, deform_units

    # This is a REPLACEMENT module (not additive): the baseline's model.6 inner
    # Bottleneck cv2.conv.weight tensors no longer exist; DCNv2Unit introduces
    # cv2.offset_mask.* / cv2.deform.weight instead. So a plain load reports the
    # baseline cv2.conv.weight as unexpected and the deform/offset weights as
    # missing. That is expected; the transfer step below resolves it.
    missing, unexpected = model.load_state_dict(baseline.state_dict(), strict=False)
    deform_prefixes = (".cv2.offset_mask.", ".cv2.deform.")
    # Every unexpected key is a replaced standard-conv weight under model.6.
    assert unexpected and all(
        k.startswith("model.6.") and k.endswith(".cv2.conv.weight") for k in unexpected
    ), unexpected
    # Every missing key is deform-specific and lives under model.6.
    assert missing and all(
        "model.6." in k and any(p in k for p in deform_prefixes) for k in missing
    ), missing

    # Transfer pretrained standard 3x3 conv weight into the deform main weight.
    # deform_conv2d weight has identical shape and, with offset=0 + mask=1, computes
    # the identical regular-grid convolution -> init becomes numerically equivalent
    # to the pretrained conv (information-preserving, grid-equivalent start).
    transferred = transfer_standard_to_dcnv2(model, baseline.state_dict())
    assert transferred == deform_units, (transferred, deform_units)

    # Non-deform main-path tensors under model.6 (cv1, outer cv1/cv2, C3k cv,
    # cv2.bn) must match baseline exactly after transfer.
    base_state, candidate_state = baseline.state_dict(), model.state_dict()
    preserved_keys = [
        k for k in base_state
        if k.startswith("model.6.")
        and not k.endswith(".cv2.conv.weight")
        and k in candidate_state
        and candidate_state[k].shape == base_state[k].shape
    ]
    assert preserved_keys
    preserved_error = max(float((base_state[k] - candidate_state[k]).abs().max()) for k in preserved_keys)
    assert preserved_error == 0.0, preserved_error

    base_match = matched_tensor_count(source, baseline)
    candidate_match = matched_tensor_count(source, model)

    # Init-equivalence proof: after transfer, the candidate must produce numerically
    # identical layer6 output AND identical full-model output vs the baseline (the
    # deform block degenerates to the pretrained regular-grid conv at init).
    baseline.eval()
    model.eval()
    x = torch.randn(1, 3, 640, 640)
    captured = {}
    hook_a = baseline.model[6].register_forward_hook(
        lambda _m, _i, o: captured.setdefault("base6", o.detach())
    )
    hook_b = model.model[6].register_forward_hook(
        lambda _m, _i, o: captured.setdefault("cand6", o.detach())
    )
    with torch.no_grad():
        base_out = baseline(x.clone())
        cand_out = model(x.clone())
    hook_a.remove()
    hook_b.remove()
    layer6_error = float((captured["base6"] - captured["cand6"]).abs().max())
    full_error = float((output_tensor(base_out) - output_tensor(cand_out)).abs().max())
    # DeformConv2d uses bilinear grid sampling; even at zero offset a tiny numerical
    # epsilon vs a plain conv2d is possible, so allow a small tolerance.
    assert layer6_error < 1e-4, layer6_error
    assert full_error < 1e-4, full_error

    # Reload official pretrained through YOLO.load (training init path), then
    # re-transfer deform weights, mirroring what train_worker does.
    wrapper.load(str(OFFICIAL_WEIGHTS))
    transfer_standard_to_dcnv2(model, baseline.state_dict())
    model.eval()
    probe = torch.zeros(1, 3, 640, 640)
    with torch.no_grad():
        shape = output_shape(model(probe))
    assert shape == (1, 300, 6), shape

    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint = CHECK_DIR / f"{CANDIDATE}_roundtrip.pt"
    wrapper.save(str(checkpoint))
    child = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--reload-check", str(checkpoint)],
        text=True, capture_output=True, check=False,
    )
    print(child.stdout, end="")
    if child.stderr:
        print(child.stderr, file=sys.stderr, end="")
    assert child.returncode == 0, child.returncode

    # Fuse must keep deform units intact (non-fusable) and preserve output shape.
    # NOTE: torchvision 0.18 deform_conv2d has a CPU-only kernel bug that segfaults
    # inside thop's profiling forward (get_flops) and the fused forward. The real
    # train/val pipeline runs on device=0 (GPU) where deform_conv2d is healthy, so
    # fuse / FLOPs / fused-forward are measured on CUDA when available.
    fuse_device = "cuda" if torch.cuda.is_available() else "cpu"
    fused = copy.deepcopy(model).eval().to(fuse_device)
    fused.fuse()
    fused_deform_units = sum(1 for m in fused.model[6].modules() if isinstance(m, DCNv2Unit))
    assert fused_deform_units == deform_units, (fused_deform_units, deform_units)
    fused_params = int(sum(p.numel() for p in fused.parameters()))
    gflops = model_gflops(fused)
    with torch.no_grad():
        fused_shape = output_shape(fused(probe.to(fuse_device)))
    assert fused_shape == (1, 300, 6), fused_shape
    assert fused_params <= MAX_FUSED_PARAMS, fused_params
    assert gflops <= MAX_GFLOPS, gflops

    return {
        "cfg": str(cfg),
        "changed_backbone_indices": changed_indices,
        "layer6": type(layer6).__name__,
        "layer8": type(layer8).__name__,
        "layer10": type(layer10).__name__,
        "deform_units_layer6": int(deform_units),
        "end2end": bool(head.end2end),
        "reg_max": int(head.reg_max),
        "nl": int(head.nl),
        "detect_input_channels": list(detect_channels),
        "eval_shape": list(shape),
        "fused_shape": list(fused_shape),
        "fuse_device": fuse_device,
        "fused_deform_units": int(fused_deform_units),
        "preserved_mainpath_tensors": len(preserved_keys),
        "preserved_mainpath_max_abs_error": preserved_error,
        "missing_deform_state_items": len(missing),
        "official_matched_tensors": candidate_match,
        "baseline_matched_tensors": base_match,
        "params_unfused": int(sum(p.numel() for p in model.parameters())),
        "params_fused": fused_params,
        "gflops_fused_inference": gflops,
        "budget_fused_params_max": MAX_FUSED_PARAMS,
        "budget_gflops_max": MAX_GFLOPS,
        "roundtrip_checkpoint": str(checkpoint),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reload-check", type=Path)
    args = parser.parse_args()
    if args.reload_check:
        return reload_worker(args.reload_check)
    for path in (BASE_YAML, OFFICIAL_WEIGHTS):
        if not path.exists():
            raise FileNotFoundError(path)
    payload = {"module_behavior": module_behavior_check(), "candidate": model_check()}
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    report = CHECK_DIR / "report.json"
    report.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("BUILD_CHECK_MSDGS_BACKBONE_DCNV2_OK", report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
