#!/usr/bin/env python
"""MSDGSBoxResDetect 两候选的结构、等价性、迁移、梯度、融合和重载检查。"""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import subprocess
import sys

import torch
import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_boxres_e250"
CHECK_DIR = ROOT / "runs_msdgs_boxres_e250" / "build_check"
SPECS = {
    "msdgs_p5box_res16": [16, False],
    "msdgs_p4detail_boxres": [16, True],
}


def generate_yaml(name: str) -> Path:
    doc = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    last = doc["head"][-1]
    assert last[0] == [16, 19, 22] and last[2] == "Detect", last
    last[2] = "MSDGSBoxResDetect"
    last[3] = ["nc", *SPECS[name]]
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GEN_DIR / f"{name}.yaml"
    path.write_text("# generated by build_check_msdgs_boxres.py\n" + yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")
    return path


def output_shape(output):
    if torch.is_tensor(output):
        return tuple(output.shape)
    if isinstance(output, (list, tuple)) and output and torch.is_tensor(output[0]):
        return tuple(output[0].shape)
    return None


def tensor_max_abs(a, b) -> float:
    values = []
    if torch.is_tensor(a) and torch.is_tensor(b):
        values.append(float((a - b).abs().max()))
    elif isinstance(a, dict) and isinstance(b, dict):
        assert a.keys() == b.keys()
        values.extend(tensor_max_abs(a[k], b[k]) for k in a)
    elif isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        assert len(a) == len(b)
        values.extend(tensor_max_abs(x, y) for x, y in zip(a, b))
    else:
        assert type(a) is type(b)
    return max(values, default=0.0)


def fresh_features():
    return [
        torch.randn(1, 64, 20, 20, requires_grad=True),
        torch.randn(1, 128, 10, 10, requires_grad=True),
        torch.randn(1, 256, 5, 5, requires_grad=True),
    ]


def final_conv(branch):
    return branch[-1]


def equivalence_and_gradient(name: str) -> dict:
    from ultralytics.nn.modules.head import Detect
    from ultralytics.nn.modules.yolo26_msdgs_boxres import MSDGSBoxResDetect

    Detect.legacy = False
    MSDGSBoxResDetect.legacy = False
    torch.manual_seed(29)
    standard = Detect(nc=6, reg_max=1, end2end=True, ch=(64, 128, 256))
    custom = MSDGSBoxResDetect(
        nc=6, residual_width=SPECS[name][0], use_p4_detail=SPECS[name][1],
        reg_max=1, end2end=True, ch=(64, 128, 256),
    )
    missing, unexpected = custom.load_state_dict(standard.state_dict(), strict=False)
    assert not unexpected
    assert missing and all(key.startswith(("box_res_o2m.", "box_res_o2o.")) for key in missing), missing
    for branch in (custom.box_res_o2m, custom.box_res_o2o):
        assert torch.count_nonzero(final_conv(branch).weight) == 0
        assert torch.count_nonzero(final_conv(branch).bias) == 0

    standard.stride[:] = torch.tensor([8.0, 16.0, 32.0])
    custom.stride[:] = standard.stride
    standard.eval()
    custom.eval()
    features = [torch.randn(1, 64, 80, 80), torch.randn(1, 128, 40, 40), torch.randn(1, 256, 20, 20)]
    with torch.no_grad():
        error = tensor_max_abs(standard([x.clone() for x in features]), custom([x.clone() for x in features]))
    assert error < 1e-6, error

    custom.train()
    custom.zero_grad(set_to_none=True)
    o2o_features = fresh_features()
    o2o = custom(o2o_features)["one2one"]
    o2o["boxes"].sum().backward()
    input_grad = max(float(x.grad.abs().max()) if x.grad is not None else 0.0 for x in o2o_features)
    final_weight_grad = float(final_conv(custom.box_res_o2o).weight.grad.abs().max())
    assert input_grad == 0.0, input_grad
    assert final_weight_grad > 0.0, final_weight_grad

    custom.zero_grad(set_to_none=True)
    o2m_features = fresh_features()
    o2m = custom(o2m_features)["one2many"]
    o2m["boxes"].sum().backward()
    o2m_input_grad = max(float(x.grad.abs().max()) if x.grad is not None else 0.0 for x in o2m_features)
    o2m_final_grad = float(final_conv(custom.box_res_o2m).weight.grad.abs().max())
    assert o2m_input_grad > 0.0
    assert o2m_final_grad > 0.0
    return {
        "equivalence_max_abs_error": error,
        "one2one_input_grad_max": input_grad,
        "one2one_residual_final_grad_max": final_weight_grad,
        "one2many_input_grad_max": o2m_input_grad,
        "one2many_residual_final_grad_max": o2m_final_grad,
        "missing_residual_state_items": len(missing),
    }


def model_gflops(model):
    from ultralytics.utils.torch_utils import get_flops
    return float(get_flops(model, imgsz=640))


def matched_tensor_count(source, target) -> int:
    source_state = source.state_dict()
    target_state = target.state_dict()
    return sum(key in target_state and target_state[key].shape == value.shape for key, value in source_state.items())


def reload_worker(weights: Path) -> int:
    from ultralytics import YOLO
    wrapper = YOLO(str(weights), task="detect")
    wrapper.model.eval()
    with torch.no_grad():
        shape = output_shape(wrapper.model(torch.zeros(1, 3, 640, 640)))
    print(json.dumps({"head": type(wrapper.model.model[-1]).__name__, "shape": shape}))
    return 0 if shape == (1, 300, 6) else 2


def check_candidate(name: str, source_model, base_match: int) -> dict:
    from ultralytics import YOLO

    cfg = generate_yaml(name)
    wrapper = YOLO(str(cfg), task="detect")
    model = wrapper.model
    head = model.model[-1]
    assert type(head).__name__ == "MSDGSBoxResDetect"
    assert head.end2end is True and head.reg_max == 1 and head.nl == 3
    assert tuple(head.input_channels) == (64, 128, 256)
    box_widths = [int(tower[0].conv.out_channels) for tower in head.cv2]
    o2o_widths = [int(tower[0].conv.out_channels) for tower in head.one2one_cv2]
    assert box_widths == [16, 16, 16]
    assert o2o_widths == [16, 16, 16]

    candidate_match = matched_tensor_count(source_model, model)
    assert candidate_match == base_match == 402, (name, candidate_match, base_match)
    wrapper.load(str(OFFICIAL_WEIGHTS))
    model.eval()
    with torch.no_grad():
        shape = output_shape(model(torch.zeros(1, 3, 640, 640)))
    assert shape == (1, 300, 6), shape

    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint = CHECK_DIR / f"{name}_roundtrip.pt"
    wrapper.save(str(checkpoint))
    child = subprocess.run([sys.executable, str(Path(__file__).resolve()), "--reload-check", str(checkpoint)], text=True, capture_output=True)
    print(child.stdout, end="")
    if child.stderr:
        print(child.stderr, file=sys.stderr, end="")
    assert child.returncode == 0, child.returncode

    gflops_eval = model_gflops(model)
    fused = copy.deepcopy(model).eval()
    fused.fuse()
    fused_params = int(sum(p.numel() for p in fused.parameters()))
    gflops_fused = model_gflops(fused)
    with torch.no_grad():
        fused_shape = output_shape(fused(torch.zeros(1, 3, 640, 640)))
    assert fused_shape == (1, 300, 6)
    return {
        "cfg": str(cfg), "head": type(head).__name__, "input_channels": list(head.input_channels),
        "box_widths": box_widths, "eval_shape": list(shape), "fused_shape": list(fused_shape),
        "official_matched_tensors": candidate_match, "fused_params": fused_params,
        "gflops_eval_graph": gflops_eval, "gflops_fused_inference": gflops_fused,
        "roundtrip_checkpoint": str(checkpoint),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reload-check", type=Path)
    args = parser.parse_args()
    if args.reload_check:
        return reload_worker(args.reload_check)
    from ultralytics import YOLO
    for required in (BASE_YAML, OFFICIAL_WEIGHTS):
        if not required.exists():
            raise FileNotFoundError(required)
    source = YOLO(str(OFFICIAL_WEIGHTS), task="detect").model
    base = YOLO(str(BASE_YAML), task="detect").model
    base_match = matched_tensor_count(source, base)
    assert base_match == 402, base_match
    checks = {name: equivalence_and_gradient(name) for name in SPECS}
    candidates = {name: check_candidate(name, source, base_match) for name in SPECS}
    payload = {"base_official_matched_tensors": base_match, "behavior_checks": checks, "candidates": candidates}
    CHECK_DIR.mkdir(parents=True, exist_ok=True)
    report = CHECK_DIR / "report.json"
    report.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    print("BUILD_CHECK_MSDGS_BOXRES_OK", report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
