#!/usr/bin/env python
"""串行训练并独立评测两个 MSDGS box-residual Detect 候选。"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
import traceback

import yaml

ROOT = Path(os.environ.get("YOLO26_EXP_ROOT", "/root/autodl-tmp/neu-det-yolo26"))
DATA = ROOT / "dataset" / "neu-det.yaml"
BASE_YAML = ROOT / "generated_models_msdgs_gsdown_e250" / "y26n_gsdown_msdgs_135eq_e250.yaml"
OFFICIAL_WEIGHTS = Path(os.environ.get("YOLO26_EXP_WEIGHTS", ROOT / "yolo26n.pt"))
GEN_DIR = ROOT / "generated_models_msdgs_boxres_e250"
PROJECT = ROOT / "runs_msdgs_boxres_e250"
QUEUE_DIR = ROOT / "runs_msdgs_boxres_queue"
STATUS = QUEUE_DIR / "status.json"
REPORT_JSON = QUEUE_DIR / "report.json"
REPORT_MD = QUEUE_DIR / "report.md"
LOCK = QUEUE_DIR / ".queue.lock"
SCRIPT = Path(__file__).resolve()
NAMES = ["crazing", "inclusion", "patches", "pitted_surface", "rolled-in_scale", "scratches"]
SPECS = {
    "msdgs_p5box_res16": [16, False],
    "msdgs_p4detail_boxres": [16, True],
}
ORDER = list(SPECS)
MSDGS = {
    "map50": 0.7324113100352823,
    "map50_95": 0.3988372172746915,
    "per_class": {
        "crazing": 0.1770695825201802,
        "pitted_surface": 0.4686952771905249,
        "rolled-in_scale": 0.2584298478269593,
    },
}


def now():
    return time.strftime("%Y-%m-%d %H:%M:%S")


def atomic_json(path: Path, payload: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(path)


def save_status(status: str, current=None, pending=None, note=""):
    atomic_json(STATUS, {
        "status": status, "current": current, "pending": pending or [], "note": note,
        "updated_at": now(), "pid": os.getpid(), "project": str(PROJECT),
        "report_json": str(REPORT_JSON), "report_md": str(REPORT_MD),
    })


def generate_configs():
    base = yaml.safe_load(BASE_YAML.read_text(encoding="utf-8"))
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    result = {}
    for name, spec in SPECS.items():
        doc = json.loads(json.dumps(base))
        last = doc["head"][-1]
        assert last[0] == [16, 19, 22] and last[2] == "Detect", last
        last[2] = "MSDGSBoxResDetect"
        last[3] = ["nc", *spec]
        path = GEN_DIR / f"{name}.yaml"
        path.write_text("# generated by train_msdgs_boxres_queue.py\n" + yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")
        result[name] = path
    return result


def metric_dict(metrics):
    infer = float(metrics.speed.get("inference", 0.0) or 0.0)
    result = {
        "precision": float(metrics.box.mp), "recall": float(metrics.box.mr),
        "map50": float(metrics.box.map50), "map50_95": float(metrics.box.map),
        "infer_ms": infer, "fps_infer_only": 1000.0 / infer if infer else None,
        "per_class": {},
    }
    for i, cls_index in enumerate(metrics.ap_class_index):
        cls = int(cls_index)
        name = NAMES[cls] if cls < len(NAMES) else str(cls)
        result["per_class"][name] = {
            "precision": float(metrics.box.p[i]), "recall": float(metrics.box.r[i]),
            "map50": float(metrics.box.ap50[i]), "map50_95": float(metrics.box.ap[i]),
        }
    return result


def model_gflops(model):
    try:
        from ultralytics.utils.torch_utils import get_flops
        return float(get_flops(model, imgsz=640))
    except Exception as exc:  # noqa: BLE001
        print("WARN_GFLOPS", repr(exc), flush=True)
        return None


def train_worker(args):
    from ultralytics import YOLO
    target = PROJECT / args.run_name
    if target.exists():
        archive = target.with_name(target.name + f"_interrupted_{time.strftime('%Y%m%d_%H%M%S')}")
        target.rename(archive)
        print("ARCHIVED_EXISTING_RUN", target, "->", archive, flush=True)
    print("TRAIN_WORKER_START", os.getpid(), args.candidate, args.cfg, flush=True)
    model = YOLO(args.cfg, task="detect").load(str(OFFICIAL_WEIGHTS))
    params_unfused = int(sum(p.numel() for p in model.model.parameters()))
    model.train(
        data=str(DATA), epochs=args.epochs, imgsz=args.imgsz, batch=args.batch,
        workers=8, seed=0, device=0, project=str(PROJECT), name=args.run_name,
        exist_ok=True, patience=max(args.epochs, 250), cache=False, verbose=True,
    )
    weights = target / "weights" / "best.pt"
    if not weights.exists():
        raise FileNotFoundError(weights)
    atomic_json(target / "train_worker.json", {
        "status": "done", "candidate": args.candidate, "seed": 0, "cfg": args.cfg,
        "weights": str(weights), "params_unfused": params_unfused, "finished_at": now(),
    })
    print("TRAIN_WORKER_DONE", weights, flush=True)
    return 0


def eval_worker(args):
    from ultralytics import YOLO
    weights = Path(args.weights)
    if not weights.exists():
        raise FileNotFoundError(weights)
    print("EVAL_WORKER_FRESH_PROCESS", os.getpid(), weights, flush=True)
    best = YOLO(str(weights), task="detect")
    val = best.val(data=str(DATA), split="val", imgsz=args.imgsz, batch=args.batch, device=0,
                   project=str(PROJECT), name=f"{args.run_name}_val", exist_ok=True, verbose=False)
    test = best.val(data=str(DATA), split="test", imgsz=args.imgsz, batch=args.batch, device=0,
                    project=str(PROJECT), name=f"{args.run_name}_test", exist_ok=True, verbose=False)
    fused = YOLO(str(weights), task="detect")
    gflops_eval = model_gflops(fused.model)
    fused.model.fuse()
    params_fused = int(sum(p.numel() for p in fused.model.parameters()))
    gflops_fused = model_gflops(fused.model)
    payload = {
        "status": "done", "candidate": args.candidate, "seed": 0, "weights": str(weights),
        "params_fused": params_fused, "gflops_eval_graph": gflops_eval,
        "gflops_fused_inference": gflops_fused, "val": metric_dict(val), "test": metric_dict(test),
        "evaluated_at": now(), "eval_pid": os.getpid(),
    }
    atomic_json(PROJECT / args.run_name / "independent_eval.json", payload)
    print("EVAL_WORKER_DONE", flush=True)
    return 0


def gpu_idle():
    result = subprocess.run(
        ["nvidia-smi", "--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader"],
        text=True, capture_output=True, check=False,
    )
    if result.stdout.strip():
        raise RuntimeError(f"GPU already busy; refusing duplicate training:\n{result.stdout.strip()}")


def run_checked(command):
    print("SUBPROCESS", " ".join(command), flush=True)
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"subprocess failed rc={result.returncode}: {' '.join(command)}")


def gate(record):
    test = record["test"]
    pc = test["per_class"]
    deltas = {
        "map50": test["map50"] - MSDGS["map50"],
        "map50_95": test["map50_95"] - MSDGS["map50_95"],
        "crazing": pc["crazing"]["map50_95"] - MSDGS["per_class"]["crazing"],
        "pitted_surface": pc["pitted_surface"]["map50_95"] - MSDGS["per_class"]["pitted_surface"],
        "rolled-in_scale": pc["rolled-in_scale"]["map50_95"] - MSDGS["per_class"]["rolled-in_scale"],
    }
    checks = {
        "map50_95_gt_0.401794": test["map50_95"] > 0.401794,
        "map50_ge_0.722411": test["map50"] >= 0.722411,
        "target_class_gain_ge_0.01": max(deltas["pitted_surface"], deltas["rolled-in_scale"]) >= 0.01,
        "crazing_drop_le_0.02": deltas["crazing"] >= -0.02,
    }
    return {"pass": all(checks.values()), "checks": checks, "deltas_vs_msdgs": deltas}


def write_report(report):
    atomic_json(REPORT_JSON, report)
    lines = [
        "# MSDGS P5 box residual seed0 报告", "",
        "固定协议：250 epochs / imgsz=640 / batch=32 / cache=False / seed=0 / yolo26n.pt。",
        "最终指标由独立新进程重载磁盘 `best.pt` 后分别评测 val/test。", "",
        "| 候选 | 状态 | test mAP50 | test mAP50-95 | fused 参数 | GFLOPs | 晋级 |",
        "|---|---|---:|---:|---:|---:|---|",
    ]
    for name in ORDER:
        item = report["experiments"].get(name, {})
        if item.get("status") == "done":
            test = item["test"]
            lines.append(f"| {name} | done | {test['map50']:.6f} | {test['map50_95']:.6f} | {item.get('params_fused')} | {item.get('gflops_fused_inference')} | {'PASS' if item['gate']['pass'] else 'FAIL'} |")
        else:
            lines.append(f"| {name} | {item.get('status', 'pending')} | - | - | - | - | - |")
    lines += ["", "## 原始结果", "", "```json", json.dumps(report, indent=2, ensure_ascii=False), "```", ""]
    REPORT_MD.parent.mkdir(parents=True, exist_ok=True)
    REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


def orchestrate(args):
    import fcntl
    QUEUE_DIR.mkdir(parents=True, exist_ok=True)
    handle = LOCK.open("a+")
    try:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError as exc:
        raise RuntimeError("another MSDGS boxres queue is already running") from exc
    for required in (DATA, BASE_YAML, OFFICIAL_WEIGHTS):
        if not required.exists():
            raise FileNotFoundError(required)
    gpu_idle()
    configs = generate_configs()
    report = {
        "schema_version": 1, "started_at": now(),
        "protocol": {"epochs": args.epochs, "imgsz": args.imgsz, "batch": args.batch, "cache": False, "seed": 0,
                     "init_weights": str(OFFICIAL_WEIGHTS), "data": str(DATA),
                     "final_eval": "fresh subprocess reloads best.pt for val and test"},
        "baseline": MSDGS, "experiments": {},
    }
    write_report(report)
    for index, candidate in enumerate(ORDER):
        pending = ORDER[index + 1:]
        run_name = f"{candidate}_seed0"
        try:
            gpu_idle()
            save_status("training", candidate, pending, "fresh train; resume disabled")
            run_checked([sys.executable, str(SCRIPT), "--worker-train", "--candidate", candidate,
                         "--run-name", run_name, "--cfg", str(configs[candidate]),
                         "--epochs", str(args.epochs), "--imgsz", str(args.imgsz), "--batch", str(args.batch)])
            weights = PROJECT / run_name / "weights" / "best.pt"
            save_status("evaluating", candidate, pending, "fresh process reloads best.pt")
            run_checked([sys.executable, str(SCRIPT), "--worker-eval", "--candidate", candidate,
                         "--run-name", run_name, "--weights", str(weights),
                         "--imgsz", str(args.imgsz), "--batch", str(args.batch)])
            record = json.loads((PROJECT / run_name / "independent_eval.json").read_text(encoding="utf-8"))
            record["cfg"] = str(configs[candidate])
            record["gate"] = gate(record)
            report["experiments"][candidate] = record
        except Exception as exc:  # noqa: BLE001
            traceback.print_exc()
            report["experiments"][candidate] = {"status": "failed", "error": repr(exc), "failed_at": now()}
        write_report(report)
    report["finished_at"] = now()
    write_report(report)
    save_status("done", None, [], "both seed0 candidates finished or isolated")
    print("MSDGS_BOXRES_QUEUE_DONE", REPORT_JSON, flush=True)
    return 0


def parser():
    p = argparse.ArgumentParser()
    p.add_argument("--worker-train", action="store_true")
    p.add_argument("--worker-eval", action="store_true")
    p.add_argument("--candidate", choices=ORDER)
    p.add_argument("--run-name")
    p.add_argument("--cfg")
    p.add_argument("--weights")
    p.add_argument("--epochs", type=int, default=250)
    p.add_argument("--imgsz", type=int, default=640)
    p.add_argument("--batch", type=int, default=32)
    return p


def main():
    args = parser().parse_args()
    if args.worker_train:
        return train_worker(args)
    if args.worker_eval:
        return eval_worker(args)
    return orchestrate(args)


if __name__ == "__main__":
    raise SystemExit(main())
